//bm_api.c
void *bgbmid_malloc(int size);
void bgbmid_free(void *buf);
void *bgbmid_realloc(void *buf, int size);
int BGBMID_SetInputBuffer(BGBMID_Context *ctx, byte *buf, int sz);
int BGBMID_SynthStream(BGBMID_Context *ctx, byte *buf, int sz);
int BGBMID_SetOutputBuffer(BGBMID_Context *ctx, short *buf, int len);
short *BGBMID_GetOutputBuffer(BGBMID_Context *ctx);
int BGBMID_GetOutputBufferPos(BGBMID_Context *ctx);
int BGBMID_GetOutputBufferSize(BGBMID_Context *ctx);
int BGBMID_GetOutputSampleRate(BGBMID_Context *ctx);
int BGBMID_SetNoteTicks(BGBMID_Context *ctx, int ticks);
int BGBMID_SetNoteLen(BGBMID_Context *ctx, float sec);
int BGBMID_SetRateScale(BGBMID_Context *ctx, float scale);
BGBMID_Context *BGBMID_NewContext();
//bm_file.c
int BGBMID_ReadS16BE(void *fd);
int BGBMID_ReadS32BE(void *fd);
void BGBMID_WriteS16BE(void *fd, int v);
void BGBMID_WriteS32BE(void *fd, int v);
int BGBMID_ReadDelta(void *fd);
int BGBMID_DumpMidi0(char *name, byte *strm, int sz, int nticks);
int BGBMID_DumpMidi1(char *name, byte **strm, int *sz, int ntrk, int nticks);
int BGBMID_ReadMidi(char *name, byte **strm, int *sz, int *rntrk, int *rnticks);
int BGBMID_DecVLI(byte **rcs);
int BGBMID_EncVLI(byte **rct, int val);
int BGBMID_TryDecVLI(byte **rcs, byte *ce);
int BGBMID_ReadMidiMerge(char *name, byte **rstrm, int *rsz, int *rnticks);
//bm_patch.c
BGBMID_Patch *BGBMID_LookupPatch(char *name);
char *BGBMID_MidiPatchName(int idx);
char *BGBMID_MidiDrumPatchName(int idx);
int BGBMID_ReadS16LE(void *fd);
int BGBMID_ReadS32LE(void *fd);
void BGBMID_WriteS16LE(void *fd, int v);
void BGBMID_WriteS32LE(void *fd, int v);
BGBMID_Patch *BGBMID_LoadPatchGUS(char *name);
int BGBMID_TestPatchFilt(char *name, BGBMID_Patch *pat);
BGBMID_Patch *BGBMID_LoadPatchWav(char *name);
int BGBMID_StorePatchWav(char *name, BGBMID_Patch *pat);
int BGBMID_DumpPatches();
BGBMID_Patch *BGBMID_LoadPatch(char *name);
//bm_synth.c
int BGBMID_InitChannels(BGBMID_Context *ctx);
int BGBMID_BlendNoteTone(BGBMID_Context *ctx, int chan, int len, int note);
int BGBMID_BlendNoteSampLoop(BGBMID_Context *ctx, int chan, int len, int note,BGBMID_Sample *samp, float freq);
int BGBMID_BlendNoteSampNoLoop(BGBMID_Context *ctx, int chan, int len, int note,BGBMID_Sample *samp, float freq);
int BGBMID_BlendNote(BGBMID_Context *ctx, int chan, int len, int note);
int BGBMID_BlendNoteDrum(BGBMID_Context *ctx, int chan, int len, int note);
int BGBMID_BlendChannel(BGBMID_Context *ctx, int chan, int samp);
int BGBMID_DeltaTime(BGBMID_Context *ctx, int step);
int BGBMID_NoteOn(BGBMID_Context *ctx, int chan, int note, int vel);
int BGBMID_NoteOff(BGBMID_Context *ctx, int chan, int note, int vel);
int BGBMID_NoteAftertouch(BGBMID_Context *ctx, int chan, int note, int val);
int BGBMID_Controller(BGBMID_Context *ctx, int chan, int num, int val);
int BGBMID_ProgramChange(BGBMID_Context *ctx, int chan, int num);
int BGBMID_ChannelAftertouch(BGBMID_Context *ctx, int chan, int val);
int BGBMID_PitchBlend(BGBMID_Context *ctx, int chan, int val);
int BGBMID_SynthStep(BGBMID_Context *ctx);
int BGBMID_DoSynth(BGBMID_Context *ctx);
int BGBMID_SynthSamples(BGBMID_Context *ctx, short *buf, int len);
//bm_util.c
void *bgbmid_ralloc(int sz);
char **bgbmid_split(char *s);
char *bgbmid_rstrdup(char *s);
char *bgbmid_strdup(char *s);
char *bgbmid_strdup(char *str);
void bgbmid_file_init();
void *bgbmid_fopen(char *name, char *mode);
void bgbmid_fclose(void *fd);
int bgbmid_fread(void *buf, int i, int j, void *fd);
int bgbmid_fwrite(void *buf, int i, int j, void *fd);
void bgbmid_fseek(void *buf, int i, int j);
int bgbmid_fgetc(void *fd);
int bgbmid_fputc(int i, void *fd);
int bgbmid_ftell(void *fd);
int bgbmid_feof(void *fd);
int bgbmid_fgets(void *buf, int sz, void *fd);
//bm_wave.c
int BGBMID_ScaleSample(short *d, int dl, short *s, int sl);
byte *BGBMID_LoadWAV(char *name, int *rch, int *rr, int *rbits, int *rlen);
void BGBMID_StoreWAV(char *name, byte *buf, int ch, int rt, int bits, int len);
short *BGBMID_LoadWAV_Mono16(char *name, int *rrt, int *rlen);
short *BGBMID_LoadWAV_44Mono16(char *name, int *rlen);
short *BGBMID_LoadWAV_16Mono16(char *name, int *rlen);
int BGBMID_NormalizeSample(short *dst, short *src, int len);
double BGBMID_SplinePolate(short *samp, int len, double t);
double BGBMID_SplinePolateF(float *samp, int len, double t);
int BGBMID_ScaleSampleTrilinear(short *d, int dl, short *s, int sl);
double BGBMID_Sinc(double x);
double BGBMID_SincPolate(short *samp, int len, double f, int n);
int BGBMID_ScaleSampleSinc(short *d, int dl, short *s, int sl);
double BGBMID_SplinePolate(short *samp, int len, double t);
double BGBMID_SplinePolateF(float *samp, int len, double t);
double BGBMID_SplinePolateLoop(short *samp, int len, double t);
int BGBMID_ScaleSampleSpline(short *d, int dl, short *s, int sl);
int BGBMID_ScaleSample(short *d, int dl, short *s, int sl);
int BGBMID_SampleCompressor(short *db, int dl, short *sb, int sl,int ivl, int isl, int irl);
