#include "cparse/cparse_token.c"
#include "cparse/cparse_misc.c"
#include "cparse/cparse_type.c"
#include "cparse/cparse_def.c"
#include "cparse/cparse_expr2.c"
#include "cparse/cparse_stmt.c"
#include "cparse/cparse_reduce.c"
#include "cparse/cppi_interp.c"
#include "cparse/preproc.c"

// #include "jparse/jp_token2.c"
// #include "jparse/jp_misc.c"
// #include "jparse/jp_type.c"
// #include "jparse/jp_def.c"
// #include "jparse/jp_tyexpr.c"
// #include "jparse/jp_expr2.c"
// #include "jparse/jp_stmt.c"

//#include "cc/cc_compile.c"
//#include "cc/cc_expr.c"
//#include "cc/cc_index.c"
//#include "cc/cc_reduce.c"
//#include "cc/ccm_compile.c"

// #include "cc/bs2cc_compile.c"
// #include "cc/bs2cc_expr.c"
// #include "cc/bs2cc_index.c"

#if 0
#include "frcc/frbc_call.c"
#include "frcc/frbc_const.c"
#include "frcc/frbc_dbgdisasm.c"
#include "frcc/frbc_emit.c"
#include "frcc/frbc_global.c"
#include "frcc/frbc_image.c"
#include "frcc/frbc_pred.c"
#include "frcc/frbc_ptrops.c"
#include "frcc/frbc_register.c"
#include "frcc/frbc_stack.c"
#include "frcc/frbc_struct.c"
#include "frcc/frbc_type.c"

#include "frcc/frcc_bind.c"
#include "frcc/frcc_compile.c"
#include "frcc/frcc_expr.c"
#include "frcc/frcc_index.c"
#include "frcc/frcc_reduce.c"
#endif

// #include "frbc_cgn/frj_context.c"
// #include "frbc_cgn/frj_function.c"
// #include "frbc_cgn/frj_image.c"
// #include "frbc_cgn/frj_loader.c"
// #include "frbc_cgn/frj_opcode.c"
// #include "frbc_cgn/frj_struct.c"
// #include "frbc_cgn/frj_trace.c"
// #include "frbc_cgn/frj_mkop.c"

#include "mm/cc_tokord.c"

#ifdef BGBCC_BCCX2

#include "mm/cca_node.c"
#include "mm/cca_print.c"

#else

#include "mm/ccx_node.c"
#include "mm/ccx_print.c"
#include "mm/ccx_parse.c"

#endif

#include "mm/cc_float16.c"
#include "mm/cc_malloc.c"
// #include "mm/dytf_base.c"
// #include "mm/dytf_cons.c"
// #include "mm/dytf_opr.c"

#include "mm/cc_thread.c"

#include "mm/cc_int128.c"
#include "mm/cc_float128.c"


#include "mm/inflate.c"
#include "mm/deflate.c"
#include "mm/cc_exwad.c"
#include "mm/ccl_context.c"
#include "mm/ccl_coff.c"
#include "mm/ccl_elf.c"

#include "mm/dyll_metapath.c"
#include "mm/dyll_metabin.c"


#include "ccxl/ccxl_cgif.c"
#include "ccxl/ccxl_compile.c"
#include "ccxl/ccxl_const.c"
#include "ccxl/ccxl_expr.c"
#include "ccxl/ccxl_fold.c"
#include "ccxl/ccxl_global.c"
#include "ccxl/ccxl_index.c"
#include "ccxl/ccxl_infer.c"
#include "ccxl/ccxl_pred.c"
#include "ccxl/ccxl_reduce.c"
#include "ccxl/ccxl_register.c"
#include "ccxl/ccxl_ril3.c"
#include "ccxl/ccxl_stack.c"
#include "ccxl/ccxl_stack_bin.c"
#include "ccxl/ccxl_stack_un.c"
#include "ccxl/ccxl_struct.c"
#include "ccxl/ccxl_trace.c"
#include "ccxl/ccxl_type.c"

#include "ccxl/ccxl_fr2e.c"
#include "ccxl/ccxl_lvatag.c"

#include "shcc/shx_binop.c"
#include "shcc/shx_bufasm.c"
#include "shcc/shx_cgif.c"
#include "shcc/shx_conv.c"
#include "shcc/shx_elf.c"
#include "shcc/shx_emit.c"
#include "shcc/shx_emit_sec.c"
#include "shcc/shx_emit_opc.c"
#include "shcc/shx_emit_mov.c"
#include "shcc/shx_emit_lbl.c"
#include "shcc/shx_emit_bra.c"
#include "shcc/shx_emit_queue.c"
#include "shcc/shx_fltrom.c"
#include "shcc/shx_fpreg.c"
#include "shcc/shx_frame.c"
#include "shcc/shx_ldix.c"
#include "shcc/shx_lparith.c"
#include "shcc/shx_lpreg.c"
#include "shcc/shx_lqarith.c"
#include "shcc/shx_lvarith.c"
#include "shcc/shx_lxarith.c"
#include "shcc/shx_pecoff.c"
#include "shcc/shx_register.c"
#include "shcc/shx_softfpu.c"
#include "shcc/shx_struct.c"
#include "shcc/shx_vreg.c"

#include "bsrcc/bsr_binop.c"
#include "bsrcc/bsr_bufasm.c"
#include "bsrcc/bsr_cgif.c"
#include "bsrcc/bsr_conv.c"
// #include "bsrcc/bsr_elf.c"
#include "bsrcc/bsr_emit.c"
#include "bsrcc/bsr_emit_sec.c"
#include "bsrcc/bsr_emit_opc.c"
#include "bsrcc/bsr_emit_mov.c"
#include "bsrcc/bsr_emit_lbl.c"
#include "bsrcc/bsr_emit_bra.c"
#include "bsrcc/bsr_emit_queue.c"
#include "bsrcc/bsr_fltrom.c"
#include "bsrcc/bsr_fpstub.c"
#include "bsrcc/bsr_frame.c"
#include "bsrcc/bsr_ldix.c"
#include "bsrcc/bsr_lparith.c"
#include "bsrcc/bsr_lpreg.c"
// #include "bsrcc/bsr_lqarith.c"
#include "bsrcc/bsr_lvarith.c"
#include "bsrcc/bsr_lxarith.c"
#include "bsrcc/bsr_pecoff.c"
#include "bsrcc/bsr_register.c"
#include "bsrcc/bsr_softfpu.c"
#include "bsrcc/bsr_struct.c"
#include "bsrcc/bsr_vreg.c"


#include "jx2cc/jx2_asmdump.c"
#include "jx2cc/jx2_binop.c"
#include "jx2cc/jx2_bufasm.c"
#include "jx2cc/jx2_cgif.c"
#include "jx2cc/jx2_conv.c"
#include "jx2cc/jx2_emit.c"
#include "jx2cc/jx2_emit_sec.c"
#include "jx2cc/jx2_emit_opc.c"
#include "jx2cc/jx2_emit_mov.c"
#include "jx2cc/jx2_emit_lbl.c"
#include "jx2cc/jx2_emit_bra.c"
#include "jx2cc/jx2_emit_queue.c"
#include "jx2cc/jx2_emrv_opc.c"
#include "jx2cc/jx2_fltrom.c"
#include "jx2cc/jx2_fparith.c"
#include "jx2cc/jx2_fpreg2x.c"
#include "jx2cc/jx2_fpstub.c"
#include "jx2cc/jx2_frame.c"
#include "jx2cc/jx2_frm_layout.c"
#include "jx2cc/jx2_frm_prolog.c"
#include "jx2cc/jx2_frm_epilog.c"
#include "jx2cc/jx2_ldix.c"
#include "jx2cc/jx2_lparith.c"
#include "jx2cc/jx2_lpreg.c"
#include "jx2cc/jx2_lqarith.c"
#include "jx2cc/jx2_lvarith.c"
#include "jx2cc/jx2_lxarith.c"
#include "jx2cc/jx2_lzarith.c"
#include "jx2cc/jx2_v4arith.c"
#include "jx2cc/jx2_pecoff.c"
#include "jx2cc/jx2_register.c"
#include "jx2cc/jx2_softfpu.c"
#include "jx2cc/jx2_struct.c"
#include "jx2cc/jx2_vreg.c"
#include "jx2cc/jx2_wexify.c"

#include "bgbmeta.c"
