#include <stdio.h>
#include <stdlib.h>
#include <string.h>

char *in_txt;
char *out_c;
char *out_h;
char *out_suf, *out_suf2;

char *ops[16384];
char *args[16384];
char *sfis[16384];

char *kralloc_buffer=NULL;
int kralloc_pos=0;

void *kralloc(int sz)
{
	char *s;

	if(!kralloc_buffer)kralloc_buffer=malloc(262144);
	if((kralloc_pos+sz)>=262144)kralloc_pos=0;

	s=kralloc_buffer+kralloc_pos;
	kralloc_pos+=sz;
	return((void *)s);
}

char **ksplit(char *s)
{
	char **a, *t;
	int i;

	a=kralloc(64*sizeof(char *));
	i=0;
	while(*s)
	{
		while(*s && (*s<=' '))s++;
		if(!*s)break;
		if(*s=='#')break;
		if(*s==';')break;
		if((s[0]=='/') && (s[1]=='/'))
			break;

		t=kralloc(256);
		a[i++]=t;

		if(*s=='"')
		{
			s++;
			while(*s && (*s!='"'))*t++=*s++;
			if(*s=='"')s++;

			*t++=0;
			continue;
		}

		while(*s && (*s>' '))*t++=*s++;
		*t++=0;
	}
	a[i]=NULL;

	return(a);
}

int is_sfi(char *s)
{
	while(*s)
	{
		if(*s=='=')return(1);
		s++;
	}
	return(0);
}

int main(int argc, char *argv[])
{
	char buf[256], buf2[256];
	FILE *fd;
	char *s, *t, **a;
	int i, j, k, l, n;

	in_txt="bgbcc_token.txt";
	out_c="mm/cc_tokord.c";
	out_h="include/bgbcc_tokord.h";
	out_suf="bgbcc_tokord";
	out_suf2="BOTK";

	memset(ops, 0, 16384*sizeof(char *));
	memset(args, 0, 16384*sizeof(char *));
	memset(sfis, 0, 16384*sizeof(char *));

	fd=fopen(in_txt, "rt");
	if(!fd)
	{
		printf("fail open %s\n", in_txt);
		return(-1);
	}

	n=0; i=0;
	while(!feof(fd))
	{
		memset(buf, 0, 256);
		fgets(buf, 255, fd);

		s=buf;
		while(*s && (*s<=' '))s++;
		if(!*s)continue;
		if(*s==';')continue;
		if(*s=='#')continue;
		if(*s=='/')continue;

		a=ksplit(s);
		if(!a[0])continue;

		if(a[1] && strcmp(a[1], "-"))
			{ i=atoi(a[1]); }
		else
			{ i++; while(ops[i])i++; }
		ops[i]=strdup(a[0]);

#if 1
		if(a[2])
		{
			if(strcmp(a[2], "-"))
			{
				if(!is_sfi(a[2]))
				{
					args[i]=strdup(a[2]);

					if(a[3] && strcmp(a[3], "-"))
						sfis[i]=strdup(a[3]);
				}else sfis[i]=strdup(a[2]);
			}else
			{
				if(a[3] && strcmp(a[3], "-"))
					sfis[i]=strdup(a[3]);
			}
		}
#endif

		if(i>=n)n=i+1;
	}
	fclose(fd);

	fd=fopen(out_c, "wt");
	if(!fd) { printf("Fail Out C %s\n", out_c); return(-1); }
	fprintf(fd, "/* Autogenerated source */\n");

	j=0; k=0; l=0;
	for(i=0; i<n; i++)
	{
		if(ops[i])j++;
		if(args[i])k++;
		if(sfis[i])l++;
	}

//	fprintf(fd, "/* OPS %d, W/Args %d, W/Flow %d */\n\n", j, k, l);
	fprintf(fd, "#include <stdio.h>\n\n");

	fprintf(fd, "int %s_nops=%d;\n\n", out_suf, n);

	fprintf(fd, "char *%s_strs[]={\n", out_suf);
	j=0;
	for(i=0; i<n; i++)
	{
		s=ops[i];
		if(!s)s="";

		strcpy(buf, s);

#if 0
		s=buf;
		while(*s)
		{
			if((*s>='A') && (*s<='Z'))
				*s=*s-'A'+'a';
			s++;
		}
#endif

		fprintf(fd, "\"%s\", ", buf);
		j+=strlen(buf)+4;

		if(j>64)
		{
			fprintf(fd, "\n");
			j=0;
		}
	}
	fprintf(fd, "NULL};\n\n");

#if 1
	fprintf(fd, "char *%s_args[]={\n", out_suf);
	j=0;
	for(i=0; i<n; i++)
	{
		s=args[i];
		if(!s)s="";

		fprintf(fd, "\"%s\", ", s);
		j+=strlen(s)+4;

		if(j>64)
		{
			fprintf(fd, "\n");
			j=0;
		}
	}
	fprintf(fd, "NULL};\n\n");

	fprintf(fd, "char *%s_sfis[]={\n", out_suf);
	j=0;
	for(i=0; i<n; i++)
	{
		s=sfis[i];
		if(!s)s="";

		fprintf(fd, "\"%s\", ", s);
		j+=strlen(s)+4;

		if(j>64)
		{
			fprintf(fd, "\n");
			j=0;
		}
	}
	fprintf(fd, "NULL};\n\n");
#endif

	fclose(fd);

	fd=fopen(out_h, "wt");
	if(!fd) { printf("Fail Out H %s\n", out_h); return(-1); }
	fprintf(fd, "/* Autogenerated header */\n\n");

	for(i=0; i<n; i++)if(ops[i])
	{
		strcpy(buf, ops[i]);
		s=buf;
		while(*s)
		{
			if((*s>='a') && (*s<='z'))
				*s=*s-'a'+'A';
			s++;
		}

		sprintf(buf2, "#define %s_%s", out_suf2, buf);
		j=(47-strlen(buf2))/8; if(!j)j=1;

//		j=(31-strlen(buf))/8;
		fprintf(fd, "#define %s_%s", out_suf2, buf);

		while(j--)fprintf(fd, "\t");
		fprintf(fd, "%d\n", i);
	}

	return(0);
}
