int WINAPI          AccessResource( HINSTANCE, HRSRC );
HGLOBAL WINAPI      AllocResource( HINSTANCE, HRSRC, DWORD );
int WINAPI          Catch( int FAR * );
void WINAPI         DebugBreak( void );
void WINAPI         DirectedYield( HTASK );
void WINAPI         FatalAppExit( UINT, LPCSTR );
void WINAPI         FatalExit( int );
HRSRC WINAPI        FindResource( HINSTANCE, LPCSTR, LPCSTR );
void WINAPI         FreeLibrary( HINSTANCE );
BOOL WINAPI         FreeModule( HINSTANCE );
void WINAPI         FreeProcInstance( FARPROC );
BOOL WINAPI         FreeResource( HGLOBAL );
HGLOBAL WINAPI      GetCodeHandle( FARPROC );
void WINAPI         GetCodeInfo( FARPROC, SEGINFO FAR * );
UINT WINAPI         GetCurrentPDB( void );
HTASK WINAPI        GetCurrentTask( void );
LPSTR WINAPI        GetDOSEnvironment( void );
UINT WINAPI         GetDriveType( int );
DWORD WINAPI        GetFreeSpace( UINT );
int WINAPI          GetInstanceData( HINSTANCE, BYTE NEAR *, int );
int WINAPI          GetModuleFileName( HINSTANCE, LPSTR, int );
HMODULE WINAPI      GetModuleHandle( LPCSTR );
int WINAPI          GetModuleUsage( HINSTANCE );
UINT WINAPI         GetNumTasks( void );
UINT WINAPI         GetPrivateProfileInt( LPCSTR, LPCSTR, int, LPCSTR );
int WINAPI          GetPrivateProfileString( LPCSTR, LPCSTR, LPCSTR, LPSTR, int, LPCSTR );
FARPROC WINAPI      GetProcAddress( HINSTANCE, LPCSTR );
UINT WINAPI         GetProfileInt( LPCSTR, LPCSTR, int );
int WINAPI          GetProfileString( LPCSTR, LPCSTR, LPCSTR, LPSTR, int );
UINT WINAPI         GetSystemDirectory( LPSTR, UINT );
BYTE WINAPI         GetTempDrive( char );
int WINAPI          GetTempFileName( BYTE, LPCSTR, UINT, LPSTR );
DWORD WINAPI        GetVersion( void );
DWORD WINAPI        GetWinFlags( void );
UINT WINAPI         GetWindowsDirectory( LPSTR, UINT );
HINSTANCE WINAPI    LoadLibrary( LPCSTR );
HINSTANCE WINAPI    LoadModule( LPCSTR, LPVOID );
HGLOBAL WINAPI      LoadResource( HINSTANCE, HRSRC );
FARPROC WINAPI      MakeProcInstance( FARPROC, HINSTANCE );
void WINAPI         OutputDebugString( LPCSTR );
UINT WINAPI         SetErrorMode( UINT );
RSRCHDLRPROC WINAPI SetResourceHandler( HINSTANCE, LPCSTR, RSRCHDLRPROC );
LONG WINAPI         SetSwapAreaSize( UINT );
DWORD WINAPI        SizeofResource( HINSTANCE, HRSRC );
void WINAPI         SwapRecording( UINT );
void WINAPI         SwitchStackBack( void );
void WINAPI         SwitchStackTo( UINT, UINT, UINT );
void WINAPI         Throw( const int FAR *, int );
void WINAPI         ValidateCodeSegments( void );
UINT WINAPI         WinExec( LPCSTR, UINT );
BOOL WINAPI         WritePrivateProfileString( LPCSTR, LPCSTR, LPCSTR, LPCSTR );
BOOL WINAPI         WriteProfileString( LPCSTR, LPCSTR, LPCSTR );
void WINAPI         Yield( void );
void FAR * WINAPI   LockResource( HGLOBAL );

UINT WINAPI         AllocDStoCSAlias( UINT );
UINT WINAPI         AllocSelector( UINT );
UINT WINAPI         FreeSelector( UINT );
DWORD WINAPI        GetSelectorBase( UINT );
DWORD WINAPI        GetSelectorLimit( UINT );
HGLOBAL WINAPI      GlobalAlloc( UINT, DWORD );
DWORD WINAPI        GlobalCompact( DWORD );
DWORD WINAPI        GlobalDosAlloc( DWORD );
UINT WINAPI         GlobalDosFree( UINT );
void WINAPI         GlobalFix( HGLOBAL );
UINT WINAPI         GlobalFlags( HGLOBAL );
HGLOBAL WINAPI      GlobalFree( HGLOBAL );
DWORD WINAPI        GlobalHandle( UINT );
HGLOBAL WINAPI      GlobalLRUNewest( HGLOBAL );
HGLOBAL WINAPI      GlobalLRUOldest( HGLOBAL );
void WINAPI         GlobalNotify( GNOTIFYPROC );
UINT WINAPI         GlobalPageLock( HGLOBAL );
UINT WINAPI         GlobalPageUnlock( HGLOBAL );
HGLOBAL WINAPI      GlobalReAlloc( HGLOBAL, DWORD, UINT );
DWORD WINAPI        GlobalSize( HGLOBAL );
BOOL WINAPI         GlobalUnWire( HGLOBAL );
void WINAPI         GlobalUnfix( HGLOBAL );
BOOL WINAPI         GlobalUnlock( HGLOBAL );
void WINAPI         LimitEmsPages( DWORD );
HLOCAL WINAPI       LocalAlloc( UINT, UINT );
UINT WINAPI         LocalCompact( UINT );
UINT WINAPI         LocalFlags( HLOCAL );
HLOCAL WINAPI       LocalFree( HLOCAL );
BOOL WINAPI         LocalInit( UINT, UINT, UINT );
HLOCAL WINAPI       LocalReAlloc( HLOCAL, UINT, UINT );
UINT WINAPI         LocalShrink( HLOCAL, UINT );
UINT WINAPI         LocalSize( HLOCAL );
BOOL WINAPI         LocalUnlock( HLOCAL );
HGLOBAL WINAPI      LockSegment( UINT );
UINT WINAPI         PrestoChangoSelector( UINT, UINT );
UINT WINAPI         SetHandleCount( UINT );
UINT WINAPI         SetSelectorBase( UINT, DWORD );
UINT WINAPI         SetSelectorLimit( UINT, DWORD );
void WINAPI         UnlockSegment( UINT );
void WINAPI         ValidateFreeSpaces( void );
void FAR * WINAPI   GlobalLock( HGLOBAL );
void FAR * WINAPI   GlobalWire( HGLOBAL );
void NEAR * WINAPI  LocalLock( HLOCAL );
HLOCAL WINAPI       LocalHandle( UINT );

HFILE WINAPI        _lclose( HFILE );
HFILE WINAPI        _lcreat( LPCSTR, int );
LONG WINAPI         _llseek( HFILE, LONG, int );
HFILE WINAPI        _lopen( LPCSTR, int );
UINT WINAPI         _lread( HFILE, void __huge *, UINT );
UINT WINAPI         _lwrite( HFILE, const void __huge *, UINT );
HFILE WINAPI        OpenFile( LPCSTR, OFSTRUCT FAR *, UINT );

ATOM WINAPI         AddAtom( LPCSTR );
ATOM WINAPI         DeleteAtom( ATOM );
ATOM WINAPI         FindAtom( LPCSTR );
HLOCAL WINAPI       GetAtomHandle( ATOM );
UINT WINAPI         GetAtomName( ATOM, LPSTR, int );
BOOL WINAPI         InitAtomTable( int );

LPSTR WINAPI        lstrcat( LPSTR, LPCSTR );
LPSTR WINAPI        lstrcpy( LPSTR, LPCSTR );
int WINAPI          lstrlen( LPCSTR );

BOOL WINAPI         IsBadCodePtr( FARPROC );
BOOL WINAPI         IsBadHugeReadPtr( const void __huge *, DWORD );
BOOL WINAPI         IsBadHugeWritePtr( void __huge *, DWORD );
BOOL WINAPI         IsBadReadPtr( const void FAR *, UINT );
BOOL WINAPI         IsBadStringPtr( const void FAR *, UINT );
BOOL WINAPI         IsBadWritePtr( void FAR *, UINT );
BOOL WINAPI         IsTask( HTASK );

void FAR __cdecl    DebugOutput( UINT, LPCSTR, ... );
BOOL WINAPI         GetWinDebugInfo( WINDEBUGINFO FAR * , UINT );
void WINAPI         LogError( UINT, void FAR * );
void WINAPI         LogParamError( UINT, FARPROC, void FAR* );
BOOL WINAPI         SetWinDebugInfo( const WINDEBUGINFO FAR * );

long WINAPI         _hread( HFILE, void __huge *, long );
long WINAPI         _hwrite( HFILE, const void __huge *, long );

void WINAPI         hmemcpy( void __huge *, const void __huge *, long );
LPSTR WINAPI        lstrcpyn( LPSTR, LPCSTR, int );

BOOL WINAPI         IsDBCSLeadByte( BYTE );
