#include "raswgl/ragl_begin.c"
#include "raswgl/ragl_clip.c"
#include "raswgl/ragl_gldrv.c"

#include "raswgl/ragl_light.c"
#include "raswgl/ragl_raswprim.c"
#include "raswgl/ragl_teximage.c"
#include "raswgl/ragl_transform.c"
#include "raswgl/ragl_vertexarray.c"

#include "vecmath/math_clip.c"
#include "vecmath/math_hullf.c"
#include "vecmath/math_m3.c"
#include "vecmath/math_m4.c"
#include "vecmath/math_mf.c"
#include "vecmath/math_n.c"
#include "vecmath/math_plane.c"
#include "vecmath/math_quat.c"
#include "vecmath/math_solid.c"
#include "vecmath/math_v3f.c"
#include "vecmath/math_vecnf.c"
#include "vecmath/math_vnf.c"
#include "vecmath/mathlib_d.c"
#include "vecmath/mathlib_f.c"
