#define TKGDI_PALDFL_GRAYSCALE		0xF0
#define TKGDI_PALDFL_RGBI16			0x00

#define TKGDI_PALDFL_TRANSPARENT	0xF0

#define TKGDI_PALDFL_BLACK			0x00

#define TKGDI_PALDFL_BLACK_LO		0x00
#define TKGDI_PALDFL_BLUE_LO		0x01
#define TKGDI_PALDFL_GREEN_LO		0x02
#define TKGDI_PALDFL_CYAN_LO		0x03
#define TKGDI_PALDFL_RED_LO			0x04
#define TKGDI_PALDFL_MAGENTA_LO		0x05
#define TKGDI_PALDFL_BROWN_LO		0x06
#define TKGDI_PALDFL_GRAY_LO		0x07

#define TKGDI_PALDFL_BLACK_HI		0x08
#define TKGDI_PALDFL_BLUE_HI		0x09
#define TKGDI_PALDFL_GREEN_HI		0x0A
#define TKGDI_PALDFL_CYAN_HI		0x0B
#define TKGDI_PALDFL_RED_HI			0x0C
#define TKGDI_PALDFL_MAGENTA_HI		0x0D
#define TKGDI_PALDFL_YELLOW_HI		0x0E
#define TKGDI_PALDFL_WHITE_HI		0x0F

