#include <vx_kernel32.h>

WINBASEAPI BOOL WINAPI BackupEventLogA(HANDLE a0, LPCSTR a1)
WINBASEAPI BOOL WINAPI BackupEventLogW(HANDLE a0, LPCWSTR a1)
WINBASEAPI BOOL WINAPI BackupRead(
	HANDLE a0, LPBYTE a1, DWORD a2, LPDWORD a3, BOOL a4, BOOL a5, LPVOID *a6)
WINBASEAPI BOOL WINAPI BackupSeek(
	HANDLE a0, DWORD a1, DWORD a2, LPDWORD a3, LPDWORD a4, LPVOID *a5)
WINBASEAPI BOOL WINAPI BackupWrite(
	HANDLE a0, LPBYTE a1, DWORD a2, LPDWORD a3, BOOL a4, BOOL a5, LPVOID *a6)
WINBASEAPI BOOL WINAPI Beep(DWORD a0, DWORD a1)
WINBASEAPI HANDLE WINAPI BeginUpdateResourceA(LPCSTR a0, BOOL a1)
WINBASEAPI HANDLE WINAPI BeginUpdateResourceW(LPCWSTR a0, BOOL a1)
WINBASEAPI BOOL WINAPI BuildCommDCBA(LPCSTR a0, LPDCB a1)
WINBASEAPI BOOL WINAPI BuildCommDCBW(LPCWSTR a0, LPDCB a1)
WINBASEAPI BOOL WINAPI BuildCommDCBAndTimeoutsA(LPCSTR a0, LPDCB a1, LPCOMMTIMEOUTS a0)
WINBASEAPI BOOL WINAPI BuildCommDCBAndTimeoutsW(LPCWSTR a0, LPDCB a1, LPCOMMTIMEOUTS a0)
