#include <vx_kernel32.h>

//WINBASEAPI BOOL WINAPI CallNamedPipeA(
//	LPCSTR a0, PVOID a1, DWORD a2, PVOID a3, DWORD a4, PDWORD a5, DWORD a6)
//{
//	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
//}

//WINBASEAPI BOOL WINAPI CallNamedPipeW(
//	LPCWSTR a0, PVOID a1, DWORD a2, PVOID a3, DWORD a4, PDWORD a5, DWORD a6)
//{
//	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
//}

//WINBASEAPI BOOL WINAPI CancelDeviceWakeupRequest(
//	HANDLE a0)
//{
//	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
//}

//WINBASEAPI BOOL WINAPI CancelIo(
//	HANDLE a0)
//{
//	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
//}

//WINBASEAPI BOOL WINAPI CancelWaitableTimer(
//	HANDLE a0)
//{
//	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
//}

//WINBASEAPI BOOL WINAPI ChangeTimerQueueTimer(
//	HANDLE a0, HANDLE a1, ULONG a2, ULONG a3)
//{
//	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
//}

//WINBASEAPI BOOL WINAPI CheckNameLegalDOS8Dot3A(
//	LPCSTR a0, LPSTR a1, DWORD a2, PBOOL a3, PBOOL a4)
//{
//	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
//}

//WINBASEAPI BOOL WINAPI CheckNameLegalDOS8Dot3W(
//	LPCWSTR a0, LPSTR a1, DWORD a2, PBOOL a3, PBOOL a4)
//{
//	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
//}

//WINBASEAPI BOOL WINAPI CheckRemoteDebuggerPresent(
//	HANDLE a0, PBOOL a1)
//{
//	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
//}

//WINBASEAPI BOOL WINAPI CheckTokenMembership(
//	HANDLE a0, PSID a1, PBOOL a2)
//{
//	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
//}

/* 
WINBASEAPI BOOL WINAPI ClearCommBreak(
	HANDLE a0)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI ClearCommError(
	HANDLE a0, PDWORD a1, LPCOMSTAT a2)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI ClearEventLogA(
	HANDLE a0, LPCSTR a1)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI ClearEventLogW(
	HANDLE a0, LPCWSTR a1)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}
*/

/*
WINBASEAPI BOOL WINAPI CloseEventLog(
	HANDLE a0)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI CloseHandle(
	HANDLE a0)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI CommConfigDialogA(
	LPCSTR a0, HWND a1, LPCOMMCONFIG a2)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI CommConfigDialogW(
	LPCWSTR a0, HWND a1, LPCOMMCONFIG a2)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}
*/

/*
WINBASEAPI BOOL WINAPI ConnectNamedPipe(
	HANDLE a0, LPOVERLAPPED a1)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI ContinueDebugEvent(
	DWORD a0, DWORD a1, DWORD a2)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}
*/

/*
WINBASEAPI BOOL WINAPI ConvertFiberToThread(void)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI PVOID WINAPI ConvertThreadToFiber(
	PVOID a0)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}
*/

WINBASEAPI BOOL WINAPI CopySid(
	DWORD a0, PSID a1, PSID a2)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

/*
WINBASEAPI HANDLE WINAPI CreateActCtxA(
	PCACTCTXA a0)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI HANDLE WINAPI CreateActCtxW(
	PCACTCTXW a0)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}
*/

/*
WINBASEAPI BOOL WINAPI CreateDirectoryA(
	LPCSTR a0, LPSECURITY_ATTRIBUTES a1)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI CreateDirectoryW(
	LPCWSTR a0, LPSECURITY_ATTRIBUTES a1)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI CreateDirectoryExA(
	LPCSTR a0, LPCSTR a1, LPSECURITY_ATTRIBUTES a2)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI CreateDirectoryExW(
	LPCWSTR a0, LPCWSTR a1, LPSECURITY_ATTRIBUTES a2)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI HANDLE WINAPI CreateEventA(
	LPSECURITY_ATTRIBUTES a0, BOOL a1, BOOL a2, LPCSTR a3)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI HANDLE WINAPI CreateEventW(
	LPSECURITY_ATTRIBUTES a0, BOOL a1, BOOL a2, LPCWSTR a3)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}
*/

/*
WINBASEAPI LPVOID WINAPI CreateFiber(
	SIZE_T a0, LPFIBER_START_ROUTINE a1, LPVOID a2)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI LPVOID WINAPI CreateFiberEx(
	SIZE_T a0, SIZE_T a1, DWORD a2, LPFIBER_START_ROUTINE a3, LPVOID a4)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}
*/

WINBASEAPI HANDLE WINAPI CreateIoCompletionPort(
	HANDLE a0, HANDLE a1, ULONG_PTR a2, DWORD a3)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

/*
WINBASEAPI HANDLE WINAPI CreateJobObjectA(
	LPSECURITY_ATTRIBUTES a0, LPCSTR a1)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI HANDLE WINAPI CreateJobObjectW(
	LPSECURITY_ATTRIBUTES a0, LPCWSTR a1)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}
*/

WINBASEAPI HANDLE WINAPI CreateMailslotA(
	LPCSTR a0, DWORD a1, DWORD a2, LPSECURITY_ATTRIBUTES a3)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI HANDLE WINAPI CreateMailslotW(
	LPCWSTR a0, DWORD a1, DWORD a2, LPSECURITY_ATTRIBUTES a3)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

//WINBASEAPI HANDLE WINAPI CreateMemoryResourceNotification(
//	MEMORY_RESOURCE_NOTIFICATION_TYPE a0)
//{
//	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
//}

WINBASEAPI HANDLE WINAPI CreateMutexA(
	LPSECURITY_ATTRIBUTES a0, BOOL a1, LPCSTR a2)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI HANDLE WINAPI CreateMutexW(
	LPSECURITY_ATTRIBUTES a0, BOOL a1, LPCWSTR a2)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI HANDLE WINAPI CreateNamedPipeA(
	LPCSTR a0, DWORD a1, DWORD a2, DWORD a3, DWORD a4, DWORD a5,
	DWORD a6, LPSECURITY_ATTRIBUTES a7)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI HANDLE WINAPI CreateNamedPipeW(
	LPCWSTR a0, DWORD a1, DWORD a2, DWORD a3, DWORD a4, DWORD a5,
	DWORD a6, LPSECURITY_ATTRIBUTES a7)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI CreatePipe(
	PHANDLE a0, PHANDLE a1, LPSECURITY_ATTRIBUTES a2, DWORD a3)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI CreatePrivateObjectSecurity(
	PSECURITY_DESCRIPTOR a0, PSECURITY_DESCRIPTOR a1,
	PSECURITY_DESCRIPTOR *a2, BOOL a3, HANDLE a4, PGENERIC_MAPPING a5)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI CreateProcessA(
	LPCSTR a0, LPSTR a1, LPSECURITY_ATTRIBUTES a2,
	LPSECURITY_ATTRIBUTES a3, BOOL a4, DWORD a5, PVOID a6,
	LPCSTR a7, LPSTARTUPINFOA a8, LPPROCESS_INFORMATION a9)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI CreateProcessW(
	LPCWSTR a0, LPWSTR a1, LPSECURITY_ATTRIBUTES a2,
	LPSECURITY_ATTRIBUTES a3, BOOL a4, DWORD a5, PVOID a6,
	LPCWSTR a7, LPSTARTUPINFOW a8, LPPROCESS_INFORMATION a9)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI CreateProcessAsUserA(
	HANDLE a0, LPCSTR a1, LPSTR a2, LPSECURITY_ATTRIBUTES a3, 
	LPSECURITY_ATTRIBUTES a4, BOOL a5, DWORD a6, PVOID a7,
	LPCSTR a8, LPSTARTUPINFOA a9, LPPROCESS_INFORMATION a10)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI CreateProcessAsUserW(
	HANDLE a0, LPCWSTR a1, LPWSTR a2, LPSECURITY_ATTRIBUTES a3, 
	LPSECURITY_ATTRIBUTES a4, BOOL a5, DWORD a6, PVOID a7, LPCWSTR a8, 
	LPSTARTUPINFOW a9, LPPROCESS_INFORMATION a10)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI CreateProcessWithLogonW (
	LPCWSTR a0, LPCWSTR a1, LPCWSTR a2, DWORD a3, 
	LPCWSTR a4, LPWSTR a5, DWORD a6, LPVOID a7, 
	LPCWSTR a8, LPSTARTUPINFOW a9, 
	LPPROCESS_INFORMATION a10)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI HANDLE WINAPI CreateRemoteThread(
	HANDLE a0, LPSECURITY_ATTRIBUTES a1, DWORD a2,
	LPTHREAD_START_ROUTINE a3, LPVOID a4, DWORD a5, LPDWORD a6)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI CreateRestrictedToken(
	HANDLE a0, DWORD a1, DWORD a2, PSID_AND_ATTRIBUTES a3, DWORD a4, 
	PLUID_AND_ATTRIBUTES a5, DWORD a6, PSID_AND_ATTRIBUTES a7, PHANDLE a8)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI HANDLE WINAPI CreateSemaphoreA(
	LPSECURITY_ATTRIBUTES a0, LONG a1, LONG a2, LPCSTR a3)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI HANDLE WINAPI CreateSemaphoreW(
	LPSECURITY_ATTRIBUTES a0, LONG a1, LONG a2, LPCWSTR a3)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI CreateSymbolicLinkA(
	LPCSTR a0, LPCSTR a1, DWORD a2)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI CreateSymbolicLinkW(
	LPCWSTR a0, LPCWSTR a1, DWORD a2)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI DWORD WINAPI CreateTapePartition(
	HANDLE a0, DWORD a1, DWORD a2, DWORD a3)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI HANDLE WINAPI CreateTimerQueue(void)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

//WINBASEAPI BOOL WINAPI CreateTimerQueueTimer(
//	PHANDLE a0, HANDLE a1, WAITORTIMERCALLBACK a2, PVOID a3,
//	DWORD a4, DWORD a5, ULONG a6)
//{
//	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
//}

WINBASEAPI HANDLE WINAPI CreateThread(
	LPSECURITY_ATTRIBUTES a0, DWORD a1, LPTHREAD_START_ROUTINE a2,
	PVOID a3, DWORD a4, PDWORD a5)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI HANDLE WINAPI CreateWaitableTimerA(
	LPSECURITY_ATTRIBUTES a0, BOOL a1, LPCSTR a2)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI HANDLE WINAPI CreateWaitableTimerW(
	LPSECURITY_ATTRIBUTES a0, BOOL a1, LPCWSTR a2)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

