#include <vx_kernel32.h>

/*
WINBASEAPI void WINAPI LeaveCriticalSection(LPCRITICAL_SECTION a0)
WINBASEAPI HINSTANCE WINAPI LoadLibraryA(LPCSTR a0)
WINBASEAPI HINSTANCE WINAPI LoadLibraryExA(LPCSTR a0, HANDLE a1, DWORD a2)
WINBASEAPI HINSTANCE WINAPI LoadLibraryExW(LPCWSTR a0, HANDLE a1, DWORD a2)
WINBASEAPI HINSTANCE WINAPI LoadLibraryW(LPCWSTR a0)
WINBASEAPI DWORD WINAPI LoadModule(LPCSTR a0, PVOID a1)
WINBASEAPI HLOCAL WINAPI LocalAlloc(UINT a0, SIZE_T a0)
WINBASEAPI SIZE_T WINAPI LocalCompact(UINT a0)
WINBASEAPI HLOCAL LocalDiscard(HLOCAL a0)
WINBASEAPI UINT WINAPI LocalFlags(HLOCAL a0)
WINBASEAPI HLOCAL WINAPI LocalFree(HLOCAL a0)
WINBASEAPI HLOCAL WINAPI LocalHandle(LPCVOID a0)
WINBASEAPI PVOID WINAPI LocalLock(HLOCAL a0)
WINBASEAPI HLOCAL WINAPI LocalReAlloc(HLOCAL a0, SIZE_T a0, UINT a0)
WINBASEAPI SIZE_T WINAPI LocalShrink(HLOCAL a0, UINT a0) 
WINBASEAPI UINT WINAPI LocalSize(HLOCAL a0)
WINBASEAPI BOOL WINAPI LocalUnlock(HLOCAL a0)
*/

WINBASEAPI HGLOBAL WINAPI LoadResource(
	HINSTANCE a0, HRSRC a1)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI PVOID WINAPI LockResource(
	HGLOBAL a0)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI LogonUserA(
	LPSTR a0, LPSTR a1, LPSTR a2, DWORD a3, DWORD a4, PHANDLE a5)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI LogonUserW(
	LPWSTR a0, LPWSTR a1, LPWSTR a2, DWORD a3, DWORD a4, PHANDLE a5)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI LookupAccountNameA(
	LPCSTR a0, LPCSTR a1, PSID a2, PDWORD a3, LPSTR a4,
	PDWORD a5, PSID_NAME_USE a6)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI LookupAccountNameW(
	LPCWSTR a0, LPCWSTR a1, PSID a2, PDWORD a3, LPWSTR a4,
	PDWORD a5, PSID_NAME_USE a6)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI LookupAccountSidA(
	LPCSTR a0, PSID a1, LPSTR a2, PDWORD a3, LPSTR a4,
	PDWORD a5, PSID_NAME_USE a6)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI LookupAccountSidW(
	LPCWSTR a0, PSID a1, LPWSTR a2, PDWORD a3, LPWSTR a4,
	PDWORD a5, PSID_NAME_USE a6)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI LookupPrivilegeDisplayNameA(
	LPCSTR a0, LPCSTR a1, LPSTR a2, PDWORD a3, PDWORD a4)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI LookupPrivilegeDisplayNameW(
	LPCWSTR a0, LPCWSTR a1, LPWSTR a2, PDWORD a3, PDWORD a4)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI LookupPrivilegeNameA(
	LPCSTR a0, PLUID a1, LPSTR a2, PDWORD a3)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI LookupPrivilegeNameW(
	LPCWSTR a0, PLUID a1, LPWSTR a2, PDWORD a3)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI LookupPrivilegeValueA(
	LPCSTR a0, LPCSTR a1, PLUID a2)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}

WINBASEAPI BOOL WINAPI LookupPrivilegeValueW(
	LPCWSTR a0, LPCWSTR a1, PLUID a2)
{
	VxStubFault(__FILE__, __LINE__, __FUNCTION__);
}


/*
WINBASEAPI LPSTR WINAPI lstrcatA(LPSTR a0, LPCSTR a1)
WINBASEAPI LPWSTR WINAPI lstrcatW(LPWSTR a0, LPCWSTR a1)
WINBASEAPI int WINAPI lstrcmpA(LPCSTR a0, LPCSTR a1)
WINBASEAPI int WINAPI lstrcmpiA(LPCSTR a0, LPCSTR a1)
WINBASEAPI int WINAPI lstrcmpiW( LPCWSTR a0, LPCWSTR a1)
WINBASEAPI int WINAPI lstrcmpW(LPCWSTR a0, LPCWSTR a1)
WINBASEAPI LPSTR WINAPI lstrcpyA(LPSTR a0, LPCSTR a1)
WINBASEAPI LPSTR WINAPI lstrcpynA(LPSTR a0, LPCSTR a1, int a0)
WINBASEAPI LPWSTR WINAPI lstrcpynW(LPWSTR a0, LPCWSTR a1, int a0)
WINBASEAPI LPWSTR WINAPI lstrcpyW(LPWSTR a0, LPCWSTR a1)
WINBASEAPI int WINAPI lstrlenA(LPCSTR a0)
WINBASEAPI int WINAPI lstrlenW(LPCWSTR a0)
*/
