WINBASEAPI BOOL WINAPI AccessCheck(
	PSECURITY_DESCRIPTOR a0, HANDLE a1, DWORD a2, PGENERIC_MAPPING a3, 
	PPRIVILEGE_SET a4, PDWORD a5, PDWORD a6, PBOOL a7)
WINBASEAPI BOOL WINAPI AccessCheckAndAuditAlarmA(
	LPCSTR a0, LPVOID a1, LPSTR a2, LPSTR a3, PSECURITY_DESCRIPTOR a4,
	DWORD a5, PGENERIC_MAPPING a6, BOOL a7, PDWORD a8, PBOOL a9, PBOOL a10)
WINBASEAPI BOOL WINAPI AccessCheckAndAuditAlarmW(
	LPCWSTR a0, LPVOID a1, LPWSTR a2, LPWSTR a3, PSECURITY_DESCRIPTOR a4, 
	DWORD a5, PGENERIC_MAPPING a6, BOOL a7, PDWORD a8, PBOOL a9, PBOOL a10)
WINBASEAPI BOOL WINAPI ActivateActCtx(HANDLE a0, ULONG_PTR *a1)
WINBASEAPI BOOL WINAPI AddAccessAllowedAce(
	PACL a0, DWORD a1, DWORD a2, PSID a3)
WINBASEAPI BOOL WINAPI AddAccessDeniedAce(
	PACL a0, DWORD a1, DWORD a2, PSID a3)
WINBASEAPI BOOL WINAPI AddAccessAllowedAceEx(
	PACL a0, DWORD a1, DWORD a2, DWORD a3, PSID a4)
WINBASEAPI BOOL WINAPI AddAccessDeniedAceEx(
	PACL a0, DWORD a1, DWORD a2, DWORD a3, PSID a4)
WINBASEAPI BOOL WINAPI AddAce(
	PACL a0, DWORD a1, DWORD a2, PVOID a3, DWORD a4)
WINBASEAPI ATOM WINAPI AddAtomA(LPCSTR a0)
WINBASEAPI ATOM WINAPI AddAtomW(LPCWSTR a0)
WINBASEAPI BOOL WINAPI AddAuditAccessAce(
	PACL a0, DWORD a1, DWORD a2, PSID a3, BOOL a4, BOOL a5)
WINBASEAPI void WINAPI AddRefActCtx(HANDLE a0)
WINBASEAPI PVOID WINAPI AddVectoredExceptionHandler(
	ULONG a0, PVECTORED_EXCEPTION_HANDLER a1)
WINBASEAPI BOOL WINAPI AdjustTokenGroups(
	HANDLE a0, BOOL a1, PTOKEN_GROUPS a2, DWORD a3,
	PTOKEN_GROUPS a4, PDWORD a5)
WINBASEAPI BOOL WINAPI AdjustTokenPrivileges(
	HANDLE a0, BOOL a1, PTOKEN_PRIVILEGES a2, DWORD a3,
	PTOKEN_PRIVILEGES a4, PDWORD a5)
WINBASEAPI BOOL WINAPI AllocateAndInitializeSid(
	PSID_IDENTIFIER_AUTHORITY a0, BYTE a1, DWORD a2, DWORD a3,
	DWORD a4, DWORD a5, DWORD a6, DWORD a7, DWORD a8, DWORD a9, PSID *a10)
WINBASEAPI BOOL WINAPI AllocateLocallyUniqueId(PLUID a0)
WINBASEAPI BOOL WINAPI AreAllAccessesGranted(DWORD a0, DWORD a1)
WINBASEAPI BOOL WINAPI AreAnyAccessesGranted(DWORD a0, DWORD a1)
WINBASEAPI BOOL WINAPI AssignProcessToJobObject(HANDLE a0, HANDLE a1)
