/*
 * SH-ISA
 */

/* 00-1F: GPR R00-R31, 32/64 */
#define BGBCC_SH_REG_R0			0x00
#define BGBCC_SH_REG_R1			0x01
#define BGBCC_SH_REG_R2			0x02
#define BGBCC_SH_REG_R3			0x03
#define BGBCC_SH_REG_R4			0x04
#define BGBCC_SH_REG_R5			0x05
#define BGBCC_SH_REG_R6			0x06
#define BGBCC_SH_REG_R7			0x07
#define BGBCC_SH_REG_R8			0x08
#define BGBCC_SH_REG_R9			0x09
#define BGBCC_SH_REG_R10		0x0A
#define BGBCC_SH_REG_R11		0x0B
#define BGBCC_SH_REG_R12		0x0C
#define BGBCC_SH_REG_R13		0x0D
#define BGBCC_SH_REG_R14		0x0E
#define BGBCC_SH_REG_R15		0x0F
#define BGBCC_SH_REG_R16		0x10
#define BGBCC_SH_REG_R17		0x11
#define BGBCC_SH_REG_R18		0x12
#define BGBCC_SH_REG_R19		0x13
#define BGBCC_SH_REG_R20		0x14
#define BGBCC_SH_REG_R21		0x15
#define BGBCC_SH_REG_R22		0x16
#define BGBCC_SH_REG_R23		0x17
#define BGBCC_SH_REG_R24		0x18
#define BGBCC_SH_REG_R25		0x19
#define BGBCC_SH_REG_R26		0x1A
#define BGBCC_SH_REG_R27		0x1B
#define BGBCC_SH_REG_R28		0x1C
#define BGBCC_SH_REG_R29		0x1D
#define BGBCC_SH_REG_R30		0x1E
#define BGBCC_SH_REG_R31		0x1F

#define BGBCC_SH_REG_BP			0x0E
#define BGBCC_SH_REG_SP			0x0F


/* 20-3F: GPR RQ00-RQ31, 64 */
#define BGBCC_SH_REG_RQ0		0x20
#define BGBCC_SH_REG_RQ1		0x21
#define BGBCC_SH_REG_RQ2		0x22
#define BGBCC_SH_REG_RQ3		0x23
#define BGBCC_SH_REG_RQ4		0x24
#define BGBCC_SH_REG_RQ5		0x25
#define BGBCC_SH_REG_RQ6		0x26
#define BGBCC_SH_REG_RQ7		0x27
#define BGBCC_SH_REG_RQ8		0x28
#define BGBCC_SH_REG_RQ9		0x29
#define BGBCC_SH_REG_RQ10		0x2A
#define BGBCC_SH_REG_RQ11		0x2B
#define BGBCC_SH_REG_RQ12		0x2C
#define BGBCC_SH_REG_RQ13		0x2D
#define BGBCC_SH_REG_RQ14		0x2E
#define BGBCC_SH_REG_RQ15		0x2F
#define BGBCC_SH_REG_RQ16		0x30
#define BGBCC_SH_REG_RQ17		0x31
#define BGBCC_SH_REG_RQ18		0x32
#define BGBCC_SH_REG_RQ19		0x33
#define BGBCC_SH_REG_RQ20		0x34
#define BGBCC_SH_REG_RQ21		0x35
#define BGBCC_SH_REG_RQ22		0x36
#define BGBCC_SH_REG_RQ23		0x37
#define BGBCC_SH_REG_RQ24		0x38
#define BGBCC_SH_REG_RQ25		0x39
#define BGBCC_SH_REG_RQ26		0x3A
#define BGBCC_SH_REG_RQ27		0x3B
#define BGBCC_SH_REG_RQ28		0x3C
#define BGBCC_SH_REG_RQ29		0x3D
#define BGBCC_SH_REG_RQ30		0x3E
#define BGBCC_SH_REG_RQ31		0x3F

/* 40-5F: GPR RD00-RD31, 32 */
#define BGBCC_SH_REG_RD0		0x40
#define BGBCC_SH_REG_RD1		0x41
#define BGBCC_SH_REG_RD2		0x42
#define BGBCC_SH_REG_RD3		0x43
#define BGBCC_SH_REG_RD4		0x44
#define BGBCC_SH_REG_RD5		0x45
#define BGBCC_SH_REG_RD6		0x46
#define BGBCC_SH_REG_RD7		0x47
#define BGBCC_SH_REG_RD8		0x48
#define BGBCC_SH_REG_RD9		0x49
#define BGBCC_SH_REG_RD10		0x4A
#define BGBCC_SH_REG_RD11		0x4B
#define BGBCC_SH_REG_RD12		0x4C
#define BGBCC_SH_REG_RD13		0x4D
#define BGBCC_SH_REG_RD14		0x4E
#define BGBCC_SH_REG_RD15		0x4F
#define BGBCC_SH_REG_RD16		0x50
#define BGBCC_SH_REG_RD17		0x51
#define BGBCC_SH_REG_RD18		0x52
#define BGBCC_SH_REG_RD19		0x53
#define BGBCC_SH_REG_RD20		0x54
#define BGBCC_SH_REG_RD21		0x55
#define BGBCC_SH_REG_RD22		0x56
#define BGBCC_SH_REG_RD23		0x57
#define BGBCC_SH_REG_RD24		0x58
#define BGBCC_SH_REG_RD25		0x59
#define BGBCC_SH_REG_RD26		0x5A
#define BGBCC_SH_REG_RD27		0x5B
#define BGBCC_SH_REG_RD28		0x5C
#define BGBCC_SH_REG_RD29		0x5D
#define BGBCC_SH_REG_RD30		0x5E
#define BGBCC_SH_REG_RD31		0x5F

/* 60-6F: Control Regs */
#define BGBCC_SH_REG_CR0		0x60

#define BGBCC_SH_REG_SR			0x60
#define BGBCC_SH_REG_GBR		0x61
#define BGBCC_SH_REG_VBR		0x62
#define BGBCC_SH_REG_SSR		0x63
#define BGBCC_SH_REG_SPC		0x64

#define BGBCC_SH_REG_TBR		0x65	//placeholder

#define BGBCC_SH_REG_R0B		0x68
#define BGBCC_SH_REG_R1B		0x69
#define BGBCC_SH_REG_R2B		0x6A
#define BGBCC_SH_REG_R3B		0x6B
#define BGBCC_SH_REG_R4B		0x6C
#define BGBCC_SH_REG_R5B		0x6D
#define BGBCC_SH_REG_R6B		0x6E
#define BGBCC_SH_REG_R7B		0x6F

/* 70-7F: Status Regs */
#define BGBCC_SH_REG_SR0		0x70

#define BGBCC_SH_REG_MACH		0x70	//S
#define BGBCC_SH_REG_MACL		0x71	//S
#define BGBCC_SH_REG_PR			0x72	//S
#define BGBCC_SH_REG_SGR		0x73	//C

#define BGBCC_SH_REG_FPUL		0x75
#define BGBCC_SH_REG_FPSCR		0x76
#define BGBCC_SH_REG_PC			0x77


#define BGBCC_SH_REG_TTB		0x78
#define BGBCC_SH_REG_TEA		0x79
#define BGBCC_SH_REG_MMCR		0x7A
#define BGBCC_SH_REG_EXSR		0x7B
#define BGBCC_SH_REG_STTB		0x7C
#define BGBCC_SH_REG_KRR		0x7D

#define BGBCC_SH_REG_DBR		0x7F

/* 80-9F: FPR DR0-DR15, 64 */
#define BGBCC_SH_REG_DR0		0x80
#define BGBCC_SH_REG_DR1		0x81
#define BGBCC_SH_REG_DR2		0x82
#define BGBCC_SH_REG_DR3		0x83
#define BGBCC_SH_REG_DR4		0x84
#define BGBCC_SH_REG_DR5		0x85
#define BGBCC_SH_REG_DR6		0x86
#define BGBCC_SH_REG_DR7		0x87
#define BGBCC_SH_REG_DR8		0x88
#define BGBCC_SH_REG_DR9		0x89
#define BGBCC_SH_REG_DR10		0x8A
#define BGBCC_SH_REG_DR11		0x8B
#define BGBCC_SH_REG_DR12		0x8C
#define BGBCC_SH_REG_DR13		0x8D
#define BGBCC_SH_REG_DR14		0x8E
#define BGBCC_SH_REG_DR15		0x8F
#define BGBCC_SH_REG_DR16		0x90
#define BGBCC_SH_REG_DR17		0x91
#define BGBCC_SH_REG_DR18		0x92
#define BGBCC_SH_REG_DR19		0x93
#define BGBCC_SH_REG_DR20		0x94
#define BGBCC_SH_REG_DR21		0x95
#define BGBCC_SH_REG_DR22		0x96
#define BGBCC_SH_REG_DR23		0x97
#define BGBCC_SH_REG_DR24		0x98
#define BGBCC_SH_REG_DR25		0x99
#define BGBCC_SH_REG_DR26		0x9A
#define BGBCC_SH_REG_DR27		0x9B
#define BGBCC_SH_REG_DR28		0x9C
#define BGBCC_SH_REG_DR29		0x9D
#define BGBCC_SH_REG_DR30		0x9E
#define BGBCC_SH_REG_DR31		0x9F

/* A0-AF: FPR FR0-FR15, 32 */
#define BGBCC_SH_REG_FR0		0xA0
#define BGBCC_SH_REG_FR1		0xA1
#define BGBCC_SH_REG_FR2		0xA2
#define BGBCC_SH_REG_FR3		0xA3
#define BGBCC_SH_REG_FR4		0xA4
#define BGBCC_SH_REG_FR5		0xA5
#define BGBCC_SH_REG_FR6		0xA6
#define BGBCC_SH_REG_FR7		0xA7
#define BGBCC_SH_REG_FR8		0xA8
#define BGBCC_SH_REG_FR9		0xA9
#define BGBCC_SH_REG_FR10		0xAA
#define BGBCC_SH_REG_FR11		0xAB
#define BGBCC_SH_REG_FR12		0xAC
#define BGBCC_SH_REG_FR13		0xAD
#define BGBCC_SH_REG_FR14		0xAE
#define BGBCC_SH_REG_FR15		0xAF

#define BGBCC_SH_REG_FR16		0xB0
#define BGBCC_SH_REG_FR17		0xB1
#define BGBCC_SH_REG_FR18		0xB2
#define BGBCC_SH_REG_FR19		0xB3
#define BGBCC_SH_REG_FR20		0xB4
#define BGBCC_SH_REG_FR21		0xB5
#define BGBCC_SH_REG_FR22		0xB6
#define BGBCC_SH_REG_FR23		0xB7
#define BGBCC_SH_REG_FR24		0xB8
#define BGBCC_SH_REG_FR25		0xB9
#define BGBCC_SH_REG_FR26		0xBA
#define BGBCC_SH_REG_FR27		0xBB
#define BGBCC_SH_REG_FR28		0xBC
#define BGBCC_SH_REG_FR29		0xBD
#define BGBCC_SH_REG_FR30		0xBE
#define BGBCC_SH_REG_FR31		0xBF

/* B0-BF: FPR XF0-XF15, 32 */
#define BGBCC_SH_REG_XF0		0xB0
#define BGBCC_SH_REG_XF1		0xB1
#define BGBCC_SH_REG_XF2		0xB2
#define BGBCC_SH_REG_XF3		0xB3
#define BGBCC_SH_REG_XF4		0xB4
#define BGBCC_SH_REG_XF12		0xBC
#define BGBCC_SH_REG_XF13		0xBD
#define BGBCC_SH_REG_XF14		0xBE
#define BGBCC_SH_REG_XF15		0xBF

/* C0-CF: FPR YF0-YF15, 32 */
#define BGBCC_SH_REG_YF0		0xC0
#define BGBCC_SH_REG_YF1		0xC1
#define BGBCC_SH_REG_YF2		0xC2
#define BGBCC_SH_REG_YF3		0xC3
#define BGBCC_SH_REG_YF4		0xC4
#define BGBCC_SH_REG_YF12		0xCC
#define BGBCC_SH_REG_YF13		0xCD
#define BGBCC_SH_REG_YF14		0xCE
#define BGBCC_SH_REG_YF15		0xCF

/* D0-DF: FPR ZF0-ZF15, 32 */
#define BGBCC_SH_REG_ZF0		0xD0
#define BGBCC_SH_REG_ZF1		0xD1
#define BGBCC_SH_REG_ZF2		0xD2
#define BGBCC_SH_REG_ZF3		0xD3
#define BGBCC_SH_REG_ZF4		0xD4
#define BGBCC_SH_REG_ZF12		0xDC
#define BGBCC_SH_REG_ZF13		0xDD
#define BGBCC_SH_REG_ZF14		0xDE
#define BGBCC_SH_REG_ZF15		0xDF

#if 0
/* E0-EF: GPR R0-R15 High Bits, 32 */
#define BGBCC_SH_REG_RH0		0xE0
#define BGBCC_SH_REG_RH1		0xE1
#define BGBCC_SH_REG_RH2		0xE2
#define BGBCC_SH_REG_RH3		0xE3
#define BGBCC_SH_REG_RH4		0xE4
#define BGBCC_SH_REG_RH5		0xE5
#define BGBCC_SH_REG_RH6		0xE6
#define BGBCC_SH_REG_RH7		0xE7
#define BGBCC_SH_REG_RH8		0xE8
#define BGBCC_SH_REG_RH9		0xE9
#define BGBCC_SH_REG_RH10		0xEA
#define BGBCC_SH_REG_RH11		0xEB
#define BGBCC_SH_REG_RH12		0xEC
#define BGBCC_SH_REG_RH13		0xED
#define BGBCC_SH_REG_RH14		0xEE
#define BGBCC_SH_REG_RH15		0xEF

/* F0-FF: GPR R0-R15 Pair, 32+32 */
#define BGBCC_SH_REG_LR0		0xF0
#define BGBCC_SH_REG_LR1		0xF1
#define BGBCC_SH_REG_LR2		0xF2
#define BGBCC_SH_REG_LR3		0xF3
#define BGBCC_SH_REG_LR4		0xF4
#define BGBCC_SH_REG_LR5		0xF5
#define BGBCC_SH_REG_LR6		0xF6
#define BGBCC_SH_REG_LR7		0xF7
#define BGBCC_SH_REG_LR8		0xF8
#define BGBCC_SH_REG_LR9		0xF9
#define BGBCC_SH_REG_LR10		0xFA
#define BGBCC_SH_REG_LR11		0xFB
#define BGBCC_SH_REG_LR12		0xFC
#define BGBCC_SH_REG_LR13		0xFD
#define BGBCC_SH_REG_LR14		0xFE
#define BGBCC_SH_REG_LR15		0xFF		//Invalid

#endif

#if 1
/* E0-EF: GPR R0-R15 Pair */
#define BGBCC_SH_REG_LR0		0xE0
#define BGBCC_SH_REG_LR1		0xE1
#define BGBCC_SH_REG_LR2		0xE2
#define BGBCC_SH_REG_LR3		0xE3
#define BGBCC_SH_REG_LR4		0xE4
#define BGBCC_SH_REG_LR5		0xE5
#define BGBCC_SH_REG_LR6		0xE6
#define BGBCC_SH_REG_LR7		0xE7
#define BGBCC_SH_REG_LR8		0xE8
#define BGBCC_SH_REG_LR9		0xE9
#define BGBCC_SH_REG_LR10		0xEA
#define BGBCC_SH_REG_LR11		0xEB
#define BGBCC_SH_REG_LR12		0xEC
#define BGBCC_SH_REG_LR13		0xED
#define BGBCC_SH_REG_LR14		0xEE
#define BGBCC_SH_REG_LR15		0xEF		//Invalid

/* F0-FF: GPR R16-R31 Pair */
#define BGBCC_SH_REG_LR16		0xF0
#define BGBCC_SH_REG_LR17		0xF1
#define BGBCC_SH_REG_LR18		0xF2
#define BGBCC_SH_REG_LR19		0xF3
#define BGBCC_SH_REG_LR20		0xF4
#define BGBCC_SH_REG_LR21		0xF5
#define BGBCC_SH_REG_LR22		0xF6
#define BGBCC_SH_REG_LR23		0xF7
#define BGBCC_SH_REG_LR24		0xF8
#define BGBCC_SH_REG_LR25		0xF9
#define BGBCC_SH_REG_LR26		0xFA
#define BGBCC_SH_REG_LR27		0xFB
#define BGBCC_SH_REG_LR28		0xFC
#define BGBCC_SH_REG_LR29		0xFD
#define BGBCC_SH_REG_LR30		0xFE
#define BGBCC_SH_REG_LR31		0xFF		//Invalid

#endif

#define BGBCC_SH_REG_RTMASK		0xF0
#define BGBCC_SH_REG_RTMASK3	0xF8
#define BGBCC_SH_REG_RTMASK5	0xE0

#define BGBCC_SH_REG_ZZR		0xFF		//Null Register (Placeholder Reg)


#define BGBCC_SH_REG_DLR	BGBCC_SH_REG_MACL	//Alias
#define BGBCC_SH_REG_DHR	BGBCC_SH_REG_MACH	//Alias

#define BGBCC_BJX2_FLIPSTNM


#define BGBCC_SH_LBL_ARCHREG(rn)	((CCXL_LBL_ARCHBASE)+(rn))

#define BGBCC_SH_ARCHREG_MACH		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_MACH)
#define BGBCC_SH_ARCHREG_MACL		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_MACL)
#define BGBCC_SH_ARCHREG_PR			BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_PR)
#define BGBCC_SH_ARCHREG_SGR		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_SGR)

#define BGBCC_SH_ARCHREG_FPUL		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_FPUL)
#define BGBCC_SH_ARCHREG_FPSCR		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_FPSCR)
#define BGBCC_SH_ARCHREG_PC			BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_PC)

#define BGBCC_SH_ARCHREG_TTB		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_TTB)
#define BGBCC_SH_ARCHREG_TEA		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_TEA)
#define BGBCC_SH_ARCHREG_MMCR		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_MMCR)
#define BGBCC_SH_ARCHREG_EXSR		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_EXSR)

#define BGBCC_SH_ARCHREG_DBR		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_DBR)


#define BGBCC_SH_LBL_ARCHSTRT		(CCXL_LBL_ARCHBASE+  0)
#define BGBCC_SH_LBL_ARCHEND		(CCXL_LBL_ARCHBASE+256)


#define BGBCC_SH_NMID_UNK			0x0000	//Unknown
#define BGBCC_SH_NMID_MOV			0x0001	//MOV
#define BGBCC_SH_NMID_MOVB			0x0002	//MOV.B
#define BGBCC_SH_NMID_MOVW			0x0003	//MOV.W
#define BGBCC_SH_NMID_MOVL			0x0004	//MOV.L
#define BGBCC_SH_NMID_ADD			0x0005	//ADD
#define BGBCC_SH_NMID_ADDC			0x0006	//ADDC
#define BGBCC_SH_NMID_ADDV			0x0007	//ADDV
#define BGBCC_SH_NMID_SUB			0x0008	//SUB
#define BGBCC_SH_NMID_SUBC			0x0009	//SUBC
#define BGBCC_SH_NMID_SUBV			0x000A	//SUBV
#define BGBCC_SH_NMID_CMPHS			0x000B	//CMPHS
#define BGBCC_SH_NMID_CMPHI			0x000C	//CMPHI
#define BGBCC_SH_NMID_CMPEQ			0x000D	//CMPEQ
#define BGBCC_SH_NMID_CMPGE			0x000E	//CMPGE
#define BGBCC_SH_NMID_CMPGT			0x000F	//CMPGT
#define BGBCC_SH_NMID_JMP			0x0010	//JMP
#define BGBCC_SH_NMID_JSR			0x0011	//JSR
#define BGBCC_SH_NMID_BRA			0x0012	//BRA
#define BGBCC_SH_NMID_BSR			0x0013	//BSR
#define BGBCC_SH_NMID_BT			0x0014	//BT
#define BGBCC_SH_NMID_BF			0x0015	//BF
#define BGBCC_SH_NMID_BTS			0x0016	//BTS
#define BGBCC_SH_NMID_BFS			0x0017	//BFS
#define BGBCC_SH_NMID_DIV1			0x0018	//DIV1
#define BGBCC_SH_NMID_DMULU			0x0019	//DMULU
#define BGBCC_SH_NMID_DMULS			0x001A	//DMULS
#define BGBCC_SH_NMID_TST			0x001B	//TST
#define BGBCC_SH_NMID_AND			0x001C	//AND
#define BGBCC_SH_NMID_XOR			0x001D	//XOR
#define BGBCC_SH_NMID_OR			0x001E	//OR
#define BGBCC_SH_NMID_INVALID		0x001F	//Invalid
#define BGBCC_SH_NMID_DIV0S			0x0020	//
#define BGBCC_SH_NMID_CMPSTR		0x0021	//
#define BGBCC_SH_NMID_MULUW			0x0022	//
#define BGBCC_SH_NMID_MULSW			0x0023	//
#define BGBCC_SH_NMID_MACL			0x0024	//
#define BGBCC_SH_NMID_BSRF			0x0025	//
#define BGBCC_SH_NMID_BRAF			0x0026	//
#define BGBCC_SH_NMID_MULL			0x0027	//
#define BGBCC_SH_NMID_CLRT			0x0028	//
#define BGBCC_SH_NMID_SETT			0x0029	//
#define BGBCC_SH_NMID_CLRMAC		0x002A	//
#define BGBCC_SH_NMID_NOP			0x002B	//
#define BGBCC_SH_NMID_MOVT			0x002C	//
#define BGBCC_SH_NMID_RTS			0x002D	//
#define BGBCC_SH_NMID_SLEEP			0x002E	//
#define BGBCC_SH_NMID_RTE			0x002F	//
#define BGBCC_SH_NMID_SHLL			0x0030	//
#define BGBCC_SH_NMID_DT			0x0031	//
#define BGBCC_SH_NMID_SHAL			0x0032	//
#define BGBCC_SH_NMID_SHLR			0x0033	//
#define BGBCC_SH_NMID_CMPPZ			0x0034	//
#define BGBCC_SH_NMID_SHAR			0x0035	//
#define BGBCC_SH_NMID_ROTL			0x0036	//
#define BGBCC_SH_NMID_ROTCL			0x0037	//
#define BGBCC_SH_NMID_ROTT			0x0038	//
#define BGBCC_SH_NMID_ROTCR			0x0039	//
#define BGBCC_SH_NMID_SHLL2			0x003A	//
#define BGBCC_SH_NMID_ROTR			0x003B	//
#define BGBCC_SH_NMID_CMPPL			0x003C	//
#define BGBCC_SH_NMID_SHLL8			0x003D	//
#define BGBCC_SH_NMID_SHLL16		0x003E	//
#define BGBCC_SH_NMID_SHLR2			0x003F	//
#define BGBCC_SH_NMID_SHLR8			0x0040	//
#define BGBCC_SH_NMID_SHLR16		0x0041	//
#define BGBCC_SH_NMID_MACW			0x0042	//
#define BGBCC_SH_NMID_NOT			0x0043	//
#define BGBCC_SH_NMID_SWAPB			0x0044	//
#define BGBCC_SH_NMID_SWAPW			0x0045	//
#define BGBCC_SH_NMID_NEGC			0x0046	//
#define BGBCC_SH_NMID_NEG			0x0047	//
#define BGBCC_SH_NMID_EXTUB			0x0048	//
#define BGBCC_SH_NMID_EXTUW			0x0049	//
#define BGBCC_SH_NMID_EXTSB			0x004A	//
#define BGBCC_SH_NMID_EXTSW			0x004B	//
#define BGBCC_SH_NMID_TRAPA			0x004C	//
#define BGBCC_SH_NMID_MOVA			0x004D	//
#define BGBCC_SH_NMID_TSTB			0x004E	//
#define BGBCC_SH_NMID_DIV0U			0x004F	//
#define BGBCC_SH_NMID_LDC			0x0050	//
#define BGBCC_SH_NMID_LDCL			0x0051	//
#define BGBCC_SH_NMID_LDS			0x0052	//
#define BGBCC_SH_NMID_LDSL			0x0053	//
#define BGBCC_SH_NMID_STC			0x0054	//
#define BGBCC_SH_NMID_STCL			0x0055	//
#define BGBCC_SH_NMID_STS			0x0056	//
#define BGBCC_SH_NMID_STSL			0x0057	//
#define BGBCC_SH_NMID_CASL			0x0058	//
#define BGBCC_SH_NMID_TASB			0x0059	//
#define BGBCC_SH_NMID_XTRCT			0x005A	//
#define BGBCC_SH_NMID_ANDB			0x005B	//
#define BGBCC_SH_NMID_XORB			0x005C	//
#define BGBCC_SH_NMID_ORB			0x005D	//
#define BGBCC_SH_NMID_SHAD			0x005E	//
#define BGBCC_SH_NMID_SHLD			0x005F	//
#define BGBCC_SH_NMID_INVDLY		0x0060	//
#define BGBCC_SH_NMID_CLRS			0x0061	//
#define BGBCC_SH_NMID_SETS			0x0062	//
#define BGBCC_SH_NMID_MOVI20		0x0063	//MOVI20
#define BGBCC_SH_NMID_MOVI20S		0x0064	//MOVI20S
#define BGBCC_SH_NMID_MOVUB			0x0065	//MOVU.B
#define BGBCC_SH_NMID_MOVUW			0x0066	//MOVU.W
#define BGBCC_SH_NMID_MOVUL			0x0067	//MOVU.L
#define BGBCC_SH_NMID_LEAB			0x0068	//LEA.B
#define BGBCC_SH_NMID_LEAW			0x0069	//LEA.W
#define BGBCC_SH_NMID_LEAL			0x006A	//LEA.L
#define BGBCC_SH_NMID_LEAQ			0x006B	//LEA.Q
#define BGBCC_SH_NMID_LEAO			0x006C	//LEA.O
#define BGBCC_SH_NMID_NOTT			0x006D	//
#define BGBCC_SH_NMID_LDTLB			0x006E	//
#define BGBCC_SH_NMID_BRK			0x006F	//
#define BGBCC_SH_NMID_MOVRT			0x0070	//
#define BGBCC_SH_NMID_MOVCAL		0x0071	//
#define BGBCC_SH_NMID_PUSH			0x0072	//
#define BGBCC_SH_NMID_POP			0x0073	//
#define BGBCC_SH_NMID_ICLRMD		0x0074	//
#define BGBCC_SH_NMID_ISETMD		0x0075	//
#define BGBCC_SH_NMID_SHLL1			0x0076	//
#define BGBCC_SH_NMID_LDHF16		0x0077	//
#define BGBCC_SH_NMID_BRAN			0x0078	//BRA/N
#define BGBCC_SH_NMID_BSRN			0x0079	//BSR/N
#define BGBCC_SH_NMID_RTSN			0x007A	//
#define BGBCC_SH_NMID_LDIF16		0x007B	//
#define BGBCC_SH_NMID_STHF16		0x007C	//
#define BGBCC_SH_NMID_CSELT			0x007D	//
#define BGBCC_SH_NMID_EXTUL			0x007E	//
#define BGBCC_SH_NMID_EXTSL			0x007F	//
#define BGBCC_SH_NMID_FABS			0x0080	//
#define BGBCC_SH_NMID_FADD			0x0081	//
#define BGBCC_SH_NMID_FCMPEQ		0x0082	//
#define BGBCC_SH_NMID_FCMPGT		0x0083	//
#define BGBCC_SH_NMID_FCNVDS		0x0084	//
#define BGBCC_SH_NMID_FCNVSD		0x0085	//
#define BGBCC_SH_NMID_FDIV			0x0086	//
#define BGBCC_SH_NMID_FLDI0			0x0087	//
#define BGBCC_SH_NMID_FLDI1			0x0088	//
#define BGBCC_SH_NMID_FLDS			0x0089	//
#define BGBCC_SH_NMID_FLOAT			0x008A	//
#define BGBCC_SH_NMID_FMAC			0x008B	//
#define BGBCC_SH_NMID_FMOV			0x008C	//
#define BGBCC_SH_NMID_FMOVS			0x008D	//
#define BGBCC_SH_NMID_FMOVD			0x008E	//
#define BGBCC_SH_NMID_FMUL			0x008F	//
#define BGBCC_SH_NMID_FNEG			0x0090	//
#define BGBCC_SH_NMID_FSCHG			0x0091	//
#define BGBCC_SH_NMID_FSQRT			0x0092	//
#define BGBCC_SH_NMID_FSTS			0x0093	//
#define BGBCC_SH_NMID_FSUB			0x0094	//
#define BGBCC_SH_NMID_FTRC			0x0095	//
#define BGBCC_SH_NMID_FSRRA			0x0096	//
#define BGBCC_SH_NMID_FIPR			0x0097	//
#define BGBCC_SH_NMID_FTRV			0x0098	//
#define BGBCC_SH_NMID_PSETMD4		0x0099	//
#define BGBCC_SH_NMID_PSETMD12		0x009A	//
#define BGBCC_SH_NMID_FMOVX			0x009B	//
#define BGBCC_SH_NMID_FMOVIS		0x009C	//
#define BGBCC_SH_NMID_FMOVID		0x009D	//
#define BGBCC_SH_NMID_FMOVSI		0x009E	//
#define BGBCC_SH_NMID_FMOVDI		0x009F	//

#define BGBCC_SH_NMID_FLDCF			0x00A8	//
#define BGBCC_SH_NMID_FLDCD			0x00A9	//
#define BGBCC_SH_NMID_FLDCI			0x00AA	//
#define BGBCC_SH_NMID_FLDCH			0x00AB	//
#define BGBCC_SH_NMID_FSTCF			0x00AC	//
#define BGBCC_SH_NMID_FSTCD			0x00AD	//
#define BGBCC_SH_NMID_FSTCI			0x00AE	//
#define BGBCC_SH_NMID_FSTCH			0x00AF	//
#define BGBCC_SH_NMID_FRCPA			0x00B0	//
#define BGBCC_SH_NMID_FSQRTA		0x00B1	//
#define BGBCC_SH_NMID_FRCP			0x00B2	//
#define BGBCC_SH_NMID_SWCPLW		0x00B3	//
#define BGBCC_SH_NMID_SWCPMW		0x00B4	//
#define BGBCC_SH_NMID_SWCPHW		0x00B5	//
#define BGBCC_SH_NMID_SWAPMW		0x00B6	//
#define BGBCC_SH_NMID_SWAPHW		0x00B7	//
#define BGBCC_SH_NMID_SWAPL			0x00B8	//
#define BGBCC_SH_NMID_SWAPLW		0x00B9	//
#define BGBCC_SH_NMID_BSR2F			0x00BA	//BSRF, 32-bit align
#define BGBCC_SH_NMID_BRA2F			0x00BB	//BRAF, 32-bit align
#define BGBCC_SH_NMID_MOVDL			0x00BC	//MOVD.L
#define BGBCC_SH_NMID_RET			0x00BD	//
#define BGBCC_SH_NMID_PUSHX2		0x00BE	//
#define BGBCC_SH_NMID_POPX2			0x00BF	//
#define BGBCC_SH_NMID_MOVI			0x00C0	//
#define BGBCC_SH_NMID_MOVIV			0x00C1	//
#define BGBCC_SH_NMID_PREF			0x00C2	//
#define BGBCC_SH_NMID_OCBI			0x00C3	//
#define BGBCC_SH_NMID_OCBP			0x00C4	//
#define BGBCC_SH_NMID_OCBWB			0x00C5	//
#define BGBCC_SH_NMID_ICBI			0x00C6	//
#define BGBCC_SH_NMID_MOVQ			0x00C7	//MOV.Q
#define BGBCC_SH_NMID_ADDQ			0x00C8	//ADD
#define BGBCC_SH_NMID_SUBQ			0x00C9	//SUB
#define BGBCC_SH_NMID_MULQ			0x00CA	//SUB
#define BGBCC_SH_NMID_ANDQ			0x00CB	//SUB
#define BGBCC_SH_NMID_ORQ			0x00CC	//SUB
#define BGBCC_SH_NMID_XORQ			0x00CD	//SUB
#define BGBCC_SH_NMID_SHLLQ			0x00CE	//SUB
#define BGBCC_SH_NMID_SHLRQ			0x00CF	//SUB
#define BGBCC_SH_NMID_SHALQ			0x00D0	//SUB
#define BGBCC_SH_NMID_SHARQ			0x00D1	//SUB
#define BGBCC_SH_NMID_LDSH16		0x00D2	//SUB
#define BGBCC_SH_NMID_TSTQ			0x00D3	//SUB
#define BGBCC_SH_NMID_SHADQ			0x00D4	//
#define BGBCC_SH_NMID_SHLDQ			0x00D5	//
#define BGBCC_SH_NMID_SHLL4			0x00D6	//
#define BGBCC_SH_NMID_SHLR4			0x00D7	//
#define BGBCC_SH_NMID_BREQ			0x00D8	//
#define BGBCC_SH_NMID_BRNE			0x00D9	//
#define BGBCC_SH_NMID_BRGT			0x00DA	//
#define BGBCC_SH_NMID_BRLE			0x00DB	//
#define BGBCC_SH_NMID_BRGE			0x00DC	//
#define BGBCC_SH_NMID_BRLT			0x00DD	//
#define BGBCC_SH_NMID_ICLRMD_DQ		0x00DE	//
#define BGBCC_SH_NMID_ISETMD_DQ		0x00DF	//
#define BGBCC_SH_NMID_CMPQHS		0x00E0	//CMPQ/HS
#define BGBCC_SH_NMID_CMPQHI		0x00E1	//CMPQ/HI
#define BGBCC_SH_NMID_CMPQEQ		0x00E2	//CMPQ/EQ
#define BGBCC_SH_NMID_CMPQGE		0x00E3	//CMPQ/GE
#define BGBCC_SH_NMID_CMPQGT		0x00E4	//CMPQ/GT
#define BGBCC_SH_NMID_CMPQPZ		0x00E5	//CMPQ/PZ
#define BGBCC_SH_NMID_CMPQPL		0x00E6	//CMPQ/PL
#define BGBCC_SH_NMID_NOTS			0x00E7	//
#define BGBCC_SH_NMID_SHLL32		0x00E8	//
#define BGBCC_SH_NMID_SHLR32		0x00E9	//
#define BGBCC_SH_NMID_SHLR1			0x00EA	//
#define BGBCC_SH_NMID_SHAR1			0x00EB	//
#define BGBCC_SH_NMID_SHAR2			0x00EC	//
#define BGBCC_SH_NMID_SHAR4			0x00ED	//
#define BGBCC_SH_NMID_SHAR8			0x00EE	//
#define BGBCC_SH_NMID_SHAR16		0x00EF	//
#define BGBCC_SH_NMID_SHAR32		0x00F0	//
#define BGBCC_SH_NMID_LDSH8			0x00F1	//SUB
#define BGBCC_SH_NMID_BRA8B			0x00F2	//SUB
// #define BGBCC_SH_NMID_SHARX			0x00F3	//SUB
#define BGBCC_SH_NMID_MOVNT			0x00F4	//
#define BGBCC_SH_NMID_CLZ			0x00F5	//
#define BGBCC_SH_NMID_CLZQ			0x00F6	//
#define BGBCC_SH_NMID_SWAP8B		0x00F7	//
#define BGBCC_SH_NMID_SWCPLB		0x00F8	//
#define BGBCC_SH_NMID_SWAPLB		0x00F9	//
#define BGBCC_SH_NMID_SWAPMB		0x00FA	//
#define BGBCC_SH_NMID_SWAPHB		0x00FB	//
#define BGBCC_SH_NMID_SWCPMB		0x00FC	//
#define BGBCC_SH_NMID_SWCPHB		0x00FD	//
#define BGBCC_SH_NMID_LDBF16		0x00FE	//
#define BGBCC_SH_NMID_STBF16		0x00FF	//

#define BGBCC_SH_NMID_ADDL			0x0100	//
#define BGBCC_SH_NMID_SUBL			0x0101	//
#define BGBCC_SH_NMID_PADDW			0x0102	//
#define BGBCC_SH_NMID_PADDL			0x0103	//
#define BGBCC_SH_NMID_PSUBW			0x0104	//
#define BGBCC_SH_NMID_PSUBL			0x0105	//
#define BGBCC_SH_NMID_PMULUW		0x0106	//
#define BGBCC_SH_NMID_MOVD			0x0107	//
#define BGBCC_SH_NMID_MOVHD			0x0108	//
#define BGBCC_SH_NMID_MOVLD			0x0109	//
#define BGBCC_SH_NMID_MOVHLD		0x010A	//
#define BGBCC_SH_NMID_MOVLHD		0x010B	//
#define BGBCC_SH_NMID_ADDSL			0x010C	//ADD
#define BGBCC_SH_NMID_ADDUL			0x010D	//ADD
#define BGBCC_SH_NMID_SUBSL			0x010E	//ADD
#define BGBCC_SH_NMID_SUBUL			0x010F	//ADD

#define BGBCC_SH_NMID_CMOVTB		0x0110	//CMOVT.B
#define BGBCC_SH_NMID_CMOVTW		0x0111	//CMOVT.W
#define BGBCC_SH_NMID_CMOVTL		0x0112	//CMOVT.L
#define BGBCC_SH_NMID_CMOVTQ		0x0113	//CMOVT.Q
#define BGBCC_SH_NMID_CMOVFB		0x0114	//CMOVF.B
#define BGBCC_SH_NMID_CMOVFW		0x0115	//CMOVF.W
#define BGBCC_SH_NMID_CMOVFL		0x0116	//CMOVF.L
#define BGBCC_SH_NMID_CMOVFQ		0x0117	//CMOVF.Q
#define BGBCC_SH_NMID_CMOVUTB		0x0118	//CMOVUT.B
#define BGBCC_SH_NMID_CMOVUTW		0x0119	//CMOVUT.W
#define BGBCC_SH_NMID_CMOVUTL		0x011A	//CMOVUT.L
#define BGBCC_SH_NMID_CMOVDTL		0x011B	//CMOVDT.L
#define BGBCC_SH_NMID_CMOVUFB		0x011C	//CMOVUF.B
#define BGBCC_SH_NMID_CMOVUFW		0x011D	//CMOVUF.W
#define BGBCC_SH_NMID_CMOVUFL		0x011E	//CMOVUF.L
#define BGBCC_SH_NMID_CMOVDFL		0x011F	//CMOVDF.L

#define BGBCC_SH_NMID_MOVX2			0x0120	//
#define BGBCC_SH_NMID_PADDH			0x0121	//
#define BGBCC_SH_NMID_PSUBH			0x0122	//
#define BGBCC_SH_NMID_PMULH			0x0123	//
#define BGBCC_SH_NMID_WEXMD			0x0124	//
#define BGBCC_SH_NMID_CPUID			0x0125	//
#define BGBCC_SH_NMID_RTSU			0x0126	//
#define BGBCC_SH_NMID_SYSCALL		0x0127	//
#define BGBCC_SH_NMID_INVIC			0x0128	//
#define BGBCC_SH_NMID_INVDC			0x0129	//
#define BGBCC_SH_NMID_INVTLB		0x012A	//
#define BGBCC_SH_NMID_JLDI			0x012B	//
#define BGBCC_SH_NMID_MULUL			0x012C	//MULU.L
#define BGBCC_SH_NMID_MULSL			0x012D	//MULS.L
#define BGBCC_SH_NMID_BRA2B			0x012E	//BRA (16-bit)
#define BGBCC_SH_NMID_BRA4B			0x012F	//BRA (32-bit)

#define BGBCC_SH_NMID_FLDCFH		0x0130	//
#define BGBCC_SH_NMID_FSTCFH		0x0131	//
#define BGBCC_SH_NMID_RGB5SHR1		0x0132	//
#define BGBCC_SH_NMID_PMULSW		0x0133	//
#define BGBCC_SH_NMID_PMULULW		0x0134	//
#define BGBCC_SH_NMID_PMULSLW		0x0135	//
#define BGBCC_SH_NMID_PMULUHW		0x0136	//
#define BGBCC_SH_NMID_PMULSHW		0x0137	//
#define BGBCC_SH_NMID_RGB5PCK32		0x0138	//
#define BGBCC_SH_NMID_RGB5PCK64		0x0139	//
#define BGBCC_SH_NMID_RGB5UPCK32	0x013A	//
#define BGBCC_SH_NMID_RGB5UPCK64	0x013B	//
#define BGBCC_SH_NMID_RGB32PCK64	0x013C	//
#define BGBCC_SH_NMID_RGB32UPCK64	0x013D	//
#define BGBCC_SH_NMID_PSHUFB		0x013E	//
#define BGBCC_SH_NMID_PSHUFW		0x013F	//

#define BGBCC_SH_NMID_PADDF			0x0140	//
#define BGBCC_SH_NMID_PSUBF			0x0141	//
#define BGBCC_SH_NMID_PMULF			0x0142	//
#define BGBCC_SH_NMID_PADDFX		0x0143	//
#define BGBCC_SH_NMID_PSUBFX		0x0144	//
#define BGBCC_SH_NMID_PMULFX		0x0145	//
#define BGBCC_SH_NMID_PSHUFL		0x0146	//
#define BGBCC_SH_NMID_PSHUFXL		0x0147	//
#define BGBCC_SH_NMID_CTZ			0x0148	//
#define BGBCC_SH_NMID_CTZQ			0x0149	//
#define BGBCC_SH_NMID_BTRNS			0x014A	//
#define BGBCC_SH_NMID_BTRNSQ		0x014B	//
#define BGBCC_SH_NMID_PMORTL		0x014C	//
#define BGBCC_SH_NMID_PMORTQ		0x014D	//
#define BGBCC_SH_NMID_MOVP			0x014E	//MOV.P
#define BGBCC_SH_NMID_LEAP			0x014F	//LEA.P

#define BGBCC_SH_NMID_PADDXD		0x0150	//
#define BGBCC_SH_NMID_PSUBXD		0x0151	//
#define BGBCC_SH_NMID_PMULXD		0x0152	//
#define BGBCC_SH_NMID_MOVQ_DISP		0x0153	//MOV.Q, explicit displacement

#define BGBCC_SH_NMID_PCSELTW		0x0154	//
#define BGBCC_SH_NMID_PCSELTL		0x0155	//
#define BGBCC_SH_NMID_PCMPEQW		0x0156	//
#define BGBCC_SH_NMID_PCMPEQL		0x0157	//
#define BGBCC_SH_NMID_PCMPHIW		0x0158	//
#define BGBCC_SH_NMID_PCMPHIL		0x0159	//
#define BGBCC_SH_NMID_PCMPGTW		0x015A	//
#define BGBCC_SH_NMID_PCMPGTL		0x015B	//
#define BGBCC_SH_NMID_PCMPEQH		0x015C	//
#define BGBCC_SH_NMID_PCMPEQF		0x015D	//
#define BGBCC_SH_NMID_PCMPGTH		0x015E	//
#define BGBCC_SH_NMID_PCMPGTF		0x015F	//

#define BGBCC_SH_NMID_SHLL64		0x0160	//
#define BGBCC_SH_NMID_SHLR64		0x0161	//
#define BGBCC_SH_NMID_FADDX			0x0162	//
#define BGBCC_SH_NMID_FSUBX			0x0163	//
#define BGBCC_SH_NMID_FMULX			0x0164	//
#define BGBCC_SH_NMID_FMACX			0x0165	//
#define BGBCC_SH_NMID_FCMPXEQ		0x0166	//
#define BGBCC_SH_NMID_FCMPXGT		0x0167	//
#define BGBCC_SH_NMID_FLDCDX		0x0168	//
#define BGBCC_SH_NMID_FSTCDX		0x0169	//
#define BGBCC_SH_NMID_FLDCIX		0x016A	//
#define BGBCC_SH_NMID_FSTCIX		0x016B	//
#define BGBCC_SH_NMID_SHADX			0x016C	//
#define BGBCC_SH_NMID_SHLDX			0x016D	//
#define BGBCC_SH_NMID_SHARX			0x016E	//
#define BGBCC_SH_NMID_SHLRX			0x016F	//

#define BGBCC_SH_NMID_ADDX			0x0170	//
#define BGBCC_SH_NMID_SUBX			0x0171	//
#define BGBCC_SH_NMID_ADCX			0x0172	//
#define BGBCC_SH_NMID_SBBX			0x0173	//
#define BGBCC_SH_NMID_ROTLX			0x0174	//
#define BGBCC_SH_NMID_ANDX			0x0175	//
#define BGBCC_SH_NMID_ORX			0x0176	//
#define BGBCC_SH_NMID_XORX			0x0177	//
#define BGBCC_SH_NMID_CMPXEQ		0x0178	//
#define BGBCC_SH_NMID_CMPXHI		0x0179	//
#define BGBCC_SH_NMID_CMPXGT		0x017A	//

#define BGBCC_SH_NMID_BLKUTX1		0x017C	//
#define BGBCC_SH_NMID_BLKUTX2		0x017D	//
#define BGBCC_SH_NMID_BLKUTX3H		0x017E	//
#define BGBCC_SH_NMID_BLKUTX3L		0x017F	//
#define BGBCC_SH_NMID_BLINTW		0x0180	//
#define BGBCC_SH_NMID_BLERPW		0x0181	//
#define BGBCC_SH_NMID_BLINTAW		0x0182	//
#define BGBCC_SH_NMID_PSTCH			0x0183	//
#define BGBCC_SH_NMID_PLDCH			0x0184	//
#define BGBCC_SH_NMID_PLDCHH		0x0185	//

#define BGBCC_SH_NMID_PLDCM8SH		0x0188	//
#define BGBCC_SH_NMID_PLDCM8UH		0x0189	//
#define BGBCC_SH_NMID_PSTCM8SH		0x018A	//
#define BGBCC_SH_NMID_PSTCM8UH		0x018B	//
#define BGBCC_SH_NMID_BRAB			0x018C	//
#define BGBCC_SH_NMID_BSRB			0x018D	//
#define BGBCC_SH_NMID_BTB			0x018E	//
#define BGBCC_SH_NMID_BFB			0x018F	//

#define BGBCC_SH_NMID_BRAL			0x0190	//
#define BGBCC_SH_NMID_BSRL			0x0191	//
#define BGBCC_SH_NMID_BTL			0x0192	//
#define BGBCC_SH_NMID_BFL			0x0193	//


#define BGBCC_SH_FMID_REGREG		0x01	//Rm, Rn
#define BGBCC_SH_FMID_REGRM			0x02	//Rm
#define BGBCC_SH_FMID_REGRN			0x03	//Rn
#define BGBCC_SH_FMID_REGIMM		0x04	//Imm, Rn
#define BGBCC_SH_FMID_REGLDABS		0x05	//@(Abs), Rn
#define BGBCC_SH_FMID_REGST			0x06	//Rm, @Rn
#define BGBCC_SH_FMID_REGLD			0x07	//@Rm, Rn
#define BGBCC_SH_FMID_REGDECST		0x08	//Rm, @-Rn
#define BGBCC_SH_FMID_REGINCLD		0x09	//@Rm+, Rn
#define BGBCC_SH_FMID_REGSTR0N		0x0A	//Rm, @(Ro+Rn)
#define BGBCC_SH_FMID_REGLDR0M		0x0B	//@(Ro+Rm), Rn
#define BGBCC_SH_FMID_REGSTDISP		0x0C	//Rm, @(Rn+Disp)
#define BGBCC_SH_FMID_REGLDDISP		0x0D	//@(Rm+Disp), Rn
#define BGBCC_SH_FMID_ABS			0x0E	//@(Abs)
#define BGBCC_SH_FMID_NONE			0x0F	//-

#define BGBCC_SH_FMID_IMM			0x10	//Imm
#define BGBCC_SH_FMID_LDREG			0x11	//@Rm
#define BGBCC_SH_FMID_STREG			0x12	//@Rn
#define BGBCC_SH_FMID_IMMSTRMN		0x13	//Imm, @(Rm+Rn)
#define BGBCC_SH_FMID_REGVIMM		0x14	//<Imm>, Rn
#define BGBCC_SH_FMID_FREGREG		0x15	//FRm, FRn
#define BGBCC_SH_FMID_FREGRM		0x16	//FRm
#define BGBCC_SH_FMID_FREGRN		0x17	//FRn
#define BGBCC_SH_FMID_DREGREG		0x18	//FRm, FRn
#define BGBCC_SH_FMID_DREGRM		0x19	//FRm
#define BGBCC_SH_FMID_DREGRN		0x1A	//FRn
#define BGBCC_SH_FMID_LABEL			0x1B	//<Lbl>
#define BGBCC_SH_FMID_LBLREG		0x1C	//<Lbl>, Rn
#define BGBCC_SH_FMID_REGREGREG		0x1D	//Rn, Rm, Ro
#define BGBCC_SH_FMID_REGINCST		0x1E	//Rm, @+Rn
#define BGBCC_SH_FMID_REGDECLD		0x1F	//@Rm-, Rn

#define BGBCC_SH_FMID_REGSTRODISP	0x20	//Rm, @(Rn,Ro,Disp)
#define BGBCC_SH_FMID_REGLDRODISP	0x21	//@(Rm,Ro,Disp), Rn
#define BGBCC_SH_FMID_REGIMMREG		0x22	//Rm, Imm, Rn
#define BGBCC_SH_FMID_FREGREGREG	0x23	//FRm, FRo, FRn
#define BGBCC_SH_FMID_DREGREGREG	0x24	//DRm, DRo, DRn
#define BGBCC_SH_FMID_REGLBL		0x25	//Rn, <Lbl>
#define BGBCC_SH_FMID_FREGST		0x26	//FRm, @Rn
#define BGBCC_SH_FMID_FREGLD		0x27	//@Rm, FRn
#define BGBCC_SH_FMID_FREGDECST		0x28	//FRm, @-Rn
#define BGBCC_SH_FMID_FREGINCLD		0x29	//@Rm+, FRn
#define BGBCC_SH_FMID_FREGSTR0N		0x2A	//FRm, @(Ro+Rn)
#define BGBCC_SH_FMID_FREGLDR0M		0x2B	//@(Ro+Rm), FRn
#define BGBCC_SH_FMID_FREGSTDISP	0x2C	//FRm, @(Rn+Disp)
#define BGBCC_SH_FMID_FREGLDDISP	0x2D	//@(Rm+Disp), FRn
#define BGBCC_SH_FMID_FREGSTRODISP	0x2E	//FRm, @(Rn,Ro,Disp)
#define BGBCC_SH_FMID_FREGLDRODISP	0x2F	//@(Rm,Ro,Disp), FRn

#define BGBCC_SH_FMID_REG1ABS		0x30	//Rn, @(Abs)
#define BGBCC_SH_FMID_REG2ABS		0x31	//Rm, Rn, @(Abs)

#define BGBCC_SH_FMID_DREGST		0x36	//DRm, @Rn
#define BGBCC_SH_FMID_DREGLD		0x37	//@Rm, DRn
#define BGBCC_SH_FMID_DREGDECST		0x38	//DRm, @-Rn
#define BGBCC_SH_FMID_DREGINCLD		0x39	//@Rm+, DRn
#define BGBCC_SH_FMID_DREGSTR0N		0x3A	//DRm, @(Ro+Rn)
#define BGBCC_SH_FMID_DREGLDR0M		0x3B	//@(Ro+Rm), DRn
#define BGBCC_SH_FMID_DREGSTDISP	0x3C	//DRm, @(Rn+Disp)
#define BGBCC_SH_FMID_DREGLDDISP	0x3D	//@(Rm+Disp), DRn
#define BGBCC_SH_FMID_DREGSTRODISP	0x3E	//DRm, @(Rn,Ro,Disp)
#define BGBCC_SH_FMID_DREGLDRODISP	0x3F	//@(Rm,Ro,Disp), DRn


#define BGBCC_SH_OPVTY_NONE			0x00	//None
#define BGBCC_SH_OPVTY_IMM			0x01	//#Imm
#define BGBCC_SH_OPVTY_REG			0x02	//Reg
#define BGBCC_SH_OPVTY_NAME			0x03	//Name
#define BGBCC_SH_OPVTY_DRREG		0x04	//@Reg
#define BGBCC_SH_OPVTY_DRREGI		0x05	//@Reg+
#define BGBCC_SH_OPVTY_DRREGD		0x06	//@-Reg

#define BGBCC_SH_OPVTY_RRMEM		0x08	//@(Reg,Reg)
#define BGBCC_SH_OPVTY_RDMEM		0x09	//@(Reg,Disp)

#define BGBCC_SH_RLC_REL8			0x01	//Relative BYTE (xx)
#define BGBCC_SH_RLC_REL16			0x02	//Relative WORD (xxxx)
#define BGBCC_SH_RLC_REL32			0x03	//Relative DWORD (xxxx_xxxx)
#define BGBCC_SH_RLC_ABS8			0x04	//Absolute BYTE (Low 8 bits)
#define BGBCC_SH_RLC_ABS16			0x05	//Absolute WORD (Low 16 bits)
#define BGBCC_SH_RLC_ABS32			0x06	//Absolute DWORD
#define BGBCC_SH_RLC_ABS64			0x07	//Absolute QWORD
#define BGBCC_SH_RLC_RELW12			0x08	//Relative Low 12 bits (WORD)
											//Oxxx
#define BGBCC_SH_RLC_RELW8			0x09	//Relative Low 8 bit (WORD)
											//OOxx
#define BGBCC_SH_RLC_REL32B			0x0A	//Relative DWORD (Reverse)

#define BGBCC_SH_RLC_RELW12L		0x0B	//Relative Low 12 bits (DWORD)
#define BGBCC_SH_RLC_RELW8L			0x0C	//Relative Low 8 bit (DWORD)

#define BGBCC_SH_RLC_REL20_2A		0x0D	//Relative 20 bit (BYTE, SH2A)
#define BGBCC_SH_RLC_RELW16_BJX		0x0E	//Relative 16 bit (WORD, BJX1)
											//OOxx_OOxx
#define BGBCC_SH_RLC_RELW20_BJX		0x0F	//Relative 20 bit (WORD, BJX1)
											//OOxx_Oxxx
#define BGBCC_SH_RLC_REL24_BJX		0x10	//Relative 24 bit (BYTE, BJX1)
											//OOxx_xxxx
#define BGBCC_SH_RLC_REL24B_BJX		0x11	//Relative 24 bit (BYTE, BJX1, Rev)
											//OOxx_xxxx
#define BGBCC_SH_RLC_RVA32			0x12	//RVA (DWORD)
#define BGBCC_SH_RLC_RELW24_BJX		0x13	//Relative 24 bit (WORD, BJX1)
											//OOxx_xxxx

#define BGBCC_SH_RLC_PBO24_BJX		0x14	//PBO 24 bit (BYTE, BJX2)
											//OOxx_xxxx
#define BGBCC_SH_RLC_PBO32_BJX		0x15	//PBO 24 bit (BYTE, BJX2)
											//OOxx_xxxx_OOxx
#define BGBCC_SH_RLC_TBR24_BJX		0x16	//TBR 24 bit (BYTE, BJX2)
											//OOxx_xxxx
#define BGBCC_SH_RLC_TBR12_BJX		0x17	//TBR 12 bit (BYTE, BJX2)

#define BGBCC_SH_RLC_RELW16C_BSR	0x18	//Relative 16 bit (BYTE, BSR1)
											//OOxx_OOxx
#define BGBCC_SH_RLC_RELW16_BSR		0x19	//Relative 16 bit (WORD, BSR1)
											//OOxx_OOxx
#define BGBCC_SH_RLC_RELW24C_BSR	0x1A	//Relative 24 bit (BYTE, BSR1)
											//OOxx_OOxx_OOxx
#define BGBCC_SH_RLC_RELW24_BSR		0x1B	//Relative 24 bit (WORD, BSR1)
											//OOxx_OOxx_OOxx

#define BGBCC_SH_RLC_ABSW16A_BSR	0x1C	//Absolute BYTE (Low 16 bits)
#define BGBCC_SH_RLC_ABSW24A_BSR	0x1D	//Absolute BYTE (Low 24 bits)
#define BGBCC_SH_RLC_ABSW32A_BSR	0x1E	//Absolute BYTE
#define BGBCC_SH_RLC_RELW8_BSR		0x1F	//Relative Low 8 bit (WORD)

#define BGBCC_SH_RLC_RELW16D_BSR	0x20	//Relative 16 bit (WORD, BSR1)
											//Oxxx_OOOx
#define BGBCC_SH_RLC_RELW24D_BSR	0x21	//Relative 24 bit (WORD, BSR1)
											//Oxxx_OOxx_OOOx
#define BGBCC_SH_RLC_RELW32D_BSR	0x22	//Relative 24 bit (WORD, BSR1)
											//Oxxx_OOxx_OOxx_OOOx

#define BGBCC_SH_RLC_RELW32C_BSR	0x23	//Relative 32 bit (BYTE, BSR1)
											//OOxx_OOxx_OOxx_OOxx

#define BGBCC_SH_RLC_ABSW16B_BSR	0x24	//Absolute BYTE
											//Oxxx_OOOx
#define BGBCC_SH_RLC_ABSW24B_BSR	0x25	//Absolute BYTE
											//Oxxx_OOxx_OOOx
#define BGBCC_SH_RLC_ABSW32B_BSR	0x26	//Absolute BYTE
											//Oxxx_OOxx_OOxx_OOOx

#define BGBCC_SH_RLC_RELW12_BSR		0x27	//Relative Low 12 bits (WORD)

#define BGBCC_SH_RLC_RELW16A_BSR	0x28	//Relative 16 bit (BYTE, BSR1)
											//Oxxx_OOOx
#define BGBCC_SH_RLC_RELW24A_BSR	0x29	//Relative 24 bit (BYTE, BSR1)
											//Oxxx_OOxx_OOOx
#define BGBCC_SH_RLC_RELW32A_BSR	0x2A	//Relative 24 bit (BYTE, BSR1)
											//Oxxx_OOxx_OOxx_OOOx

//#define BGBCC_SH_RLC_PBOJ27_BJX		0x2C	//PBO Jumbo 27 bit (BYTE, BJX2)
											//F4xx_Cxxx_F0nm_OexO
//#define BGBCC_SH_RLC_PBOJ31_BJX		0x2D	//PBO Jumbo 31 bit (BYTE, BJX2)
											//F4xx_Cxxx_F1nm_Oexx
//#define BGBCC_SH_RLC_RELJ27_BJX		0x2E	//Relative Jumbo 27 bit (BYTE, BJX2)
											//F4xx_Cxxx_F0nm_OexO
//#define BGBCC_SH_RLC_RELJ31_BJX		0x2F	//Relative Jumbo 31 bit (BYTE, BJX2)
											//F4xx_Cxxx_F1nm_Oexx

#define BGBCC_SH_RLC_PBO9_BJX		0x2B	//PBO Disp9 (BYTE, BJX2)

#define BGBCC_SH_RLC_PBOJ29_BJX		0x2C	//PBO Jumbo 29 bit (BYTE, BJX2)
#define BGBCC_SH_RLC_PBOJ32_BJX		0x2D	//PBO Jumbo 32 bit (BYTE, BJX2)
#define BGBCC_SH_RLC_RELJ29_BJX		0x2E	//Relative Jumbo 29 bit (BYTE, BJX2)
#define BGBCC_SH_RLC_RELJ32_BJX		0x2F	//Relative Jumbo 32 bit (BYTE, BJX2)

#define BGBCC_SH_RLC_TRIPWIRE_BJX	0x30	//Tripwire Location

#define BGBCC_SH_RLC_RELB13_OP24	0x31	//Relative 13 bit (BYTE, BJX2)


// #define BGBCC_SH_RLC_ABSW48A_BSR	0x20	//Absolute BYTE
// #define BGBCC_SH_RLC_ABSW64A_BSR	0x21	//Absolute BYTE


#define BGBCC_SH_CSEG_TEXT		0x00		//.text section
#define BGBCC_SH_CSEG_STRTAB	0x01		//.strtab section
#define BGBCC_SH_CSEG_RODATA	0x02		//.rodata section
#define BGBCC_SH_CSEG_GOT		0x03		//.got section
#define BGBCC_SH_CSEG_DATA		0x04		//.data section
#define BGBCC_SH_CSEG_BSS		0x05		//.bss section
#define BGBCC_SH_CSEG_RELOC		0x06		//.reloc section

#define BGBCC_SH_CSEG_DYN		0x07		//dynamic sections

#define BGBCC_SH_CSEG_ABS		0x7F		//absolute address

#define BGBCC_SH_REGCLS_NONE	0
#define BGBCC_SH_REGCLS_GR		1	//uses a GPR
#define BGBCC_SH_REGCLS_GR2		2	//uses a pair of GPRs
#define BGBCC_SH_REGCLS_FR		3	//uses a FR
#define BGBCC_SH_REGCLS_FR2		4	//uses a pair of FRs

#define BGBCC_SH_REGCLS_VO_REF	5	//value object, pass by-ref
#define BGBCC_SH_REGCLS_VO_GR	6	//value object pass in GPR
#define BGBCC_SH_REGCLS_VO_GR2	7	//value object pass in GPR pair
#define BGBCC_SH_REGCLS_AR_REF	8	//array object, pass by-ref
// #define BGBCC_SH_REGCLS_PTR		9	//Pointer
#define BGBCC_SH_REGCLS_QGR		9	//Quad GPR
#define BGBCC_SH_REGCLS_VO_QGR	10	//value object pass in Quad GPR
#define BGBCC_SH_REGCLS_VO_QGR2	11	//value object pass in Quad GPR pair
#define BGBCC_SH_REGCLS_WGR		12	//Uses GPR, 16-bit storage

#define BGBCC_SH_REGCLS_DR		13	//uses a FR

#define BGBCC_SH_REGCLS_QGR2	14	//uses a pair of GPRs


#define BGBCC_SH_FPSCR_DN		0x00040000	//
#define BGBCC_SH_FPSCR_PR		0x00080000	//
#define BGBCC_SH_FPSCR_SZ		0x00100000	//
#define BGBCC_SH_FPSCR_FR		0x00200000	//
#define BGBCC_SH_FPSCR_VE		0x01000000	//

#define BGBCC_SH_SRFL_DQ		0x00001000	//64-bit mode (data)
#define BGBCC_SH_SRFL_JQ		0x80000000	//64-bit mode (address)

#define BGBCC_SH_MAX_CACHEVAR 5

#define BGBCC_SH_MAX_CACHEFPVAR 4



#define BGBCC_SHX_GenLabelTemp(ctx)		\
	BGBCC_SHX_GenLabelTempLLn(ctx, __FILE__, __LINE__)
#define BGBCC_SHX_GenLabel(ctx)		\
	BGBCC_SHX_GenLabelLLn(ctx, __FILE__, __LINE__)

#define BGBCC_SHX_GETLREG_LO(reg)		(BGBCC_SH_REG_R0+((reg)&31))
#define BGBCC_SHX_GETLREG_HI(reg)		(BGBCC_SH_REG_R0+(((reg)&31)+1))


#if 0
typedef struct BGBCC_SHX_Context_s BGBCC_SHX_Context;
typedef struct BGBCC_SHX_OpcodeArg_s BGBCC_SHX_OpcodeArg;
typedef struct BGBCC_SHX_VarSpan_s BGBCC_SHX_VarSpan;
typedef struct BGBCC_SHX_VarSpan2_s BGBCC_SHX_VarSpan2;

typedef struct BGBCC_SHX_EmitQueueOp_s BGBCC_SHX_EmitQueueOp;
#endif

#if 1
typedef struct BGBCC_CMG_Context_s BGBCC_SHX_Context;
typedef struct BGBCC_CMG_OpcodeArg_s BGBCC_SHX_OpcodeArg;
typedef struct BGBCC_CMG_VarSpan_s BGBCC_SHX_VarSpan;
typedef struct BGBCC_CMG_VarSpan2_s BGBCC_SHX_VarSpan2;

typedef struct BGBCC_CMG_EmitQueueOp_s BGBCC_SHX_EmitQueueOp;
#endif
