/*
 * SH-ISA
 * Also: BJX1, BJX2, ...
 */

// #define BGBCC_JX2_OLDBTF

/* 00-3F: GPR R00-R63, 32/64 */
#define BGBCC_SH_REG_R0			0x00
#define BGBCC_SH_REG_R1			0x01
#define BGBCC_SH_REG_R2			0x02
#define BGBCC_SH_REG_R3			0x03
#define BGBCC_SH_REG_R4			0x04
#define BGBCC_SH_REG_R5			0x05
#define BGBCC_SH_REG_R6			0x06
#define BGBCC_SH_REG_R7			0x07
#define BGBCC_SH_REG_R8			0x08
#define BGBCC_SH_REG_R9			0x09
#define BGBCC_SH_REG_R10		0x0A
#define BGBCC_SH_REG_R11		0x0B
#define BGBCC_SH_REG_R12		0x0C
#define BGBCC_SH_REG_R13		0x0D
#define BGBCC_SH_REG_R14		0x0E
#define BGBCC_SH_REG_R15		0x0F
#define BGBCC_SH_REG_R16		0x10
#define BGBCC_SH_REG_R17		0x11
#define BGBCC_SH_REG_R18		0x12
#define BGBCC_SH_REG_R19		0x13
#define BGBCC_SH_REG_R20		0x14
#define BGBCC_SH_REG_R21		0x15
#define BGBCC_SH_REG_R22		0x16
#define BGBCC_SH_REG_R23		0x17
#define BGBCC_SH_REG_R24		0x18
#define BGBCC_SH_REG_R25		0x19
#define BGBCC_SH_REG_R26		0x1A
#define BGBCC_SH_REG_R27		0x1B
#define BGBCC_SH_REG_R28		0x1C
#define BGBCC_SH_REG_R29		0x1D
#define BGBCC_SH_REG_R30		0x1E
#define BGBCC_SH_REG_R31		0x1F

#define BGBCC_SH_REG_R32		0x20
#define BGBCC_SH_REG_R33		0x21
#define BGBCC_SH_REG_R34		0x22
#define BGBCC_SH_REG_R35		0x23
#define BGBCC_SH_REG_R36		0x24
#define BGBCC_SH_REG_R37		0x25
#define BGBCC_SH_REG_R38		0x26
#define BGBCC_SH_REG_R39		0x27
#define BGBCC_SH_REG_R40		0x28
#define BGBCC_SH_REG_R41		0x29
#define BGBCC_SH_REG_R42		0x2A
#define BGBCC_SH_REG_R43		0x2B
#define BGBCC_SH_REG_R44		0x2C
#define BGBCC_SH_REG_R45		0x2D
#define BGBCC_SH_REG_R46		0x2E
#define BGBCC_SH_REG_R47		0x2F
#define BGBCC_SH_REG_R48		0x30
#define BGBCC_SH_REG_R49		0x31
#define BGBCC_SH_REG_R50		0x32
#define BGBCC_SH_REG_R51		0x33
#define BGBCC_SH_REG_R52		0x34
#define BGBCC_SH_REG_R53		0x35
#define BGBCC_SH_REG_R54		0x36
#define BGBCC_SH_REG_R55		0x37
#define BGBCC_SH_REG_R56		0x38
#define BGBCC_SH_REG_R57		0x39
#define BGBCC_SH_REG_R58		0x3A
#define BGBCC_SH_REG_R59		0x3B
#define BGBCC_SH_REG_R60		0x3C
#define BGBCC_SH_REG_R61		0x3D
#define BGBCC_SH_REG_R62		0x3E
#define BGBCC_SH_REG_R63		0x3F

/* 40-7F: GPR RQ0-RQ63, 64 */
#define BGBCC_SH_REG_RQ0		0x40
#define BGBCC_SH_REG_RQ1		0x41
#define BGBCC_SH_REG_RQ2		0x42
#define BGBCC_SH_REG_RQ3		0x43
#define BGBCC_SH_REG_RQ4		0x44
#define BGBCC_SH_REG_RQ5		0x45
#define BGBCC_SH_REG_RQ6		0x46
#define BGBCC_SH_REG_RQ7		0x47
#define BGBCC_SH_REG_RQ8		0x48
#define BGBCC_SH_REG_RQ9		0x49
#define BGBCC_SH_REG_RQ10		0x4A
#define BGBCC_SH_REG_RQ11		0x4B
#define BGBCC_SH_REG_RQ12		0x4C
#define BGBCC_SH_REG_RQ13		0x4D
#define BGBCC_SH_REG_RQ14		0x4E
#define BGBCC_SH_REG_RQ15		0x4F
#define BGBCC_SH_REG_RQ16		0x50
#define BGBCC_SH_REG_RQ17		0x51
#define BGBCC_SH_REG_RQ18		0x52
#define BGBCC_SH_REG_RQ19		0x53
#define BGBCC_SH_REG_RQ20		0x54
#define BGBCC_SH_REG_RQ21		0x55
#define BGBCC_SH_REG_RQ22		0x56
#define BGBCC_SH_REG_RQ23		0x57
#define BGBCC_SH_REG_RQ24		0x58
#define BGBCC_SH_REG_RQ25		0x59
#define BGBCC_SH_REG_RQ26		0x5A
#define BGBCC_SH_REG_RQ27		0x5B
#define BGBCC_SH_REG_RQ28		0x5C
#define BGBCC_SH_REG_RQ29		0x5D
#define BGBCC_SH_REG_RQ30		0x5E
#define BGBCC_SH_REG_RQ31		0x5F

#define BGBCC_SH_REG_RQ32		0x60
#define BGBCC_SH_REG_RQ33		0x61
#define BGBCC_SH_REG_RQ34		0x62
#define BGBCC_SH_REG_RQ35		0x63
#define BGBCC_SH_REG_RQ36		0x64
#define BGBCC_SH_REG_RQ37		0x65
#define BGBCC_SH_REG_RQ38		0x66
#define BGBCC_SH_REG_RQ39		0x67
#define BGBCC_SH_REG_RQ40		0x68
#define BGBCC_SH_REG_RQ41		0x69
#define BGBCC_SH_REG_RQ42		0x6A
#define BGBCC_SH_REG_RQ43		0x6B
#define BGBCC_SH_REG_RQ44		0x6C
#define BGBCC_SH_REG_RQ45		0x6D
#define BGBCC_SH_REG_RQ46		0x6E
#define BGBCC_SH_REG_RQ47		0x6F
#define BGBCC_SH_REG_RQ48		0x70
#define BGBCC_SH_REG_RQ49		0x71
#define BGBCC_SH_REG_RQ50		0x72
#define BGBCC_SH_REG_RQ51		0x73
#define BGBCC_SH_REG_RQ52		0x74
#define BGBCC_SH_REG_RQ53		0x75
#define BGBCC_SH_REG_RQ54		0x76
#define BGBCC_SH_REG_RQ55		0x77
#define BGBCC_SH_REG_RQ56		0x78
#define BGBCC_SH_REG_RQ57		0x79
#define BGBCC_SH_REG_RQ58		0x7A
#define BGBCC_SH_REG_RQ59		0x7B
#define BGBCC_SH_REG_RQ60		0x7C
#define BGBCC_SH_REG_RQ61		0x7D
#define BGBCC_SH_REG_RQ62		0x7E
#define BGBCC_SH_REG_RQ63		0x7F

/* 80-9F: FPR DR0-DR15, 64 */
#define BGBCC_SH_REG_DR0		0x80
#define BGBCC_SH_REG_DR1		0x81
#define BGBCC_SH_REG_DR2		0x82
#define BGBCC_SH_REG_DR3		0x83
#define BGBCC_SH_REG_DR4		0x84
#define BGBCC_SH_REG_DR5		0x85
#define BGBCC_SH_REG_DR6		0x86
#define BGBCC_SH_REG_DR7		0x87
#define BGBCC_SH_REG_DR8		0x88
#define BGBCC_SH_REG_DR9		0x89
#define BGBCC_SH_REG_DR10		0x8A
#define BGBCC_SH_REG_DR11		0x8B
#define BGBCC_SH_REG_DR12		0x8C
#define BGBCC_SH_REG_DR13		0x8D
#define BGBCC_SH_REG_DR14		0x8E
#define BGBCC_SH_REG_DR15		0x8F
#define BGBCC_SH_REG_DR16		0x90
#define BGBCC_SH_REG_DR17		0x91
#define BGBCC_SH_REG_DR18		0x92
#define BGBCC_SH_REG_DR19		0x93
#define BGBCC_SH_REG_DR20		0x94
#define BGBCC_SH_REG_DR21		0x95
#define BGBCC_SH_REG_DR22		0x96
#define BGBCC_SH_REG_DR23		0x97
#define BGBCC_SH_REG_DR24		0x98
#define BGBCC_SH_REG_DR25		0x99
#define BGBCC_SH_REG_DR26		0x9A
#define BGBCC_SH_REG_DR27		0x9B
#define BGBCC_SH_REG_DR28		0x9C
#define BGBCC_SH_REG_DR29		0x9D
#define BGBCC_SH_REG_DR30		0x9E
#define BGBCC_SH_REG_DR31		0x9F

/* A0-AF: FPR FR0-FR15, 32 */
#define BGBCC_SH_REG_FR0		0xA0
#define BGBCC_SH_REG_FR1		0xA1
#define BGBCC_SH_REG_FR2		0xA2
#define BGBCC_SH_REG_FR3		0xA3
#define BGBCC_SH_REG_FR4		0xA4
#define BGBCC_SH_REG_FR5		0xA5
#define BGBCC_SH_REG_FR6		0xA6
#define BGBCC_SH_REG_FR7		0xA7
#define BGBCC_SH_REG_FR8		0xA8
#define BGBCC_SH_REG_FR9		0xA9
#define BGBCC_SH_REG_FR10		0xAA
#define BGBCC_SH_REG_FR11		0xAB
#define BGBCC_SH_REG_FR12		0xAC
#define BGBCC_SH_REG_FR13		0xAD
#define BGBCC_SH_REG_FR14		0xAE
#define BGBCC_SH_REG_FR15		0xAF

#define BGBCC_SH_REG_FR16		0xB0
#define BGBCC_SH_REG_FR17		0xB1
#define BGBCC_SH_REG_FR18		0xB2
#define BGBCC_SH_REG_FR19		0xB3
#define BGBCC_SH_REG_FR20		0xB4
#define BGBCC_SH_REG_FR21		0xB5
#define BGBCC_SH_REG_FR22		0xB6
#define BGBCC_SH_REG_FR23		0xB7
#define BGBCC_SH_REG_FR24		0xB8
#define BGBCC_SH_REG_FR25		0xB9
#define BGBCC_SH_REG_FR26		0xBA
#define BGBCC_SH_REG_FR27		0xBB
#define BGBCC_SH_REG_FR28		0xBC
#define BGBCC_SH_REG_FR29		0xBD
#define BGBCC_SH_REG_FR30		0xBE
#define BGBCC_SH_REG_FR31		0xBF

/* C0-FF: GPR RD0-RD63, 32 */
#define BGBCC_SH_REG_RD0		0xC0
#define BGBCC_SH_REG_RD1		0xC1
#define BGBCC_SH_REG_RD2		0xC2
#define BGBCC_SH_REG_RD3		0xC3
#define BGBCC_SH_REG_RD4		0xC4
#define BGBCC_SH_REG_RD5		0xC5
#define BGBCC_SH_REG_RD6		0xC6
#define BGBCC_SH_REG_RD7		0xC7
#define BGBCC_SH_REG_RD8		0xC8
#define BGBCC_SH_REG_RD9		0xC9
#define BGBCC_SH_REG_RD10		0xCA
#define BGBCC_SH_REG_RD11		0xCB
#define BGBCC_SH_REG_RD12		0xCC
#define BGBCC_SH_REG_RD13		0xCD
#define BGBCC_SH_REG_RD14		0xCE
#define BGBCC_SH_REG_RD15		0xCF
#define BGBCC_SH_REG_RD16		0xD0
#define BGBCC_SH_REG_RD17		0xD1
#define BGBCC_SH_REG_RD18		0xD2
#define BGBCC_SH_REG_RD19		0xD3
#define BGBCC_SH_REG_RD20		0xD4
#define BGBCC_SH_REG_RD21		0xD5
#define BGBCC_SH_REG_RD22		0xD6
#define BGBCC_SH_REG_RD23		0xD7
#define BGBCC_SH_REG_RD24		0xD8
#define BGBCC_SH_REG_RD25		0xD9
#define BGBCC_SH_REG_RD26		0xDA
#define BGBCC_SH_REG_RD27		0xDB
#define BGBCC_SH_REG_RD28		0xDC
#define BGBCC_SH_REG_RD29		0xDD
#define BGBCC_SH_REG_RD30		0xDE
#define BGBCC_SH_REG_RD31		0xDF

#define BGBCC_SH_REG_RD32		0xE0
#define BGBCC_SH_REG_RD33		0xE1
#define BGBCC_SH_REG_RD34		0xE2
#define BGBCC_SH_REG_RD35		0xE3
#define BGBCC_SH_REG_RD36		0xE4
#define BGBCC_SH_REG_RD37		0xE5
#define BGBCC_SH_REG_RD38		0xE6
#define BGBCC_SH_REG_RD39		0xE7
#define BGBCC_SH_REG_RD40		0xE8
#define BGBCC_SH_REG_RD41		0xE9
#define BGBCC_SH_REG_RD42		0xEA
#define BGBCC_SH_REG_RD43		0xEB
#define BGBCC_SH_REG_RD44		0xEC
#define BGBCC_SH_REG_RD45		0xED
#define BGBCC_SH_REG_RD46		0xEE
#define BGBCC_SH_REG_RD47		0xEF
#define BGBCC_SH_REG_RD48		0xF0
#define BGBCC_SH_REG_RD49		0xF1
#define BGBCC_SH_REG_RD50		0xF2
#define BGBCC_SH_REG_RD51		0xF3
#define BGBCC_SH_REG_RD52		0xF4
#define BGBCC_SH_REG_RD53		0xF5
#define BGBCC_SH_REG_RD54		0xF6
#define BGBCC_SH_REG_RD55		0xF7
#define BGBCC_SH_REG_RD56		0xF8
#define BGBCC_SH_REG_RD57		0xF9
#define BGBCC_SH_REG_RD58		0xFA
#define BGBCC_SH_REG_RD59		0xFB
#define BGBCC_SH_REG_RD60		0xFC
#define BGBCC_SH_REG_RD61		0xFD
#define BGBCC_SH_REG_RD62		0xFE
#define BGBCC_SH_REG_RD63		0xFF

#define BGBCC_SH_REG_RTMASK		0x3F0
#define BGBCC_SH_REG_RTMASK3	0x3F8
#define BGBCC_SH_REG_RTMASK5	0x3E0
#define BGBCC_SH_REG_RTMASK6	0x3C0

#define BGBCC_SH_REG_ZZR		0x3FF		//Null Register (Placeholder Reg)

#if 1
/* 60-6F: Control Regs */
#define BGBCC_SH_REG_CR0		0x100

#define BGBCC_SH_REG_SR			0x100
#define BGBCC_SH_REG_GBR		0x101
#define BGBCC_SH_REG_VBR		0x102
#define BGBCC_SH_REG_SSR		0x103
#define BGBCC_SH_REG_SPC		0x104

#define BGBCC_SH_REG_TBR		0x105	//placeholder

// #define BGBCC_SH_REG_GBH		0x106
// #define BGBCC_SH_REG_SPH		0x107


#define BGBCC_SH_REG_ISRSAVE	0x107	//virtual, ISR save area

#define BGBCC_SH_REG_R0B		0x108
// #define BGBCC_SH_REG_R1B		0x69
// #define BGBCC_SH_REG_R2B		0x6A
// #define BGBCC_SH_REG_R3B		0x6B
// #define BGBCC_SH_REG_R4B		0x6C
// #define BGBCC_SH_REG_R5B		0x6D
// #define BGBCC_SH_REG_R6B		0x6E
// #define BGBCC_SH_REG_R7B		0x6F

#define BGBCC_SH_REG_R0U		0x108
#define BGBCC_SH_REG_R1U		0x109
#define BGBCC_SH_REG_R15U		0x10A

#define BGBCC_SH_REG_VIPT		0x10B
#define BGBCC_SH_REG_GBH		0x10C
#define BGBCC_SH_REG_PCH		0x10D
#define BGBCC_SH_REG_TEAH		0x10E

#define BGBCC_SH_REG_SP			0x10F

/* 70-7F: Status Regs */
#define BGBCC_SH_REG_SR0		0x110

#define BGBCC_SH_REG_MACH		0x110	//S
#define BGBCC_SH_REG_MACL		0x111	//S
#define BGBCC_SH_REG_PR			0x112	//S
#define BGBCC_SH_REG_SGR		0x113	//C

#define BGBCC_SH_REG_FPUL		0x115
#define BGBCC_SH_REG_FPSCR		0x116
#define BGBCC_SH_REG_PC			0x117


#define BGBCC_SH_REG_TTB		0x118
#define BGBCC_SH_REG_TEA		0x119
#define BGBCC_SH_REG_MMCR		0x11A
#define BGBCC_SH_REG_EXSR		0x11B
#define BGBCC_SH_REG_STTB		0x11C
#define BGBCC_SH_REG_KRR		0x11D

#define BGBCC_SH_REG_DBR		0x11F

#define BGBCC_SH_REG_LR			BGBCC_SH_REG_PR


#endif


#if 1
/* E0-EF: GPR R0-R15 Pair */
#define BGBCC_SH_REG_LR0		0x140
#define BGBCC_SH_REG_LR1		0x141
#define BGBCC_SH_REG_LR2		0x142
#define BGBCC_SH_REG_LR3		0x143
#define BGBCC_SH_REG_LR4		0x144
#define BGBCC_SH_REG_LR5		0x145
#define BGBCC_SH_REG_LR6		0x146
#define BGBCC_SH_REG_LR7		0x147
#define BGBCC_SH_REG_LR8		0x148
#define BGBCC_SH_REG_LR9		0x149
#define BGBCC_SH_REG_LR10		0x14A
#define BGBCC_SH_REG_LR11		0x14B
#define BGBCC_SH_REG_LR12		0x14C
#define BGBCC_SH_REG_LR13		0x14D
#define BGBCC_SH_REG_LR14		0x14E
#define BGBCC_SH_REG_LR15		0x14F		//Invalid

/* F0-FF: GPR R16-R31 Pair */
#define BGBCC_SH_REG_LR16		0x150
#define BGBCC_SH_REG_LR17		0x151
#define BGBCC_SH_REG_LR18		0x152
#define BGBCC_SH_REG_LR19		0x153
#define BGBCC_SH_REG_LR20		0x154
#define BGBCC_SH_REG_LR21		0x155
#define BGBCC_SH_REG_LR22		0x156
#define BGBCC_SH_REG_LR23		0x157
#define BGBCC_SH_REG_LR24		0x158
#define BGBCC_SH_REG_LR25		0x159
#define BGBCC_SH_REG_LR26		0x15A
#define BGBCC_SH_REG_LR27		0x15B
#define BGBCC_SH_REG_LR28		0x15C
#define BGBCC_SH_REG_LR29		0x15D
#define BGBCC_SH_REG_LR30		0x15E
#define BGBCC_SH_REG_LR31		0x15F		//Invalid

#endif


#define BGBCC_SH_REG_LR32		BGBCC_SH_REG_LR1
#define BGBCC_SH_REG_LR34		BGBCC_SH_REG_LR3
#define BGBCC_SH_REG_LR36		BGBCC_SH_REG_LR5
#define BGBCC_SH_REG_LR38		BGBCC_SH_REG_LR7
#define BGBCC_SH_REG_LR40		BGBCC_SH_REG_LR9
#define BGBCC_SH_REG_LR42		BGBCC_SH_REG_LR11
#define BGBCC_SH_REG_LR44		BGBCC_SH_REG_LR13
#define BGBCC_SH_REG_LR46		BGBCC_SH_REG_LR15
#define BGBCC_SH_REG_LR48		BGBCC_SH_REG_LR17
#define BGBCC_SH_REG_LR50		BGBCC_SH_REG_LR19
#define BGBCC_SH_REG_LR52		BGBCC_SH_REG_LR21
#define BGBCC_SH_REG_LR54		BGBCC_SH_REG_LR23
#define BGBCC_SH_REG_LR56		BGBCC_SH_REG_LR25
#define BGBCC_SH_REG_LR58		BGBCC_SH_REG_LR27
#define BGBCC_SH_REG_LR60		BGBCC_SH_REG_LR29
#define BGBCC_SH_REG_LR62		BGBCC_SH_REG_LR31


#define BGBCC_SH_REG_ARD0		0x160
#define BGBCC_SH_REG_ARD1		0x161
#define BGBCC_SH_REG_ARD2		0x162
#define BGBCC_SH_REG_ARD3		0x163
#define BGBCC_SH_REG_ARD4		0x164
#define BGBCC_SH_REG_ARD5		0x165
#define BGBCC_SH_REG_ARD6		0x166
#define BGBCC_SH_REG_ARD7		0x167
#define BGBCC_SH_REG_ARD8		0x168
#define BGBCC_SH_REG_ARD9		0x169
#define BGBCC_SH_REG_ARD10		0x16A
#define BGBCC_SH_REG_ARD11		0x16B
#define BGBCC_SH_REG_ARD12		0x16C
#define BGBCC_SH_REG_ARD13		0x16D
#define BGBCC_SH_REG_ARD14		0x16E
#define BGBCC_SH_REG_ARD15		0x16F

#define BGBCC_SH_REG_ARQ0		0x170
#define BGBCC_SH_REG_ARQ1		0x171
#define BGBCC_SH_REG_ARQ2		0x172
#define BGBCC_SH_REG_ARQ3		0x173
#define BGBCC_SH_REG_ARQ4		0x174
#define BGBCC_SH_REG_ARQ5		0x175
#define BGBCC_SH_REG_ARQ6		0x176
#define BGBCC_SH_REG_ARQ7		0x177
#define BGBCC_SH_REG_ARQ8		0x178
#define BGBCC_SH_REG_ARQ9		0x179
#define BGBCC_SH_REG_ARQ10		0x17A
#define BGBCC_SH_REG_ARQ11		0x17B
#define BGBCC_SH_REG_ARQ12		0x17C
#define BGBCC_SH_REG_ARQ13		0x17D
#define BGBCC_SH_REG_ARQ14		0x17E
#define BGBCC_SH_REG_ARQ15		0x17F


#define BGBCC_SH_REG_DLR	BGBCC_SH_REG_MACL	//Alias
#define BGBCC_SH_REG_DHR	BGBCC_SH_REG_MACH	//Alias

#define BGBCC_BJX2_FLIPSTNM


#define BGBCC_SH_LBL_ARCHREG(rn)	((CCXL_LBL_ARCHBASE)+(rn))

#define BGBCC_SH_ARCHREG_MACH		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_MACH)
#define BGBCC_SH_ARCHREG_MACL		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_MACL)
#define BGBCC_SH_ARCHREG_PR			BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_PR)
#define BGBCC_SH_ARCHREG_SGR		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_SGR)

#define BGBCC_SH_ARCHREG_FPUL		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_FPUL)
#define BGBCC_SH_ARCHREG_FPSCR		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_FPSCR)
#define BGBCC_SH_ARCHREG_PC			BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_PC)

#define BGBCC_SH_ARCHREG_TTB		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_TTB)
#define BGBCC_SH_ARCHREG_TEA		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_TEA)
#define BGBCC_SH_ARCHREG_MMCR		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_MMCR)
#define BGBCC_SH_ARCHREG_EXSR		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_EXSR)

#define BGBCC_SH_ARCHREG_DBR		BGBCC_SH_LBL_ARCHREG(BGBCC_SH_REG_DBR)


#define BGBCC_SH_LBL_ARCHSTRT		(CCXL_LBL_ARCHBASE+   0)
#define BGBCC_SH_LBL_ARCHEND		(CCXL_LBL_ARCHBASE+1024)

#define BGBCC_SH_LBL_TLSSTRT		(CCXL_LBL_ARCHBASE+1024)
#define BGBCC_SH_LBL_TLSEND			(CCXL_LBL_ARCHBASE+2048)


#define BGBCC_SH_NMID_UNK			0x0000	//Unknown
#define BGBCC_SH_NMID_MOV			0x0001	//MOV
#define BGBCC_SH_NMID_MOVB			0x0002	//MOV.B
#define BGBCC_SH_NMID_MOVW			0x0003	//MOV.W
#define BGBCC_SH_NMID_MOVL			0x0004	//MOV.L
#define BGBCC_SH_NMID_ADD			0x0005	//ADD
#define BGBCC_SH_NMID_ADDC			0x0006	//ADDC
#define BGBCC_SH_NMID_ADDV			0x0007	//ADDV
#define BGBCC_SH_NMID_SUB			0x0008	//SUB
#define BGBCC_SH_NMID_SUBC			0x0009	//SUBC
#define BGBCC_SH_NMID_SUBV			0x000A	//SUBV
#define BGBCC_SH_NMID_CMPHS			0x000B	//CMPHS
#define BGBCC_SH_NMID_CMPHI			0x000C	//CMPHI
#define BGBCC_SH_NMID_CMPEQ			0x000D	//CMPEQ
#define BGBCC_SH_NMID_CMPGE			0x000E	//CMPGE
#define BGBCC_SH_NMID_CMPGT			0x000F	//CMPGT
#define BGBCC_SH_NMID_JMP			0x0010	//JMP
#define BGBCC_SH_NMID_JSR			0x0011	//JSR
#define BGBCC_SH_NMID_BRA			0x0012	//BRA
#define BGBCC_SH_NMID_BSR			0x0013	//BSR
#define BGBCC_SH_NMID_BT			0x0014	//BT
#define BGBCC_SH_NMID_BF			0x0015	//BF
#define BGBCC_SH_NMID_BTS			0x0016	//BTS
#define BGBCC_SH_NMID_BFS			0x0017	//BFS
#define BGBCC_SH_NMID_DIV1			0x0018	//DIV1
#define BGBCC_SH_NMID_DMULU			0x0019	//DMULU
#define BGBCC_SH_NMID_DMULS			0x001A	//DMULS
#define BGBCC_SH_NMID_TST			0x001B	//TST
#define BGBCC_SH_NMID_AND			0x001C	//AND
#define BGBCC_SH_NMID_XOR			0x001D	//XOR
#define BGBCC_SH_NMID_OR			0x001E	//OR
#define BGBCC_SH_NMID_INVALID		0x001F	//Invalid
#define BGBCC_SH_NMID_DIV0S			0x0020	//
#define BGBCC_SH_NMID_CMPSTR		0x0021	//
#define BGBCC_SH_NMID_MULUW			0x0022	//
#define BGBCC_SH_NMID_MULSW			0x0023	//
#define BGBCC_SH_NMID_MACL			0x0024	//
#define BGBCC_SH_NMID_BSRF			0x0025	//
#define BGBCC_SH_NMID_BRAF			0x0026	//
#define BGBCC_SH_NMID_MULL			0x0027	//
#define BGBCC_SH_NMID_CLRT			0x0028	//
#define BGBCC_SH_NMID_SETT			0x0029	//
#define BGBCC_SH_NMID_CLRMAC		0x002A	//
#define BGBCC_SH_NMID_NOP			0x002B	//
#define BGBCC_SH_NMID_MOVT			0x002C	//
#define BGBCC_SH_NMID_RTS			0x002D	//
#define BGBCC_SH_NMID_SLEEP			0x002E	//
#define BGBCC_SH_NMID_RTE			0x002F	//
#define BGBCC_SH_NMID_SHLL			0x0030	//
#define BGBCC_SH_NMID_DT			0x0031	//
#define BGBCC_SH_NMID_SHAL			0x0032	//
#define BGBCC_SH_NMID_SHLR			0x0033	//
#define BGBCC_SH_NMID_CMPPZ			0x0034	//
#define BGBCC_SH_NMID_SHAR			0x0035	//
#define BGBCC_SH_NMID_ROTL			0x0036	//
#define BGBCC_SH_NMID_ROTCL			0x0037	//
#define BGBCC_SH_NMID_ROTT			0x0038	//
#define BGBCC_SH_NMID_ROTCR			0x0039	//
#define BGBCC_SH_NMID_SHLL2			0x003A	//
#define BGBCC_SH_NMID_ROTR			0x003B	//
#define BGBCC_SH_NMID_CMPPL			0x003C	//
#define BGBCC_SH_NMID_SHLL8			0x003D	//
#define BGBCC_SH_NMID_SHLL16		0x003E	//
#define BGBCC_SH_NMID_SHLR2			0x003F	//
#define BGBCC_SH_NMID_SHLR8			0x0040	//
#define BGBCC_SH_NMID_SHLR16		0x0041	//
#define BGBCC_SH_NMID_MACW			0x0042	//
#define BGBCC_SH_NMID_NOT			0x0043	//
#define BGBCC_SH_NMID_SWAPB			0x0044	//
#define BGBCC_SH_NMID_SWAPW			0x0045	//
#define BGBCC_SH_NMID_NEGC			0x0046	//
#define BGBCC_SH_NMID_NEG			0x0047	//
#define BGBCC_SH_NMID_EXTUB			0x0048	//
#define BGBCC_SH_NMID_EXTUW			0x0049	//
#define BGBCC_SH_NMID_EXTSB			0x004A	//
#define BGBCC_SH_NMID_EXTSW			0x004B	//
#define BGBCC_SH_NMID_TRAPA			0x004C	//
#define BGBCC_SH_NMID_MOVA			0x004D	//
#define BGBCC_SH_NMID_TSTB			0x004E	//
#define BGBCC_SH_NMID_DIV0U			0x004F	//
#define BGBCC_SH_NMID_LDC			0x0050	//
#define BGBCC_SH_NMID_LDCL			0x0051	//
#define BGBCC_SH_NMID_LDS			0x0052	//
#define BGBCC_SH_NMID_LDSL			0x0053	//
#define BGBCC_SH_NMID_STC			0x0054	//
#define BGBCC_SH_NMID_STCL			0x0055	//
#define BGBCC_SH_NMID_STS			0x0056	//
#define BGBCC_SH_NMID_STSL			0x0057	//
#define BGBCC_SH_NMID_CASL			0x0058	//
#define BGBCC_SH_NMID_TASB			0x0059	//
#define BGBCC_SH_NMID_XTRCT			0x005A	//
#define BGBCC_SH_NMID_ANDB			0x005B	//
#define BGBCC_SH_NMID_XORB			0x005C	//
#define BGBCC_SH_NMID_ORB			0x005D	//
#define BGBCC_SH_NMID_SHAD			0x005E	//
#define BGBCC_SH_NMID_SHLD			0x005F	//
#define BGBCC_SH_NMID_INVDLY		0x0060	//
#define BGBCC_SH_NMID_CLRS			0x0061	//
#define BGBCC_SH_NMID_SETS			0x0062	//
#define BGBCC_SH_NMID_MOVI20		0x0063	//MOVI20
#define BGBCC_SH_NMID_MOVI20S		0x0064	//MOVI20S
#define BGBCC_SH_NMID_MOVUB			0x0065	//MOVU.B
#define BGBCC_SH_NMID_MOVUW			0x0066	//MOVU.W
#define BGBCC_SH_NMID_MOVUL			0x0067	//MOVU.L
#define BGBCC_SH_NMID_LEAB			0x0068	//LEA.B
#define BGBCC_SH_NMID_LEAW			0x0069	//LEA.W
#define BGBCC_SH_NMID_LEAL			0x006A	//LEA.L
#define BGBCC_SH_NMID_LEAQ			0x006B	//LEA.Q
#define BGBCC_SH_NMID_LEAO			0x006C	//LEA.O
#define BGBCC_SH_NMID_NOTT			0x006D	//
#define BGBCC_SH_NMID_LDTLB			0x006E	//
#define BGBCC_SH_NMID_BRK			0x006F	//
#define BGBCC_SH_NMID_MOVRT			0x0070	//
#define BGBCC_SH_NMID_MOVCAL		0x0071	//
#define BGBCC_SH_NMID_PUSH			0x0072	//
#define BGBCC_SH_NMID_POP			0x0073	//
#define BGBCC_SH_NMID_ICLRMD		0x0074	//
#define BGBCC_SH_NMID_ISETMD		0x0075	//
#define BGBCC_SH_NMID_SHLL1			0x0076	//
#define BGBCC_SH_NMID_LDHF16		0x0077	//
#define BGBCC_SH_NMID_BRAN			0x0078	//BRA/N
#define BGBCC_SH_NMID_BSRN			0x0079	//BSR/N
#define BGBCC_SH_NMID_RTSN			0x007A	//
#define BGBCC_SH_NMID_LDIF16		0x007B	//
#define BGBCC_SH_NMID_STHF16		0x007C	//
#define BGBCC_SH_NMID_CSELT			0x007D	//
#define BGBCC_SH_NMID_EXTUL			0x007E	//
#define BGBCC_SH_NMID_EXTSL			0x007F	//

#define BGBCC_SH_NMID_FABS			0x0080	//
#define BGBCC_SH_NMID_FADD			0x0081	//
#define BGBCC_SH_NMID_FCMPEQ		0x0082	//
#define BGBCC_SH_NMID_FCMPGT		0x0083	//
#define BGBCC_SH_NMID_FCNVDS		0x0084	//
#define BGBCC_SH_NMID_FCNVSD		0x0085	//
#define BGBCC_SH_NMID_FDIV			0x0086	//
#define BGBCC_SH_NMID_FLDI0			0x0087	//
#define BGBCC_SH_NMID_FLDI1			0x0088	//
#define BGBCC_SH_NMID_FLDS			0x0089	//
#define BGBCC_SH_NMID_FLOAT			0x008A	//
#define BGBCC_SH_NMID_FMAC			0x008B	//
#define BGBCC_SH_NMID_FMOV			0x008C	//
#define BGBCC_SH_NMID_FMOVS			0x008D	//
#define BGBCC_SH_NMID_FMOVD			0x008E	//
#define BGBCC_SH_NMID_FMUL			0x008F	//

#define BGBCC_SH_NMID_FNEG			0x0090	//
#define BGBCC_SH_NMID_FSCHG			0x0091	//
#define BGBCC_SH_NMID_FSQRT			0x0092	//
#define BGBCC_SH_NMID_FSTS			0x0093	//
#define BGBCC_SH_NMID_FSUB			0x0094	//
#define BGBCC_SH_NMID_FTRC			0x0095	//
#define BGBCC_SH_NMID_FSRRA			0x0096	//
#define BGBCC_SH_NMID_FIPR			0x0097	//
#define BGBCC_SH_NMID_FTRV			0x0098	//
#define BGBCC_SH_NMID_PSETMD4		0x0099	//
#define BGBCC_SH_NMID_PSETMD12		0x009A	//
#define BGBCC_SH_NMID_FMOVX			0x009B	//
#define BGBCC_SH_NMID_FMOVIS		0x009C	//
#define BGBCC_SH_NMID_FMOVID		0x009D	//
#define BGBCC_SH_NMID_FMOVSI		0x009E	//
#define BGBCC_SH_NMID_FMOVDI		0x009F	//

#define BGBCC_SH_NMID_FLDCF			0x00A8	//
#define BGBCC_SH_NMID_FLDCD			0x00A9	//
#define BGBCC_SH_NMID_FLDCI			0x00AA	//
#define BGBCC_SH_NMID_FLDCH			0x00AB	//
#define BGBCC_SH_NMID_FSTCF			0x00AC	//
#define BGBCC_SH_NMID_FSTCD			0x00AD	//
#define BGBCC_SH_NMID_FSTCI			0x00AE	//
#define BGBCC_SH_NMID_FSTCH			0x00AF	//

#define BGBCC_SH_NMID_FRCPA			0x00B0	//
#define BGBCC_SH_NMID_FSQRTA		0x00B1	//
#define BGBCC_SH_NMID_FRCP			0x00B2	//
#define BGBCC_SH_NMID_SWCPLW		0x00B3	//
#define BGBCC_SH_NMID_SWCPMW		0x00B4	//
#define BGBCC_SH_NMID_SWCPHW		0x00B5	//
#define BGBCC_SH_NMID_SWAPMW		0x00B6	//
#define BGBCC_SH_NMID_SWAPHW		0x00B7	//
#define BGBCC_SH_NMID_SWAPL			0x00B8	//
#define BGBCC_SH_NMID_SWAPLW		0x00B9	//
#define BGBCC_SH_NMID_BSR2F			0x00BA	//BSRF, 32-bit align
#define BGBCC_SH_NMID_BRA2F			0x00BB	//BRAF, 32-bit align
#define BGBCC_SH_NMID_MOVDL			0x00BC	//MOVD.L
#define BGBCC_SH_NMID_RET			0x00BD	//
#define BGBCC_SH_NMID_PUSHX2		0x00BE	//
#define BGBCC_SH_NMID_POPX2			0x00BF	//

#define BGBCC_SH_NMID_MOVI			0x00C0	//
#define BGBCC_SH_NMID_MOVIV			0x00C1	//
#define BGBCC_SH_NMID_PREF			0x00C2	//
#define BGBCC_SH_NMID_OCBI			0x00C3	//
#define BGBCC_SH_NMID_OCBP			0x00C4	//
#define BGBCC_SH_NMID_OCBWB			0x00C5	//
#define BGBCC_SH_NMID_ICBI			0x00C6	//
#define BGBCC_SH_NMID_MOVQ			0x00C7	//MOV.Q
#define BGBCC_SH_NMID_ADDQ			0x00C8	//ADD
#define BGBCC_SH_NMID_SUBQ			0x00C9	//SUB
#define BGBCC_SH_NMID_MULQ			0x00CA	//SUB
#define BGBCC_SH_NMID_ANDQ			0x00CB	//SUB
#define BGBCC_SH_NMID_ORQ			0x00CC	//SUB
#define BGBCC_SH_NMID_XORQ			0x00CD	//SUB
#define BGBCC_SH_NMID_SHLLQ			0x00CE	//SUB
#define BGBCC_SH_NMID_SHLRQ			0x00CF	//SUB

#define BGBCC_SH_NMID_SHALQ			0x00D0	//SUB
#define BGBCC_SH_NMID_SHARQ			0x00D1	//SUB
#define BGBCC_SH_NMID_LDSH16		0x00D2	//SUB
#define BGBCC_SH_NMID_TSTQ			0x00D3	//SUB
#define BGBCC_SH_NMID_SHADQ			0x00D4	//
#define BGBCC_SH_NMID_SHLDQ			0x00D5	//
#define BGBCC_SH_NMID_SHLL4			0x00D6	//
#define BGBCC_SH_NMID_SHLR4			0x00D7	//
#define BGBCC_SH_NMID_BREQ			0x00D8	//
#define BGBCC_SH_NMID_BRNE			0x00D9	//
#define BGBCC_SH_NMID_BRGT			0x00DA	//
#define BGBCC_SH_NMID_BRLE			0x00DB	//
#define BGBCC_SH_NMID_BRGE			0x00DC	//
#define BGBCC_SH_NMID_BRLT			0x00DD	//
#define BGBCC_SH_NMID_ICLRMD_DQ		0x00DE	//
#define BGBCC_SH_NMID_ISETMD_DQ		0x00DF	//

#define BGBCC_SH_NMID_CMPQHS		0x00E0	//CMPQ/HS
#define BGBCC_SH_NMID_CMPQHI		0x00E1	//CMPQ/HI
#define BGBCC_SH_NMID_CMPQEQ		0x00E2	//CMPQ/EQ
#define BGBCC_SH_NMID_CMPQGE		0x00E3	//CMPQ/GE
#define BGBCC_SH_NMID_CMPQGT		0x00E4	//CMPQ/GT
#define BGBCC_SH_NMID_CMPQPZ		0x00E5	//CMPQ/PZ
#define BGBCC_SH_NMID_CMPQPL		0x00E6	//CMPQ/PL
#define BGBCC_SH_NMID_NOTS			0x00E7	//
#define BGBCC_SH_NMID_SHLL32		0x00E8	//
#define BGBCC_SH_NMID_SHLR32		0x00E9	//
#define BGBCC_SH_NMID_SHLR1			0x00EA	//
#define BGBCC_SH_NMID_SHAR1			0x00EB	//
#define BGBCC_SH_NMID_SHAR2			0x00EC	//
#define BGBCC_SH_NMID_SHAR4			0x00ED	//
#define BGBCC_SH_NMID_SHAR8			0x00EE	//
#define BGBCC_SH_NMID_SHAR16		0x00EF	//

#define BGBCC_SH_NMID_SHAR32		0x00F0	//
#define BGBCC_SH_NMID_LDSH8			0x00F1	//
#define BGBCC_SH_NMID_BRA8B			0x00F2	//
#define BGBCC_SH_NMID_NOP4B			0x00F3	//
#define BGBCC_SH_NMID_MOVNT			0x00F4	//
#define BGBCC_SH_NMID_CLZ			0x00F5	//
#define BGBCC_SH_NMID_CLZQ			0x00F6	//
#define BGBCC_SH_NMID_SWAP8B		0x00F7	//
#define BGBCC_SH_NMID_SWCPLB		0x00F8	//
#define BGBCC_SH_NMID_SWAPLB		0x00F9	//
#define BGBCC_SH_NMID_SWAPMB		0x00FA	//
#define BGBCC_SH_NMID_SWAPHB		0x00FB	//
#define BGBCC_SH_NMID_SWCPMB		0x00FC	//
#define BGBCC_SH_NMID_SWCPHB		0x00FD	//
#define BGBCC_SH_NMID_LDBF16		0x00FE	//
#define BGBCC_SH_NMID_STBF16		0x00FF	//

#define BGBCC_SH_NMID_ADDL			0x0100	//
#define BGBCC_SH_NMID_SUBL			0x0101	//
#define BGBCC_SH_NMID_PADDW			0x0102	//
#define BGBCC_SH_NMID_PADDL			0x0103	//
#define BGBCC_SH_NMID_PSUBW			0x0104	//
#define BGBCC_SH_NMID_PSUBL			0x0105	//
#define BGBCC_SH_NMID_PMULUW		0x0106	//
#define BGBCC_SH_NMID_MOVD			0x0107	//
#define BGBCC_SH_NMID_MOVHD			0x0108	//
#define BGBCC_SH_NMID_MOVLD			0x0109	//
#define BGBCC_SH_NMID_MOVHLD		0x010A	//
#define BGBCC_SH_NMID_MOVLHD		0x010B	//
#define BGBCC_SH_NMID_ADDSL			0x010C	//ADD
#define BGBCC_SH_NMID_ADDUL			0x010D	//ADD
#define BGBCC_SH_NMID_SUBSL			0x010E	//ADD
#define BGBCC_SH_NMID_SUBUL			0x010F	//ADD

#define BGBCC_SH_NMID_CMOVTB		0x0110	//CMOVT.B
#define BGBCC_SH_NMID_CMOVTW		0x0111	//CMOVT.W
#define BGBCC_SH_NMID_CMOVTL		0x0112	//CMOVT.L
#define BGBCC_SH_NMID_CMOVTQ		0x0113	//CMOVT.Q
#define BGBCC_SH_NMID_CMOVFB		0x0114	//CMOVF.B
#define BGBCC_SH_NMID_CMOVFW		0x0115	//CMOVF.W
#define BGBCC_SH_NMID_CMOVFL		0x0116	//CMOVF.L
#define BGBCC_SH_NMID_CMOVFQ		0x0117	//CMOVF.Q
#define BGBCC_SH_NMID_CMOVUTB		0x0118	//CMOVUT.B
#define BGBCC_SH_NMID_CMOVUTW		0x0119	//CMOVUT.W
#define BGBCC_SH_NMID_CMOVUTL		0x011A	//CMOVUT.L
#define BGBCC_SH_NMID_CMOVDTL		0x011B	//CMOVDT.L
#define BGBCC_SH_NMID_CMOVUFB		0x011C	//CMOVUF.B
#define BGBCC_SH_NMID_CMOVUFW		0x011D	//CMOVUF.W
#define BGBCC_SH_NMID_CMOVUFL		0x011E	//CMOVUF.L
#define BGBCC_SH_NMID_CMOVDFL		0x011F	//CMOVDF.L

// #define BGBCC_SH_NMID_XMOV			BGBCC_SH_NMID_MOVX2

#define BGBCC_SH_NMID_MOVX2			0x0120	//
#define BGBCC_SH_NMID_PADDH			0x0121	//
#define BGBCC_SH_NMID_PSUBH			0x0122	//
#define BGBCC_SH_NMID_PMULH			0x0123	//
#define BGBCC_SH_NMID_WEXMD			0x0124	//
#define BGBCC_SH_NMID_CPUID			0x0125	//
#define BGBCC_SH_NMID_RTSU			0x0126	//
#define BGBCC_SH_NMID_SYSCALL		0x0127	//
#define BGBCC_SH_NMID_INVIC			0x0128	//
#define BGBCC_SH_NMID_INVDC			0x0129	//
#define BGBCC_SH_NMID_INVTLB		0x012A	//
#define BGBCC_SH_NMID_JLDI			0x012B	//
#define BGBCC_SH_NMID_MULUL			0x012C	//MULU.L
#define BGBCC_SH_NMID_MULSL			0x012D	//MULS.L
#define BGBCC_SH_NMID_BRA2B			0x012E	//BRA (16-bit)
#define BGBCC_SH_NMID_BRA4B			0x012F	//BRA (32-bit)

#define BGBCC_SH_NMID_FLDCFH		0x0130	//
#define BGBCC_SH_NMID_FSTCFH		0x0131	//
#define BGBCC_SH_NMID_RGB5SHR1		0x0132	//
#define BGBCC_SH_NMID_PMULSW		0x0133	//
#define BGBCC_SH_NMID_PMULULW		0x0134	//
#define BGBCC_SH_NMID_PMULSLW		0x0135	//
#define BGBCC_SH_NMID_PMULUHW		0x0136	//
#define BGBCC_SH_NMID_PMULSHW		0x0137	//
#define BGBCC_SH_NMID_RGB5PCK32		0x0138	//
#define BGBCC_SH_NMID_RGB5PCK64		0x0139	//
#define BGBCC_SH_NMID_RGB5UPCK32	0x013A	//
#define BGBCC_SH_NMID_RGB5UPCK64	0x013B	//
#define BGBCC_SH_NMID_RGB32PCK64	0x013C	//
#define BGBCC_SH_NMID_RGB32UPCK64	0x013D	//
#define BGBCC_SH_NMID_PSHUFB		0x013E	//
#define BGBCC_SH_NMID_PSHUFW		0x013F	//

#define BGBCC_SH_NMID_PADDF			0x0140	//
#define BGBCC_SH_NMID_PSUBF			0x0141	//
#define BGBCC_SH_NMID_PMULF			0x0142	//
#define BGBCC_SH_NMID_PADDFX		0x0143	//
#define BGBCC_SH_NMID_PSUBFX		0x0144	//
#define BGBCC_SH_NMID_PMULFX		0x0145	//
#define BGBCC_SH_NMID_PSHUFL		0x0146	//
#define BGBCC_SH_NMID_PSHUFXL		0x0147	//
#define BGBCC_SH_NMID_CTZ			0x0148	//
#define BGBCC_SH_NMID_CTZQ			0x0149	//
#define BGBCC_SH_NMID_BTRNS			0x014A	//
#define BGBCC_SH_NMID_BTRNSQ		0x014B	//
#define BGBCC_SH_NMID_PMORTL		0x014C	//
#define BGBCC_SH_NMID_PMORTQ		0x014D	//
#define BGBCC_SH_NMID_MOVP			0x014E	//MOV.P
#define BGBCC_SH_NMID_LEAP			0x014F	//LEA.P

#define BGBCC_SH_NMID_PADDXD		0x0150	//
#define BGBCC_SH_NMID_PSUBXD		0x0151	//
#define BGBCC_SH_NMID_PMULXD		0x0152	//
#define BGBCC_SH_NMID_MOVQ_DISP		0x0153	//MOV.Q, explicit displacement
#define BGBCC_SH_NMID_PCSELTW		0x0154	//
#define BGBCC_SH_NMID_PCSELTL		0x0155	//
#define BGBCC_SH_NMID_PCMPEQW		0x0156	//
#define BGBCC_SH_NMID_PCMPEQL		0x0157	//
#define BGBCC_SH_NMID_PCMPHIW		0x0158	//
#define BGBCC_SH_NMID_PCMPHIL		0x0159	//
#define BGBCC_SH_NMID_PCMPGTW		0x015A	//
#define BGBCC_SH_NMID_PCMPGTL		0x015B	//
#define BGBCC_SH_NMID_PCMPEQH		0x015C	//
#define BGBCC_SH_NMID_PCMPEQF		0x015D	//
#define BGBCC_SH_NMID_PCMPGTH		0x015E	//
#define BGBCC_SH_NMID_PCMPGTF		0x015F	//

#define BGBCC_SH_NMID_SHLL64		0x0160	//
#define BGBCC_SH_NMID_SHLR64		0x0161	//
#define BGBCC_SH_NMID_FADDX			0x0162	//
#define BGBCC_SH_NMID_FSUBX			0x0163	//
#define BGBCC_SH_NMID_FMULX			0x0164	//
#define BGBCC_SH_NMID_FMACX			0x0165	//
#define BGBCC_SH_NMID_FCMPXEQ		0x0166	//
#define BGBCC_SH_NMID_FCMPXGT		0x0167	//
#define BGBCC_SH_NMID_FLDCDX		0x0168	//
#define BGBCC_SH_NMID_FSTCDX		0x0169	//
#define BGBCC_SH_NMID_FLDCIX		0x016A	//
#define BGBCC_SH_NMID_FSTCIX		0x016B	//
#define BGBCC_SH_NMID_SHADX			0x016C	//
#define BGBCC_SH_NMID_SHLDX			0x016D	//
#define BGBCC_SH_NMID_SHARX			0x016E	//
#define BGBCC_SH_NMID_SHLRX			0x016F	//

#define BGBCC_SH_NMID_ADDX			0x0170	//
#define BGBCC_SH_NMID_SUBX			0x0171	//
#define BGBCC_SH_NMID_ADCX			0x0172	//
#define BGBCC_SH_NMID_SBBX			0x0173	//
#define BGBCC_SH_NMID_ROTLX			0x0174	//
#define BGBCC_SH_NMID_ANDX			0x0175	//
#define BGBCC_SH_NMID_ORX			0x0176	//
#define BGBCC_SH_NMID_XORX			0x0177	//
#define BGBCC_SH_NMID_CMPXEQ		0x0178	//
#define BGBCC_SH_NMID_CMPXHI		0x0179	//
#define BGBCC_SH_NMID_CMPXGT		0x017A	//
#define BGBCC_SH_NMID_MOVQ_DISP24	0x017B	//MOV.Q, explicit 24b displacement
#define BGBCC_SH_NMID_BLKUTX1		0x017C	//
#define BGBCC_SH_NMID_BLKUTX2		0x017D	//
#define BGBCC_SH_NMID_BLKUTX3H		0x017E	//
#define BGBCC_SH_NMID_BLKUTX3L		0x017F	//

#define BGBCC_SH_NMID_BLINTW		0x0180	//
#define BGBCC_SH_NMID_BLERPW		0x0181	//
#define BGBCC_SH_NMID_BLINTAW		0x0182	//
#define BGBCC_SH_NMID_PSTCH			0x0183	//
#define BGBCC_SH_NMID_PLDCH			0x0184	//
#define BGBCC_SH_NMID_PLDCHH		0x0185	//
#define BGBCC_SH_NMID_BLKUAB1		0x0186	//
#define BGBCC_SH_NMID_BLKUAB2		0x0187	//
#define BGBCC_SH_NMID_PLDCM8SH		0x0188	//
#define BGBCC_SH_NMID_PLDCM8UH		0x0189	//
#define BGBCC_SH_NMID_PSTCM8SH		0x018A	//
#define BGBCC_SH_NMID_PSTCM8UH		0x018B	//
#define BGBCC_SH_NMID_BRAB			0x018C	//
#define BGBCC_SH_NMID_BSRB			0x018D	//
#define BGBCC_SH_NMID_BTB			0x018E	//
#define BGBCC_SH_NMID_BFB			0x018F	//

#define BGBCC_SH_NMID_BRAL			0x0190	//
#define BGBCC_SH_NMID_BSRL			0x0191	//
#define BGBCC_SH_NMID_BTL			0x0192	//
#define BGBCC_SH_NMID_BFL			0x0193	//
#define BGBCC_SH_NMID_PSCHEQW		0x0194	//
#define BGBCC_SH_NMID_PSCHEQB		0x0195	//
#define BGBCC_SH_NMID_PSCHNEW		0x0196	//
#define BGBCC_SH_NMID_PSCHNEB		0x0197	//
#define BGBCC_SH_NMID_CONVFXI		0x0198	//
#define BGBCC_SH_NMID_CONVFLI		0x0199	//
#define BGBCC_SH_NMID_SNIPEDC		0x019A	//
#define BGBCC_SH_NMID_SNIPEIC		0x019B	//
#define BGBCC_SH_NMID_LDACL			0x019C	//
#define BGBCC_SH_NMID_FADDG			0x019D	//
#define BGBCC_SH_NMID_FSUBG			0x019E	//
#define BGBCC_SH_NMID_FMULG			0x019F	//

#define BGBCC_SH_NMID_LDEKRR		0x01A0	//
#define BGBCC_SH_NMID_SVEKRR		0x01A1	//
#define BGBCC_SH_NMID_LDEKEY		0x01A2	//
#define BGBCC_SH_NMID_LDEENC		0x01A3	//
#define BGBCC_SH_NMID_PLDCEHL		0x01A4	//
#define BGBCC_SH_NMID_PLDCEHH		0x01A5	//
#define BGBCC_SH_NMID_FMOVH			0x01A6	//
#define BGBCC_SH_NMID_MOVC			0x01A7	//
#define BGBCC_SH_NMID_BRGTU			0x01A8	//
#define BGBCC_SH_NMID_BRLEU			0x01A9	//
#define BGBCC_SH_NMID_BRGEU			0x01AA	//
#define BGBCC_SH_NMID_BRLTU			0x01AB	//
#define BGBCC_SH_NMID_CMPTAEQ		0x01AC	//
#define BGBCC_SH_NMID_CMPTAHI		0x01AD	//
#define BGBCC_SH_NMID_CMPTAHS		0x01AE	//
#define BGBCC_SH_NMID_CMPTTEQ		0x01AF	//

#define BGBCC_SH_NMID_XMOVB			0x01B0	//XMOV.B
#define BGBCC_SH_NMID_XMOVW			0x01B1	//XMOV.W
#define BGBCC_SH_NMID_XMOVL			0x01B2	//XMOV.L
#define BGBCC_SH_NMID_XMOVQ			0x01B3	//XMOV.Q
#define BGBCC_SH_NMID_XMOVUB		0x01B4	//XMOVU.B
#define BGBCC_SH_NMID_XMOVUW		0x01B5	//XMOVU.W
#define BGBCC_SH_NMID_XMOVUL		0x01B6	//XMOVU.L
#define BGBCC_SH_NMID_XMOVX2		0x01B7	//XMOV.X
#define BGBCC_SH_NMID_XMOVP			0x01B8	//XMOV.P
#define BGBCC_SH_NMID_MOVC_DISP24	0x01B9	//MOV.C, explicit 24b displacement
#define BGBCC_SH_NMID_XJMP			0x01BA	//XJMP
#define BGBCC_SH_NMID_XJSR			0x01BB	//XJSR
#define BGBCC_SH_NMID_MACSL			0x01BC	//
#define BGBCC_SH_NMID_MACUL			0x01BD	//
#define BGBCC_SH_NMID_DMACSL		0x01BE	//
#define BGBCC_SH_NMID_DMACUL		0x01BF	//

#define BGBCC_SH_NMID_BREQL			0x01C0	//
#define BGBCC_SH_NMID_BRNEL			0x01C1	//
#define BGBCC_SH_NMID_BRGTL			0x01C2	//
#define BGBCC_SH_NMID_BRLEL			0x01C3	//
#define BGBCC_SH_NMID_BRGEL			0x01C4	//
#define BGBCC_SH_NMID_BRLTL			0x01C5	//
#define BGBCC_SH_NMID_MOVTT			0x01C6	//
#define BGBCC_SH_NMID_XMOVTT		0x01C7	//
#define BGBCC_SH_NMID_BRGTUL		0x01C8	//
#define BGBCC_SH_NMID_BRLEUL		0x01C9	//
#define BGBCC_SH_NMID_BRGEUL		0x01CA	//
#define BGBCC_SH_NMID_BRLTUL		0x01CB	//
#define BGBCC_SH_NMID_XLEAB			0x01CC	//XLEA.B
#define BGBCC_SH_NMID_XLEAW			0x01CD	//XLEA.W
#define BGBCC_SH_NMID_XLEAL			0x01CE	//XLEA.L
#define BGBCC_SH_NMID_XLEAQ			0x01CF	//XLEA.Q

#define BGBCC_SH_NMID_MULSQ			0x01D0	//
#define BGBCC_SH_NMID_MULUQ			0x01D1	//
#define BGBCC_SH_NMID_DIVSQ			0x01D2	//
#define BGBCC_SH_NMID_DIVUQ			0x01D3	//
#define BGBCC_SH_NMID_MODSQ			0x01D4	//
#define BGBCC_SH_NMID_MODUQ			0x01D5	//
#define BGBCC_SH_NMID_FDIVX			0x01D6	//
#define BGBCC_SH_NMID_LDTEX			0x01D7	//
#define BGBCC_SH_NMID_DIVSL			0x01D8	//
#define BGBCC_SH_NMID_DIVUL			0x01D9	//
#define BGBCC_SH_NMID_MODSL			0x01DA	//
#define BGBCC_SH_NMID_MODUL			0x01DB	//
#define BGBCC_SH_NMID_ROTCLQ		0x01DC	//
#define BGBCC_SH_NMID_ROTCRQ		0x01DD	//
#define BGBCC_SH_NMID_BCDADC		0x01DE	//
#define BGBCC_SH_NMID_BCDSBB		0x01DF	//

#define BGBCC_SH_NMID_BCDADD		0x01E0	//
#define BGBCC_SH_NMID_BCDSUB		0x01E1	//
#define BGBCC_SH_NMID_BCDADDX		0x01E2	//
#define BGBCC_SH_NMID_BCDSUBX		0x01E3	//
#define BGBCC_SH_NMID_PADDFA		0x01E4	//
#define BGBCC_SH_NMID_PSUBFA		0x01E5	//
#define BGBCC_SH_NMID_PMULFA		0x01E6	//
#define BGBCC_SH_NMID_PADDFAX		0x01E7	//
#define BGBCC_SH_NMID_PSUBFAX		0x01E8	//
#define BGBCC_SH_NMID_PMULFAX		0x01E9	//
#define BGBCC_SH_NMID_LDIZ			0x01EA	//
#define BGBCC_SH_NMID_LDIN			0x01EB	//
#define BGBCC_SH_NMID_LDHF8S		0x01EC	//
#define BGBCC_SH_NMID_LDHF8U		0x01ED	//
#define BGBCC_SH_NMID_STHF8S		0x01EE	//
#define BGBCC_SH_NMID_STHF8U		0x01EF	//

#define BGBCC_SH_NMID_JIMM			0x01F0	//
#define BGBCC_SH_NMID_JOP64			0x01F1	//
#define BGBCC_SH_NMID_LDIHI			0x01F2	//
#define BGBCC_SH_NMID_LDIHIQ		0x01F3	//
#define BGBCC_SH_NMID_CMPNANTTEQ	0x01F4	//
#define BGBCC_SH_NMID_SETTRAP		0x01F5	//
#define BGBCC_SH_NMID_MULHSQ		0x01F6	//
#define BGBCC_SH_NMID_MULHUQ		0x01F7	//
#define BGBCC_SH_NMID_BNDCHKB		0x01F8	//
#define BGBCC_SH_NMID_BNDCHKW		0x01F9	//
#define BGBCC_SH_NMID_BNDCHKL		0x01FA	//
#define BGBCC_SH_NMID_BNDCHKQ		0x01FB	//
#define BGBCC_SH_NMID_EXTUTT		0x01FC	//
#define BGBCC_SH_NMID_FCMPGE		0x01FD	//
#define BGBCC_SH_NMID_BITSEL		0x01FE	//
#define BGBCC_SH_NMID_BITSELX		0x01FF	//

#define BGBCC_SH_NMID_FADDA			0x0200	//
#define BGBCC_SH_NMID_FSUBA			0x0201	//
#define BGBCC_SH_NMID_FMULA			0x0202	//
#define BGBCC_SH_NMID_PADDXDA		0x0203	//
#define BGBCC_SH_NMID_PSUBXDA		0x0204	//
#define BGBCC_SH_NMID_PMULXDA		0x0205	//
#define BGBCC_SH_NMID_VSKG			0x0206	//
#define BGBCC_SH_NMID_VSKC			0x0207	//
#define BGBCC_SH_NMID_BNDCHK		0x0208	//
#define BGBCC_SH_NMID_BNDCMP		0x0209	//
#define BGBCC_SH_NMID_RSUBSL		0x020A	//RSUB
#define BGBCC_SH_NMID_RSUBUL		0x020B	//RSUB
#define BGBCC_SH_NMID_RSUB			0x020C	//RSUB
#define BGBCC_SH_NMID_ANDL			0x020D	//AND
#define BGBCC_SH_NMID_ORL			0x020E	//OR
#define BGBCC_SH_NMID_XORL			0x020F	//XOR

#define BGBCC_SH_NMID_ANDW			0x0210	//AND
#define BGBCC_SH_NMID_ORW			0x0211	//OR
#define BGBCC_SH_NMID_XORW			0x0212	//XOR
#define BGBCC_SH_NMID_SWAPQ			0x0213	//XOR
#define BGBCC_SH_NMID_ADDSB			0x0214	//RSUB
#define BGBCC_SH_NMID_ADDUB			0x0215	//RSUB
#define BGBCC_SH_NMID_SUBSB			0x0216	//RSUB
#define BGBCC_SH_NMID_SUBUB			0x0217	//RSUB
#define BGBCC_SH_NMID_ADDSW			0x0218	//RSUB
#define BGBCC_SH_NMID_ADDUW			0x0219	//RSUB
#define BGBCC_SH_NMID_SUBSW			0x021A	//RSUB
#define BGBCC_SH_NMID_SUBUW			0x021B	//RSUB
#define BGBCC_SH_NMID_RSUBSB		0x021C	//RSUB
#define BGBCC_SH_NMID_RSUBUB		0x021D	//RSUB
#define BGBCC_SH_NMID_RSUBSW		0x021E	//RSUB
#define BGBCC_SH_NMID_RSUBUW		0x021F	//RSUB

#define BGBCC_SH_NMID_PCVTSB2HL		0x0220	//Packed Convert
#define BGBCC_SH_NMID_PCVTUB2HL		0x0221	//
#define BGBCC_SH_NMID_PCVTSB2HH		0x0222	//
#define BGBCC_SH_NMID_PCVTUB2HH		0x0223	//
#define BGBCC_SH_NMID_PCVTSW2FL		0x0224	//
#define BGBCC_SH_NMID_PCVTUW2FL		0x0225	//
#define BGBCC_SH_NMID_PCVTSW2FH		0x0226	//
#define BGBCC_SH_NMID_PCVTUW2FH		0x0227	//
#define BGBCC_SH_NMID_PCVTH2SB		0x0228	//
#define BGBCC_SH_NMID_PCVTH2UB		0x0229	//
#define BGBCC_SH_NMID_PCVTSW2H		0x022A	//
#define BGBCC_SH_NMID_PCVTUW2H		0x022B	//
#define BGBCC_SH_NMID_PCVTF2SW		0x022C	//
#define BGBCC_SH_NMID_PCVTF2UW		0x022D	//
#define BGBCC_SH_NMID_PCVTH2SW		0x022E	//
#define BGBCC_SH_NMID_PCVTH2UW		0x022F	//

#define BGBCC_SH_NMID_PSQRTAH		0x0230	//
#define BGBCC_SH_NMID_PSQRTUAH		0x0231	//
#define BGBCC_SH_NMID_PSQRTAF		0x0232	//
#define BGBCC_SH_NMID_PSQRTUAF		0x0233	//
#define BGBCC_SH_NMID_PRCPAH		0x0234	//
#define BGBCC_SH_NMID_PRELUH		0x0235	//
#define BGBCC_SH_NMID_PRCPAF		0x0236	//
#define BGBCC_SH_NMID_PRELUF		0x0237	//
#define BGBCC_SH_NMID_LEATB			0x0238	//LEAT.B
#define BGBCC_SH_NMID_LEATW			0x0239	//LEAT.W
#define BGBCC_SH_NMID_LEATL			0x023A	//LEAT.L
#define BGBCC_SH_NMID_LEATQ			0x023B	//LEAT.Q
#define BGBCC_SH_NMID_BNDCMPB		0x023C	//BNDCMP.B
#define BGBCC_SH_NMID_BNDCMPW		0x023D	//BNDCMP.W
#define BGBCC_SH_NMID_BNDCMPL		0x023E	//BNDCMP.L
#define BGBCC_SH_NMID_BNDCMPQ		0x023F	//BNDCMP.Q

#define BGBCC_SH_NMID_PSTCXH		0x0240	//
#define BGBCC_SH_NMID_PLDCXH		0x0241	//
#define BGBCC_SH_NMID_REGCHKG		0x0242	//
#define BGBCC_SH_NMID_REGCHKC		0x0243	//
#define BGBCC_SH_NMID_MULUX			0x0244	//
#define BGBCC_SH_NMID_MULHUX		0x0245	//
#define BGBCC_SH_NMID_DIVUX			0x0246	//
#define BGBCC_SH_NMID_MODUX			0x0247	//
#define BGBCC_SH_NMID_MOVST			0x0248	//
#define BGBCC_SH_NMID_XMOVST		0x0249	//
#define BGBCC_SH_NMID_KEYBRK_XG2	0x024A	//
#define BGBCC_SH_NMID_KEYBRK_BASE	0x024B	//
#define BGBCC_SH_NMID_CMPPEQ		0x024C	//MOV.P
#define BGBCC_SH_NMID_CMPPGT		0x024D	//MOV.P
#define BGBCC_SH_NMID_CMPPGE		0x024E	//MOV.P
#define BGBCC_SH_NMID_RGB5MINMAX	0x024F	//

#define BGBCC_SH_NMID_PCVTH2AL		0x0250	//
#define BGBCC_SH_NMID_PCVTAL2H		0x0251	//
#define BGBCC_SH_NMID_RGB5CCENC1	0x0252	//
#define BGBCC_SH_NMID_RGB5CCENC2	0x0253	//
#define BGBCC_SH_NMID_SUBP			0x0254	//
#define BGBCC_SH_NMID_SUBXP			0x0255	//
#define BGBCC_SH_NMID_CMPPEQX		0x0256	//
#define BGBCC_SH_NMID_CMPPGTX		0x0257	//
#define BGBCC_SH_NMID_MOVTW			0x0258	//
#define BGBCC_SH_NMID_MOVUTW		0x0259	//
#define BGBCC_SH_NMID_MOVHTW		0x025A	//
#define BGBCC_SH_NMID_XMOV			0x025B
#define BGBCC_SH_NMID_MOVTW_V		0x025C	//Virtual
#define BGBCC_SH_NMID_MOVUTW_V		0x025D	//Virtual
#define BGBCC_SH_NMID_MOVHTW_V		0x025E	//Virtual
#define BGBCC_SH_NMID_BSWAPQ		0x025F	//Byte Swap QWORD (Virtual)

#define BGBCC_SH_NMID_BSWAPW		0x0260	//Byte Swap WORD (Virtual)
#define BGBCC_SH_NMID_BSWAPUW		0x0261	//Byte Swap WORD (Virtual)
#define BGBCC_SH_NMID_BSWAPL		0x0262	//Byte Swap DWORD (Virtual)
#define BGBCC_SH_NMID_BSWAPUL		0x0263	//Byte Swap DWORD (Virtual)
#define BGBCC_SH_NMID_MIN			0x0264	//
#define BGBCC_SH_NMID_MAX			0x0265	//
#define BGBCC_SH_NMID_FMIN			0x0266	//
#define BGBCC_SH_NMID_FMAX			0x0267	//
#define BGBCC_SH_NMID_CMPQNE		0x0268	//CMPQNE
#define BGBCC_SH_NMID_FLDCIU		0x0269	//
#define BGBCC_SH_NMID_FLDCISL		0x026A	//
#define BGBCC_SH_NMID_FLDCIUL		0x026B	//
#define BGBCC_SH_NMID_CMPQLT		0x026C	//CMPQLT
#define BGBCC_SH_NMID_CMPQLE		0x026D	//CMPQLE
#define BGBCC_SH_NMID_LDIMI			0x026E	//
#define BGBCC_SH_NMID_XBLESS		0x026F	//

#define BGBCC_SH_NMID_BRTSTL		0x0270	//
#define BGBCC_SH_NMID_BRTSTQ		0x0271	//
#define BGBCC_SH_NMID_BRTSTNL		0x0272	//
#define BGBCC_SH_NMID_BRTSTNQ		0x0273	//
#define BGBCC_SH_NMID_PSHALW		0x0274	//
#define BGBCC_SH_NMID_PSHLLW		0x0275	//
#define BGBCC_SH_NMID_PSHARW		0x0276	//
#define BGBCC_SH_NMID_PSHLRW		0x0277	//
#define BGBCC_SH_NMID_RGB5PCKI8		0x0278	//
#define BGBCC_SH_NMID_RGB5UPCKI8	0x0279	//
#define BGBCC_SH_NMID_BITNN			0x027A	//
#define BGBCC_SH_NMID_PMULF8H		0x027B	//
#define BGBCC_SH_NMID_MOVVL			0x027C	//EXCHL
#define BGBCC_SH_NMID_MOVVQ			0x027D	//EXCHL
#define BGBCC_SH_NMID_SWAPVL		0x027E	//EXCHL
#define BGBCC_SH_NMID_SWAPVQ		0x027F	//CMPQLE

#define BGBCC_SH_NMID_PCVTHTOF8		0x0280	//
#define BGBCC_SH_NMID_PCVTF8TOH		0x0281	//
#define BGBCC_SH_NMID_NTST			0x0282	//NTST
#define BGBCC_SH_NMID_RVJ21I		0x0283	//
#define BGBCC_SH_NMID_MOVHW			0x0284	//
#define BGBCC_SH_NMID_MOVLW			0x0285	//
#define BGBCC_SH_NMID_MOVHLW		0x0286	//
#define BGBCC_SH_NMID_MOVLHW		0x0287	//
#define BGBCC_SH_NMID_RVJ21O		0x0288	//
#define BGBCC_SH_NMID_RVJ22			0x0289	//
#define BGBCC_SH_NMID_LDSH32		0x028A	//
#define BGBCC_SH_NMID_MOVX_ST		0x028B	//MOV.X / SD
#define BGBCC_SH_NMID_MOVB_ST		0x028C	//MOV.B / SB
#define BGBCC_SH_NMID_MOVW_ST		0x028D	//MOV.W / SH
#define BGBCC_SH_NMID_MOVL_ST		0x028E	//MOV.L / SW
#define BGBCC_SH_NMID_MOVQ_ST		0x028F	//MOV.Q / SD

#define BGBCC_SH_NMID_PDIVF			0x0290	//
#define BGBCC_SH_NMID_PSQRTF		0x0291	//
#define BGBCC_SH_NMID_PMINF			0x0292	//
#define BGBCC_SH_NMID_PMAXF			0x0293	//
#define BGBCC_SH_NMID_FCMPLT		0x0294	//
#define BGBCC_SH_NMID_PCMPLTF		0x0295	//
#define BGBCC_SH_NMID_FCMPLE		0x0296	//
#define BGBCC_SH_NMID_PCMPLEF		0x0297	//
#define BGBCC_SH_NMID_CSRRW			0x0298	//
#define BGBCC_SH_NMID_CSRRS			0x0299	//
#define BGBCC_SH_NMID_CSRRC			0x029A	//
#define BGBCC_SH_NMID_CSRRWI		0x029B	//
#define BGBCC_SH_NMID_CSRRSI		0x029C	//
#define BGBCC_SH_NMID_CSRRCI		0x029D	//
#define BGBCC_SH_NMID_CSRR			0x029E	//
#define BGBCC_SH_NMID_CSRW			0x029F	//

#define BGBCC_SH_NMID_FSGNJS		0x02A0	//
#define BGBCC_SH_NMID_FSGNJNS		0x02A1	//
#define BGBCC_SH_NMID_FSGNJXS		0x02A2	//
#define BGBCC_SH_NMID_FSGNJD		0x02A3	//
#define BGBCC_SH_NMID_FSGNJND		0x02A4	//
#define BGBCC_SH_NMID_FSGNJXD		0x02A5	//
#define BGBCC_SH_NMID_RGB5SH3		0x02A6	//
#define BGBCC_SH_NMID_RGB5USH3		0x02A7	//
#define BGBCC_SH_NMID_BITMOV		0x02A8	//
#define BGBCC_SH_NMID_BITMOVX		0x02A9	//
#define BGBCC_SH_NMID_BITMOVS		0x02AA	//
#define BGBCC_SH_NMID_BITMOVSX		0x02AB	//
#define BGBCC_SH_NMID_PMULTW		0x02AC	//
#define BGBCC_SH_NMID_PMULTXL		0x02AD	//
#define BGBCC_SH_NMID_PDIVH			0x02AE	//
#define BGBCC_SH_NMID_PSQRTH		0x02AF	//


#define BGBCC_SH_NMID_BLKUVF1VL		0x02B0	//
#define BGBCC_SH_NMID_BLKUVF1VH		0x02B1	//
#define BGBCC_SH_NMID_BLKUVF1SL		0x02B2	//
#define BGBCC_SH_NMID_BLKUVF1SH		0x02B3	//
#define BGBCC_SH_NMID_FDIVG			0x02B4	//
#define BGBCC_SH_NMID_FMOVQ			0x02B5	//
#define BGBCC_SH_NMID_PCVTH2F8A		0x02B6	//
#define BGBCC_SH_NMID_PCVTF8A2H		0x02B7	//

#define BGBCC_SH_NMID_JIMM52		0x02B8	//
#define BGBCC_SH_NMID_JOP96			0x02B9	//

#define BGBCC_SH_NMID_FADDF			0x02BA	//
#define BGBCC_SH_NMID_FSUBF			0x02BB	//
#define BGBCC_SH_NMID_FMULF			0x02BC	//
#define BGBCC_SH_NMID_FDIVF			0x02BD	//
#define BGBCC_SH_NMID_FSQRTF		0x02BE	//


#define BGBCC_SH_NMID_MOVZT			BGBCC_SH_NMID_MOVTT
#define BGBCC_SH_NMID_XMOVZT		BGBCC_SH_NMID_XMOVTT

#define BGBCC_SH_NMID_AUIPC			BGBCC_SH_NMID_MOVI20
#define BGBCC_SH_NMID_LUI			BGBCC_SH_NMID_MOVI20S



#define BGBCC_SH_FMID_REGREG		0x01	//Rm, Rn
#define BGBCC_SH_FMID_REGRM			0x02	//Rm
#define BGBCC_SH_FMID_REGRN			0x03	//Rn
#define BGBCC_SH_FMID_IMMREG		0x04	//Imm, Rn
#define BGBCC_SH_FMID_REGLDABS		0x05	//@(Abs), Rn
#define BGBCC_SH_FMID_REGST			0x06	//Rm, @Rn
#define BGBCC_SH_FMID_REGLD			0x07	//@Rm, Rn
#define BGBCC_SH_FMID_REGDECST		0x08	//Rm, @-Rn
#define BGBCC_SH_FMID_REGINCLD		0x09	//@Rm+, Rn
#define BGBCC_SH_FMID_REGSTR0N		0x0A	//Rm, @(Ro+Rn)
#define BGBCC_SH_FMID_REGLDR0M		0x0B	//@(Ro+Rm), Rn
#define BGBCC_SH_FMID_REGSTDISP		0x0C	//Rm, @(Rn+Disp)
#define BGBCC_SH_FMID_REGLDDISP		0x0D	//@(Rm+Disp), Rn
#define BGBCC_SH_FMID_ABS			0x0E	//@(Abs)
#define BGBCC_SH_FMID_NONE			0x0F	//-

#define BGBCC_SH_FMID_IMM			0x10	//Imm
#define BGBCC_SH_FMID_LDREG			0x11	//@Rm
#define BGBCC_SH_FMID_STREG			0x12	//@Rn
#define BGBCC_SH_FMID_IMMSTRMN		0x13	//Imm, @(Rm+Rn)
#define BGBCC_SH_FMID_REGVIMM		0x14	//<Imm>, Rn
#define BGBCC_SH_FMID_FREGREG		0x15	//FRm, FRn
#define BGBCC_SH_FMID_FREGRM		0x16	//FRm
#define BGBCC_SH_FMID_FREGRN		0x17	//FRn
#define BGBCC_SH_FMID_DREGREG		0x18	//FRm, FRn
#define BGBCC_SH_FMID_DREGRM		0x19	//FRm
#define BGBCC_SH_FMID_DREGRN		0x1A	//FRn
#define BGBCC_SH_FMID_LABEL			0x1B	//<Lbl>
#define BGBCC_SH_FMID_LBLREG		0x1C	//<Lbl>, Rn
#define BGBCC_SH_FMID_REGREGREG		0x1D	//Rn, Rm, Ro
#define BGBCC_SH_FMID_REGINCST		0x1E	//Rm, @+Rn
#define BGBCC_SH_FMID_REGDECLD		0x1F	//@Rm-, Rn

#define BGBCC_SH_FMID_REGSTRODISP	0x20	//Rm, @(Rn,Ro,Disp)
#define BGBCC_SH_FMID_REGLDRODISP	0x21	//@(Rm,Ro,Disp), Rn
#define BGBCC_SH_FMID_REGIMMREG		0x22	//Rm, Imm, Rn
#define BGBCC_SH_FMID_FREGREGREG	0x23	//FRm, FRo, FRn
#define BGBCC_SH_FMID_DREGREGREG	0x24	//DRm, DRo, DRn
#define BGBCC_SH_FMID_REGLBL		0x25	//Rn, <Lbl>
#define BGBCC_SH_FMID_FREGST		0x26	//FRm, @Rn
#define BGBCC_SH_FMID_FREGLD		0x27	//@Rm, FRn
#define BGBCC_SH_FMID_FREGDECST		0x28	//FRm, @-Rn
#define BGBCC_SH_FMID_FREGINCLD		0x29	//@Rm+, FRn
#define BGBCC_SH_FMID_FREGSTR0N		0x2A	//FRm, @(Ro+Rn)
#define BGBCC_SH_FMID_FREGLDR0M		0x2B	//@(Ro+Rm), FRn
#define BGBCC_SH_FMID_FREGSTDISP	0x2C	//FRm, @(Rn+Disp)
#define BGBCC_SH_FMID_FREGLDDISP	0x2D	//@(Rm+Disp), FRn
#define BGBCC_SH_FMID_FREGSTRODISP	0x2E	//FRm, @(Rn,Ro,Disp)
#define BGBCC_SH_FMID_FREGLDRODISP	0x2F	//@(Rm,Ro,Disp), FRn

#define BGBCC_SH_FMID_REG1ABS		0x30	//Rn, @(Abs)
#define BGBCC_SH_FMID_REG2ABS		0x31	//Rm, Rn, @(Abs)
#define BGBCC_SH_FMID_REGREGREGREG	0x32	//Rm, Ro, Rp, Rn
#define BGBCC_SH_FMID_REGREGIMMREG	0x33	//Rm, Ro, Imm, Rn
#define BGBCC_SH_FMID_REGREGREGIMM	0x34	//Rm, Ro, Rn, Imm
#define BGBCC_SH_FMID_REGREGLBL		0x35	//Rm, Rn, <Lbl>
#define BGBCC_SH_FMID_DREGST		0x36	//DRm, @Rn
#define BGBCC_SH_FMID_DREGLD		0x37	//@Rm, DRn
#define BGBCC_SH_FMID_DREGDECST		0x38	//DRm, @-Rn
#define BGBCC_SH_FMID_DREGINCLD		0x39	//@Rm+, DRn
#define BGBCC_SH_FMID_DREGSTR0N		0x3A	//DRm, @(Ro+Rn)
#define BGBCC_SH_FMID_DREGLDR0M		0x3B	//@(Ro+Rm), DRn
#define BGBCC_SH_FMID_DREGSTDISP	0x3C	//DRm, @(Rn+Disp)
#define BGBCC_SH_FMID_DREGLDDISP	0x3D	//@(Rm+Disp), DRn
#define BGBCC_SH_FMID_DREGSTRODISP	0x3E	//DRm, @(Rn,Ro,Disp)
#define BGBCC_SH_FMID_DREGLDRODISP	0x3F	//@(Rm,Ro,Disp), DRn

#define BGBCC_SH_FMID_REGIMMREGREG	0x40	//Rm, Imm, Rp, Rn
#define BGBCC_SH_FMID_REGREG55A		0x41	//Rm, Rn (16-bit, 2R)
#define BGBCC_SH_FMID_REGREGB		0x42	//Rm, Rn (32-bit 2R)
#define BGBCC_SH_FMID_REGIMM_10		0x44	//Imm10, Rn (32-bit)
#define BGBCC_SH_FMID_REGIMM_10_N	0x45	//Imm10, Rn (32-bit)
#define BGBCC_SH_FMID_REGSTSPVIMM	0x46	//Rn, (SP,Disp4)
#define BGBCC_SH_FMID_REGLDSPVIMM	0x47	//(SP,Disp4), Rn
#define BGBCC_SH_FMID_REGKVIMM_U	0x48	//Imm4u, Rk
#define BGBCC_SH_FMID_REGKVIMM_N	0x49	//Imm4n, Rk
#define BGBCC_SH_FMID_REGSTRON		0x4A	//Rm, @(Ro+Rn)
#define BGBCC_SH_FMID_REGLDROM		0x4B	//@(Ro+Rm), Rn
#define BGBCC_SH_FMID_REGSTDISP5	0x4C	//Rm, @(Rn+Disp5)
#define BGBCC_SH_FMID_REGLDDISP5	0x4D	//@(Rm+Disp5), Rn
#define BGBCC_SH_FMID_PCDISP20		0x4E	//(PC,Disp20s)
#define BGBCC_SH_FMID_PCDISP8		0x4F	//(PC,Disp8s)

#define BGBCC_SH_FMID_IMM12A_U			0x50	//Imm12u (16-bit)
#define BGBCC_SH_FMID_IMM12A_N			0x51	//Imm12n (16-bit)
#define BGBCC_SH_FMID_REGIMM8S			0x52	//Imm8s, Rn (16-bit)
#define BGBCC_SH_FMID_REGIMM16S			0x53	//Imm16u, Rn (32-bit)
#define BGBCC_SH_FMID_REGVIMM_N			0x54	//Imm4n, Rn (16-bit)
#define BGBCC_SH_FMID_REGRON			0x55	//Ro as Rn
#define BGBCC_SH_FMID_IMM24_U			0x56	//Imm
#define BGBCC_SH_FMID_IMM24_N			0x57	//Imm
#define BGBCC_SH_FMID_REGIMM16_U		0x58	//Imm16u, Rn (32-bit)
#define BGBCC_SH_FMID_REGIMM16_N		0x59	//Imm16n, Rn (32-bit)
#define BGBCC_SH_FMID_REGR0REG			0x5A	//Rm, R0, Rn (16-bit)
#define BGBCC_SH_FMID_IMM5RN			0x5B	//Rn as Imm5 (16-bit)
#define BGBCC_SH_FMID_REGSTDISP3		0x5C	//Rm, @(Rn+Disp3) (16-bit)
#define BGBCC_SH_FMID_REGLDDISP3		0x5D	//@(Rm+Disp3), Rn (16-bit)
#define BGBCC_SH_FMID_REGSTGBRDISP10	0x5E	//Rn, @(GBR,Disp)
#define BGBCC_SH_FMID_REGLDGBRDISP10	0x5F	//@(GBR,Disp), Rn


#define BGBCC_SH_FMID_REGIMM5REG		0x60	//Rn, Imm5u, Ro
#define BGBCC_SH_FMID_REGIMMREG_8S		0x61	//Rn, Imm8s, Ro
#define BGBCC_SH_FMID_REGIMMREG_N		0x62	//Rn, Imm9n, Ro
#define BGBCC_SH_FMID_PCDISP8REG		0x63	//(PC,Disp8s), Rn

#define BGBCC_SH_FMID_REGSTGBRDISP10N	0x64	//Rn, @(GBR,Disp)
#define BGBCC_SH_FMID_REGLDGBRDISP10N	0x65	//@(GBR,Disp), Rn

#define BGBCC_SH_FMID_PCDISP11REG		0x66	//(PC,Disp11s), Rn
#define BGBCC_SH_FMID_REGLDGBRDISP16	0x67	//(GBR,Disp16), Rn

#define BGBCC_SH_FMID_REGIMMREG_US		0x68	//Rm, Imm9us, Rn
#define BGBCC_SH_FMID_REGREGIMM_8S		0x69	//Rm, Rn, Imm8s

#define BGBCC_SH_FMID_REGIMM			0x6A	//Rn, Imm
#define BGBCC_SH_FMID_REGREGIMM			0x6B	//Rm, Rn, Imm



#define BGBCC_SH_FMID_ISRV				0x80
#define BGBCC_SH_FMID_REGREGREG_RV		\
	(BGBCC_SH_FMID_REGREGREG|BGBCC_SH_FMID_ISRV)
#define BGBCC_SH_FMID_REGIMMREG_RV		\
	(BGBCC_SH_FMID_REGIMMREG|BGBCC_SH_FMID_ISRV)

#define BGBCC_SH_FMID_REGSTDISP_RV		\
	(BGBCC_SH_FMID_REGSTDISP|BGBCC_SH_FMID_ISRV)
#define BGBCC_SH_FMID_REGLDDISP_RV		\
	(BGBCC_SH_FMID_REGLDDISP|BGBCC_SH_FMID_ISRV)

#define BGBCC_SH_FMID_REGREGREGREG_RV		\
	(BGBCC_SH_FMID_REGREGREGREG|BGBCC_SH_FMID_ISRV)

#define BGBCC_SH_FMID_REGSTRON_RV		\
	(BGBCC_SH_FMID_REGSTRON|BGBCC_SH_FMID_ISRV)
#define BGBCC_SH_FMID_REGLDROM_RV		\
	(BGBCC_SH_FMID_REGLDROM|BGBCC_SH_FMID_ISRV)

#define BGBCC_SH_FMID_PCDISP20_RV		\
	(BGBCC_SH_FMID_PCDISP20|BGBCC_SH_FMID_ISRV)

#define BGBCC_SH_FMID_IMM20REG_RV		\
	(BGBCC_SH_FMID_IMM24_U|BGBCC_SH_FMID_ISRV)

#define BGBCC_SH_FMID_REGREGDISP_RV		\
	(BGBCC_SH_FMID_REGREGIMM_8S|BGBCC_SH_FMID_ISRV)

#define BGBCC_SH_FMID_IMM16REG_RV		\
	(BGBCC_SH_FMID_REGIMM16_U|BGBCC_SH_FMID_ISRV)

#define BGBCC_SH_FMID_IMM24_RV		\
	(BGBCC_SH_FMID_IMM24_N|BGBCC_SH_FMID_ISRV)

#define BGBCC_SH_FMID_NONE_RV		\
	(BGBCC_SH_FMID_NONE|BGBCC_SH_FMID_ISRV)


#define BGBCC_SH_FMID_REGREG5_RVC		\
	(BGBCC_SH_FMID_REGREG|BGBCC_SH_FMID_ISRV)
#define BGBCC_SH_FMID_REGREG3_RVC		\
	(BGBCC_SH_FMID_FREGREG|BGBCC_SH_FMID_ISRV)

#define BGBCC_SH_FMID_IMM6REG5_RVC		\
	(BGBCC_SH_FMID_IMMREG|BGBCC_SH_FMID_ISRV)
#define BGBCC_SH_FMID_IMM6REG3_RVC		\
	(BGBCC_SH_FMID_REGIMM8S|BGBCC_SH_FMID_ISRV)

#define BGBCC_SH_FMID_REGIMMREG3_RVC	\
	(BGBCC_SH_FMID_DREGREG|BGBCC_SH_FMID_ISRV)

#define BGBCC_SH_FMID_REG3LD_RVC	\
	(BGBCC_SH_FMID_REGLD|BGBCC_SH_FMID_ISRV)
#define BGBCC_SH_FMID_REG3ST_RVC	\
	(BGBCC_SH_FMID_REGST|BGBCC_SH_FMID_ISRV)

#define BGBCC_SH_FMID_REG5SPLD_RVC	\
	(BGBCC_SH_FMID_REGINCLD|BGBCC_SH_FMID_ISRV)
#define BGBCC_SH_FMID_REG5SPST_RVC	\
	(BGBCC_SH_FMID_REGDECST|BGBCC_SH_FMID_ISRV)


#define BGBCC_SH_OPVTY_NONE			0x00	//None
#define BGBCC_SH_OPVTY_IMM			0x01	//#Imm
#define BGBCC_SH_OPVTY_REG			0x02	//Reg
#define BGBCC_SH_OPVTY_NAME			0x03	//Name
#define BGBCC_SH_OPVTY_DRREG		0x04	//@Reg
#define BGBCC_SH_OPVTY_DRREGI		0x05	//@Reg+
#define BGBCC_SH_OPVTY_DRREGD		0x06	//@-Reg

#define BGBCC_SH_OPVTY_RRMEM		0x08	//@(Reg,Reg)
#define BGBCC_SH_OPVTY_RDMEM		0x09	//@(Reg,Disp)

#define BGBCC_SH_RLC_REL8			0x01	//Relative BYTE (xx)
#define BGBCC_SH_RLC_REL16			0x02	//Relative WORD (xxxx)
#define BGBCC_SH_RLC_REL32			0x03	//Relative DWORD (xxxx_xxxx)
#define BGBCC_SH_RLC_ABS8			0x04	//Absolute BYTE (Low 8 bits)
#define BGBCC_SH_RLC_ABS16			0x05	//Absolute WORD (Low 16 bits)
#define BGBCC_SH_RLC_ABS32			0x06	//Absolute DWORD
#define BGBCC_SH_RLC_ABS64			0x07	//Absolute QWORD
#define BGBCC_SH_RLC_RELW12			0x08	//Relative Low 12 bits (WORD)
											//Oxxx
#define BGBCC_SH_RLC_RELW8			0x09	//Relative Low 8 bit (WORD)
											//OOxx
#define BGBCC_SH_RLC_REL32B			0x0A	//Relative DWORD (Reverse)

#define BGBCC_SH_RLC_RELW12L		0x0B	//Relative Low 12 bits (DWORD)
#define BGBCC_SH_RLC_RELW8L			0x0C	//Relative Low 8 bit (DWORD)

#define BGBCC_SH_RLC_REL20_2A		0x0D	//Relative 20 bit (BYTE, SH2A)
#define BGBCC_SH_RLC_RELW16_BJX		0x0E	//Relative 16 bit (WORD, BJX1)
											//OOxx_OOxx
#define BGBCC_SH_RLC_RELW20_BJX		0x0F	//Relative 20 bit (WORD, BJX1)
											//OOxx_Oxxx
#define BGBCC_SH_RLC_REL24_BJX		0x10	//Relative 24 bit (BYTE, BJX1)
											//OOxx_xxxx
#define BGBCC_SH_RLC_REL24B_BJX		0x11	//Relative 24 bit (BYTE, BJX1, Rev)
											//OOxx_xxxx
#define BGBCC_SH_RLC_RVA32			0x12	//RVA (DWORD)
#define BGBCC_SH_RLC_RELW24_BJX		0x13	//Relative 24 bit (WORD, BJX1)
											//OOxx_xxxx

#define BGBCC_SH_RLC_PBO24_BJX		0x14	//PBO 24 bit (BYTE, BJX2)
											//OOxx_xxxx
#define BGBCC_SH_RLC_PBO32_BJX		0x15	//PBO 24 bit (BYTE, BJX2)
											//OOxx_xxxx_OOxx
#define BGBCC_SH_RLC_TBR24_BJX		0x16	//TBR 24 bit (BYTE, BJX2)
											//OOxx_xxxx
#define BGBCC_SH_RLC_TBR12_BJX		0x17	//TBR 12 bit (BYTE, BJX2)

#define BGBCC_SH_RLC_RELW16C_BSR	0x18	//Relative 16 bit (BYTE, BSR1)
											//OOxx_OOxx
#define BGBCC_SH_RLC_RELW16_BSR		0x19	//Relative 16 bit (WORD, BSR1)
											//OOxx_OOxx
#define BGBCC_SH_RLC_RELW24C_BSR	0x1A	//Relative 24 bit (BYTE, BSR1)
											//OOxx_OOxx_OOxx
#define BGBCC_SH_RLC_RELW24_BSR		0x1B	//Relative 24 bit (WORD, BSR1)
											//OOxx_OOxx_OOxx

#define BGBCC_SH_RLC_ABSW16A_BSR	0x1C	//Absolute BYTE (Low 16 bits)
#define BGBCC_SH_RLC_ABSW24A_BSR	0x1D	//Absolute BYTE (Low 24 bits)
#define BGBCC_SH_RLC_ABSW32A_BSR	0x1E	//Absolute BYTE
#define BGBCC_SH_RLC_RELW8_BSR		0x1F	//Relative Low 8 bit (WORD)

#define BGBCC_SH_RLC_RELW16D_BSR	0x20	//Relative 16 bit (WORD, BSR1)
											//Oxxx_OOOx
#define BGBCC_SH_RLC_RELW24D_BSR	0x21	//Relative 24 bit (WORD, BSR1)
											//Oxxx_OOxx_OOOx
#define BGBCC_SH_RLC_RELW32D_BSR	0x22	//Relative 24 bit (WORD, BSR1)
											//Oxxx_OOxx_OOxx_OOOx

#define BGBCC_SH_RLC_RELW32C_BSR	0x23	//Relative 32 bit (BYTE, BSR1)
											//OOxx_OOxx_OOxx_OOxx

#define BGBCC_SH_RLC_ABSW16B_BSR	0x24	//Absolute BYTE
											//Oxxx_OOOx
#define BGBCC_SH_RLC_ABSW24B_BSR	0x25	//Absolute BYTE
											//Oxxx_OOxx_OOOx
#define BGBCC_SH_RLC_ABSW32B_BSR	0x26	//Absolute BYTE
											//Oxxx_OOxx_OOxx_OOOx

#define BGBCC_SH_RLC_RELW12_BSR		0x27	//Relative Low 12 bits (WORD)

#define BGBCC_SH_RLC_RELW16A_BSR	0x28	//Relative 16 bit (BYTE, BSR1)
											//Oxxx_OOOx
#define BGBCC_SH_RLC_RELW24A_BSR	0x29	//Relative 24 bit (BYTE, BSR1)
											//Oxxx_OOxx_OOOx
#define BGBCC_SH_RLC_RELW32A_BSR	0x2A	//Relative 24 bit (BYTE, BSR1)
											//Oxxx_OOxx_OOxx_OOOx

//#define BGBCC_SH_RLC_PBOJ27_BJX		0x2C	//PBO Jumbo 27 bit (BYTE, BJX2)
											//F4xx_Cxxx_F0nm_OexO
//#define BGBCC_SH_RLC_PBOJ31_BJX		0x2D	//PBO Jumbo 31 bit (BYTE, BJX2)
											//F4xx_Cxxx_F1nm_Oexx
//#define BGBCC_SH_RLC_RELJ27_BJX		0x2E	//Relative Jumbo 27 bit (BYTE, BJX2)
											//F4xx_Cxxx_F0nm_OexO
//#define BGBCC_SH_RLC_RELJ31_BJX		0x2F	//Relative Jumbo 31 bit (BYTE, BJX2)
											//F4xx_Cxxx_F1nm_Oexx

#define BGBCC_SH_RLC_PBO9_BJX		0x2B	//PBO Disp9 (BYTE, BJX2)

#define BGBCC_SH_RLC_PBOJ29_BJX		0x2C	//PBO Jumbo 29 bit (BYTE, BJX2)
#define BGBCC_SH_RLC_PBOJ32_BJX		0x2D	//PBO Jumbo 32 bit (BYTE, BJX2)
#define BGBCC_SH_RLC_RELJ29_BJX		0x2E	//Relative Jumbo 29 bit (BYTE, BJX2)
#define BGBCC_SH_RLC_RELJ32_BJX		0x2F	//Relative Jumbo 32 bit (BYTE, BJX2)

#define BGBCC_SH_RLC_TRIPWIRE_BJX	0x30	//Tripwire Location

#define BGBCC_SH_RLC_RELB13_OP24	0x31	//Relative 13 bit (BYTE, BJX2)
#define BGBCC_SH_RLC_ABS48_BJX		0x32	//Abs48, BYTE, FEjj_jjjj_FAjj_jjjj

#define BGBCC_SH_RLC_RVA24			0x33	//RVA (24-bit)

#define BGBCC_SH_RLC_RELW12_RVI		0x34	//RISC-V, 12-bit (BEQ/etc)
#define BGBCC_SH_RLC_RELW20_RVI		0x35	//RISC-V, 20-bit (JAL)

#define BGBCC_SH_RLC_ABS96			0x36	//Absolute 96-bit

#define BGBCC_SH_RLC_REL32UI_RVI	0x37	//RISC-V, 20+12 PC-Rel

#define BGBCC_SH_RLC_RELW8_BJCMP	0x38	//JCMPxx (WORD)
#define BGBCC_SH_RLC_RELW32_BJCMP	0x39	//JCMPxx (WORD, Jumbo)

#define BGBCC_SH_RLC_ABSHI20_RVI	0x3A	//RISC-V, High 12 bits, Abs
#define BGBCC_SH_RLC_ABSLO12I_RVI	0x3B	//RISC-V, Low 12-bits I
#define BGBCC_SH_RLC_ABSLO12S_RVI	0x3C	//RISC-V, Low 12-bits I

#define BGBCC_SH_RLC_RELHI20_RVI	0x3D	//RISC-V, High 12 bits, Abs
#define BGBCC_SH_RLC_RELLO12I_RVI	0x3E	//RISC-V, Low 12-bits I
#define BGBCC_SH_RLC_RELLO12S_RVI	0x3F	//RISC-V, Low 12-bits I

#define BGBCC_SH_RLC_RELW11_BJCMP	0x40	//JCMPxx (WORD)
#define BGBCC_SH_RLC_RELW33_BJCMP	0x41	//JCMPxx (WORD)

#define BGBCC_SH_RLC_PBOQ16_BJX		0x42	//GBR+Disp16

#define BGBCC_SH_RLC_SECTOKEN		0x43	//Absolute 96-bit


#define BGBCC_SH_RLC_PBO32_RVI		0x44	//GBR+Disp32 (RV LUI+ADDI)
#define BGBCC_SH_RLC_PBO32J_RVI		0x45	//GBR+Disp32 (RV J21+ADDI)

#define BGBCC_SH_RLC_PBO32LD_RVI	0x46	//GBR+Disp32 (RV LUI+ADD+Ld)
#define BGBCC_SH_RLC_PBO32ST_RVI	0x47	//GBR+Disp32 (RV LUI+ADD+St)
#define BGBCC_SH_RLC_PBO32STJ_RVI	0x48	//GBR+Disp32 (RV J21+St)
#define BGBCC_SH_RLC_RELW33J_RVI	0x49	//RV, 33-bit (J21+BEQ/etc)

#define BGBCC_SH_RLC_RELW10_XG3		0x4A	//Bxx (DWORD, XG3)
#define BGBCC_SH_RLC_RELW23_XG3		0x4B	//Jxx (DWORD, XG3)

#define BGBCC_SH_RLC_RELB33_XG3		0x4C	//PC-Rel Jumbo 33 (BYTE, XG3)
#define BGBCC_SH_RLC_RELW33_XG3		0x4D	//PC-Rel Jumbo 33 (WORD, XG3)
#define BGBCC_SH_RLC_PBOJ33_XG3		0x4E	//GBR+Disp33 (XG3)


// #define BGBCC_SH_RLC_ABSW48A_BSR	0x20	//Absolute BYTE
// #define BGBCC_SH_RLC_ABSW64A_BSR	0x21	//Absolute BYTE


#define BGBCC_SH_CSEG_TEXT		0x00		//.text section
#define BGBCC_SH_CSEG_STRTAB	0x01		//.strtab section
#define BGBCC_SH_CSEG_RODATA	0x02		//.rodata section
#define BGBCC_SH_CSEG_GOT		0x03		//.got section
#define BGBCC_SH_CSEG_UTEXT		0x04		//.utext section
#define BGBCC_SH_CSEG_UDATA		0x05		//.udata section

#define BGBCC_SH_CSEG_DATA		0x06		//.data section
#define BGBCC_SH_CSEG_BSS		0x07		//.bss section
#define BGBCC_SH_CSEG_RELOC		0x08		//.reloc section

// #define BGBCC_SH_CSEG_DYN		0x07		//dynamic sections
#define BGBCC_SH_CSEG_DYN		0x10		//dynamic sections

#define BGBCC_SH_CSEG_ABS		0x7F		//absolute address

#define BGBCC_SH_REGCLS_NONE	0
#define BGBCC_SH_REGCLS_GR		1	//uses a GPR
#define BGBCC_SH_REGCLS_GR2		2	//uses a pair of GPRs
#define BGBCC_SH_REGCLS_FR		3	//uses a FR
#define BGBCC_SH_REGCLS_FR2		4	//uses a pair of FRs

#define BGBCC_SH_REGCLS_VO_REF	5	//value object, pass by-ref
#define BGBCC_SH_REGCLS_VO_GR	6	//value object pass in GPR
#define BGBCC_SH_REGCLS_VO_GR2	7	//value object pass in GPR pair
#define BGBCC_SH_REGCLS_AR_REF	8	//array object, pass by-ref
// #define BGBCC_SH_REGCLS_PTR		9	//Pointer
#define BGBCC_SH_REGCLS_QGR		9	//Quad GPR
#define BGBCC_SH_REGCLS_VO_QGR	10	//value object pass in Quad GPR
#define BGBCC_SH_REGCLS_VO_QGR2	11	//value object pass in Quad GPR pair
#define BGBCC_SH_REGCLS_WGR		12	//Uses GPR, 16-bit storage

#define BGBCC_SH_REGCLS_DR		13	//uses a FR

#define BGBCC_SH_REGCLS_QGR2	14	//uses a pair of GPRs

#define BGBCC_SH_REGCLS_VO_REF2	16	//value object, pass by-ref, pair
#define BGBCC_SH_REGCLS_AR_REF2	17	//array object, pass by-ref, pair


#define BGBCC_SH_FPSCR_DN		0x00040000	//
#define BGBCC_SH_FPSCR_PR		0x00080000	//
#define BGBCC_SH_FPSCR_SZ		0x00100000	//
#define BGBCC_SH_FPSCR_FR		0x00200000	//
#define BGBCC_SH_FPSCR_VE		0x01000000	//

#define BGBCC_SH_SRFL_DQ		0x00001000	//64-bit mode (data)
#define BGBCC_SH_SRFL_JQ		0x80000000	//64-bit mode (address)

#define BGBCC_SH_MAX_CACHEVAR 5

#define BGBCC_SH_MAX_CACHEFPVAR 4



#define BGBCC_SHX_GenLabelTemp(ctx)		\
	BGBCC_SHX_GenLabelTempLLn(ctx, __FILE__, __LINE__)
#define BGBCC_SHX_GenLabel(ctx)		\
	BGBCC_SHX_GenLabelLLn(ctx, __FILE__, __LINE__)

#define BGBCC_SHX_GETLREG_LO(reg)		(BGBCC_SH_REG_R0+((reg)&31))
#define BGBCC_SHX_GETLREG_HI(reg)		(BGBCC_SH_REG_R0+(((reg)&31)+1))

#define	BGBCC_JX2CC_PSREG_ARG(ix)	\
	BGBCC_JX2C_GetRqRegForArgumentIndex(ctx, sctx, ix)
#define	BGBCC_JX2CC_PSREG_RQARG(ix)	\
	BGBCC_JX2C_GetRqRegForArgumentIndex(ctx, sctx, ix)
#define	BGBCC_JX2CC_PSREG_RDARG(ix)	\
	BGBCC_JX2C_GetRdRegForArgumentIndex(ctx, sctx, ix)

#define	BGBCC_JX2CC_PSREG_LRARG(ix)	\
	BGBCC_JX2C_GetLrRegForArgumentIndex(ctx, sctx, ix)

#define	BGBCC_JX2CC_PSREG_ARGTMP(ix)	\
	BGBCC_JX2C_GetRqRegForArgTempIndex(ctx, sctx, ix)

#define	BGBCC_JX2CC_PSREG_RBRET			BGBCC_JX2C_GetRdRegReturn(ctx, sctx)
#define	BGBCC_JX2CC_PSREG_RDRET			BGBCC_JX2C_GetRdRegReturn(ctx, sctx)
#define	BGBCC_JX2CC_PSREG_RQRET			BGBCC_JX2C_GetRqRegReturn(ctx, sctx)
#define	BGBCC_JX2CC_PSREG_LRRET			BGBCC_JX2C_GetLrRegReturn(ctx, sctx)

#define	BGBCC_JX2CC_PSREG_RQTHIS		BGBCC_JX2C_GetRqRegThis(ctx, sctx)
#define	BGBCC_JX2CC_PSREG_LRTHIS		BGBCC_JX2C_GetLrRegThis(ctx, sctx)

#define	BGBCC_JX2CC_PSREG_STRUCTRET		BGBCC_JX2C_GetRqRegStructReturn(ctx, sctx)

#define	BGBCC_JX2CC_PSREG_TS0		BGBCC_JX2C_GetRegTempScratch(ctx, sctx, 0)
#define	BGBCC_JX2CC_PSREG_TS1		BGBCC_JX2C_GetRegTempScratch(ctx, sctx, 1)

#define	BGBCC_JX2CC_PSREG_RTSLR		BGBCC_JX2C_GetRtsLr(ctx, sctx)
#define	BGBCC_JX2CC_PSREG_ALTLR		BGBCC_JX2C_GetAltLr(ctx, sctx)

#define	BGBCC_JX2CC_PSREG_TS0F		BGBCC_JX2C_GetRegTempFpScratch(ctx, sctx, 0)
#define	BGBCC_JX2CC_PSREG_TS1F		BGBCC_JX2C_GetRegTempFpScratch(ctx, sctx, 1)

#if 0
typedef struct BGBCC_SHX_Context_s BGBCC_SHX_Context;
typedef struct BGBCC_SHX_OpcodeArg_s BGBCC_SHX_OpcodeArg;
typedef struct BGBCC_SHX_VarSpan_s BGBCC_SHX_VarSpan;
typedef struct BGBCC_SHX_VarSpan2_s BGBCC_SHX_VarSpan2;

typedef struct BGBCC_SHX_EmitQueueOp_s BGBCC_SHX_EmitQueueOp;
#endif

#if 1
typedef struct BGBCC_CMG_Context_s BGBCC_SHX_Context;
typedef struct BGBCC_CMG_OpcodeArg_s BGBCC_SHX_OpcodeArg;
typedef struct BGBCC_CMG_VarSpan_s BGBCC_SHX_VarSpan;
typedef struct BGBCC_CMG_VarSpan2_s BGBCC_SHX_VarSpan2;

typedef struct BGBCC_CMG_EmitQueueOp_s BGBCC_SHX_EmitQueueOp;
#endif
