//AHSRC:tkgl_api/ragl_barfarray.c
RASWGL_BARF_RenderArray *RASWGL_BARF_AllocRenderArray();
RASWGL_BARF_RenderContext *RASWGL_BARF_AllocRenderContext();
void RASWGL_BARF_CheckExpandContextArrays(RASWGL_BARF_RenderContext *ctx);
RASWGL_BARF_RenderArray *RASWGL_BARF_GetRenderArrayForTexture(RASWGL_BARF_RenderContext *ctx, int texnum);
void RASWGL_BARF_ResetContextArrays(RASWGL_BARF_RenderContext *ctx);
void RASWGL_BARF_CheckExpandArrayTriangles(RASWGL_BARF_RenderArray *arr, int ntris);
void RASWGL_BARF_UpdateArrayVBO(RASWGL_BARF_RenderArray *arr);
void RASWGL_BARF_UpdateContextArrayVBOs(RASWGL_BARF_RenderContext *ctx);
void raswgl_barf_copyArrayXYZ(raswgl_barf_xyzfloat *dst, int nvec,int vsize, int vtype, int vstep, void *src);
void raswgl_barf_copyArrayST(raswgl_barf_stfloat *dst, int nvec,int vsize, int vtype, int vstep, void *src);
u32 raswgl_barf_Float3ToNvFloat(float x, float y, float z);
u32 raswgl_barf_UByte3ToNvFloat(int x, int y, int z);
u32 raswgl_barf_SByte3ToNvFloat(int x, int y, int z);
void raswgl_barf_copyArrayNorm(raswgl_barf_nvfloat *dst, int nvec,int vsize, int vtype, int vstep, void *src);
raswgl_barf_clrfloat raswgl_barf_float2clrfloat(float val);
raswgl_barf_clrfloat raswgl_barf_halffloat2clrfloat(u16 val);
raswgl_barf_clrfloat raswgl_barf_ubyte2clrfloat(int val);
raswgl_barf_clrfloat raswgl_barf_sbyte2clrfloat(int val);
void raswgl_barf_copyArrayRGBA(raswgl_barf_clrfloat *dst, int nvec,int vsize, int vtype, int vstep, void *src, int vsize2, int vtype2, int vstep2, void *src2);
void RASWGL_BARF_ArraysEmitTriangles(RASWGL_BARF_RenderArray *arr, int ntris, int xyzsize, int xyztype, int xyzstep, void *xyz,  int stsize, int sttype, int ststep, void *st,  int normsize, int normtype, int normstep, void *norm, int xnormsize, int xnormtype, int xnormstep, void *xnorm, int ynormsize, int ynormtype, int ynormstep, void *ynorm, int rgbsize, int rgbtype, int rgbstep, void *rgb, int srgbsize, int srgbtype, int srgbstep, void *srgb, int vrgbsize, int vrgbtype, int vrgbstep, void *vrgb, int trgbsize, int trgbtype, int trgbstep, void *trgb);
void *raswgl_barf_arrayIndexOffset(int base,int vsize, int vtype, int *rvstep, void *vec);
void RASWGL_BARF_ArraysEmitVertices(RASWGL_BARF_RenderArray *arr,  int prim, int base, int nxyz, int xyzsize, int xyztype, int xyzstep, void *xyz,  int stsize, int sttype, int ststep, void *st,  int normsize, int normtype, int normstep, void *norm, int xnormsize, int xnormtype, int xnormstep, void *xnorm, int ynormsize, int ynormtype, int ynormstep, void *ynorm, int rgbsize, int rgbtype, int rgbstep, void *rgb, int srgbsize, int srgbtype, int srgbstep, void *srgb, int vrgbsize, int vrgbtype, int vrgbstep, void *vrgb, int trgbsize, int trgbtype, int trgbstep, void *trgb);
void RASWGL_BARF_DrawArraysSimpleFlat(RASWGL_BARF_RenderArray *arr,  int prim, int base, int nxyz, int xyzsize, int xyztype, int xyzstep, void *xyz);
void RASWGL_BARF_DrawArraysNormalFlat(RASWGL_BARF_RenderArray *arr,  int prim, int base, int nxyz, int xyzsize, int xyztype, int xyzstep, void *xyz,  int normsize, int normtype, int normstep, void *norm);
void RASWGL_BARF_DrawArraysNormalFlatRGB(RASWGL_BARF_RenderArray *arr,  int prim, int base, int nxyz, int xyzsize, int xyztype, int xyzstep, void *xyz,  int normsize, int normtype, int normstep, void *norm, int rgbsize, int rgbtype, int rgbstep, void *rgb);
void RASWGL_BARF_DrawArraysNormalTex(RASWGL_BARF_RenderArray *arr,  int prim, int base, int nxyz, int xyzsize, int xyztype, int xyzstep, void *xyz,  int stsize, int sttype, int ststep, void *st,  int normsize, int normtype, int normstep, void *norm);
void RASWGL_BARF_DrawArraysNormalTexRGB(RASWGL_BARF_RenderArray *arr,  int prim, int base, int nxyz, int xyzsize, int xyztype, int xyzstep, void *xyz,  int stsize, int sttype, int ststep, void *st,  int normsize, int normtype, int normstep, void *norm, int rgbsize, int rgbtype, int rgbstep, void *rgb);
void RASWGL_BARF_DrawArraysTexRGB(RASWGL_BARF_RenderArray *arr,  int prim, int base, int nxyz, int xyzsize, int xyztype, int xyzstep, void *xyz,  int stsize, int sttype, int ststep, void *st,  int rgbsize, int rgbtype, int rgbstep, void *rgb);
//AHSRC:tkgl_api/ragl_begin.c
RASWGL_Context *RASWGL_CreateContext(int xs, int ys, int flags);
void RASWGL_Finish(RASWGL_Context *ctx);
void RASWGL_Flush(RASWGL_Context *ctx);
void RASWGL_GetFloatv(RASWGL_Context *ctx,int pname, float *params);
void RASWGL_GetIntegerv(RASWGL_Context *ctx,int pname, int *params);
void RASWGL_MatrixMode(RASWGL_Context *ctx, int mode);
void RASWGL_LoadIdentityMatrix(RASWGL_Context *ctx);
void RASWGL_PushMatrix(RASWGL_Context *ctx);
void RASWGL_PopMatrix(RASWGL_Context *ctx);
void RASWGL_LoadMatrix(RASWGL_Context *ctx, float *mat);
void RASWGL_MultMatrix(RASWGL_Context *ctx, float *mat);
void RASWGL_MultMatrixT(RASWGL_Context *ctx, float *mat);
void RASWGL_PushMultMatrix(RASWGL_Context *ctx, float *mat);
void RASWGL_Translatef(RASWGL_Context *ctx, float x, float y, float z);
void RASWGL_Scalef(RASWGL_Context *ctx, float x, float y, float z);
void RASWGL_Rotatef(RASWGL_Context *ctx, float th, float x, float y, float z);
void RASWGL_SetupOrtho(RASWGL_Context *ctx, float left, float right, float bottom, float top,  float nearval, float farval);
void RASWGL_SetupFrustum(RASWGL_Context *ctx, float left, float right, float bottom, float top,  float nearval, float farval);
void RASWGL_TransformPoint(RASWGL_Context *ctx, float *src, float *dst);
void RASWGL_TransformPointLocal(RASWGL_Context *ctx, float *src, float *dst);
void RASWGL_TransformVector(RASWGL_Context *ctx, float *src, float *dst);
void RASWGL_TransformVectorLocal(RASWGL_Context *ctx, float *src, float *dst);
void RASWGL_Init(RASWGL_Context *ctx);
void RASWGL_FlushState(RASWGL_Context *ctx);
void RASWGL_FlushTexture(RASWGL_Context *ctx);
void RASWGL_SetupTexture(RASWGL_Context *ctx);
void RASWGL_BindTexture(RASWGL_Context *ctx, int target, int num);
void RASWGL_DeleteTextures(RASWGL_Context *ctx, int cnt, int *tex);
void RASWGL_GenTextures(RASWGL_Context *ctx, int cnt, int *tex);
int RASWGL_GetCurrentTexture(RASWGL_Context *ctx);
int RASWGL_GetCurrentTextureImage(RASWGL_Context *ctx);
int RASWGL_GetCurrentTextureFlags(RASWGL_Context *ctx);
int RASWGL_GetTextureFlags(RASWGL_Context *ctx, int num);
void RASWGL_BlendFunc(RASWGL_Context *ctx, int src, int dst);
void RASWGL_AlphaFunc(RASWGL_Context *ctx, int func, float ref);
void RASWGL_StencilFunc(RASWGL_Context *ctx, int func, int ref, int mask);
void RASWGL_StencilMask(RASWGL_Context *ctx, int mask);
void RASWGL_StencilOp(RASWGL_Context *ctx,int sfail, int dpfail, int dppass);
void RASWGL_ClipPlane(RASWGL_Context *ctx, int pnum, double *plane);
void RASWGL_Clear(RASWGL_Context *ctx, int mask);
void RASWGL_Enable(RASWGL_Context *ctx, int cap);
void RASWGL_Disable(RASWGL_Context *ctx, int cap);
int RASWGL_IsEnabled(RASWGL_Context *ctx, int cap);
void RASWGL_BeginQuery(RASWGL_Context *ctx, int cap, int id);
void RASWGL_EndQuery(RASWGL_Context *ctx, int cap);
void RASWGL_GetQueryObjectIV(RASWGL_Context *ctx,int id, int cap, u32 *rptr);
void RASWGL_ClearTexture(RASWGL_Context *ctx);
void RASWGL_BeginPoly(RASWGL_Context *ctx);
void RASWGL_EndPoly(RASWGL_Context *ctx);
void RASWGL_Begin(RASWGL_Context *ctx, int prim);
void RASWGL_End(RASWGL_Context *ctx);
void RASWGL_EndPrim_DrawArrays(RASWGL_Context *ctx, int prim, float *xyz, float *st, float *norm, float *rgba, int nxyz);
void RASWGL_GetWindowOrigin(RASWGL_Context *ctx, int *rxs, int *rys);
void RASWGL_GetWindowSize(RASWGL_Context *ctx, int *rxs, int *rys);
void RASWGL_GetWindowMaxSize(RASWGL_Context *ctx, int *rxs, int *rys);
void RASWGL_GetWindowTexSize(RASWGL_Context *ctx, int *rxs, int *rys);
void RASWGL_GetWindowMaxTexSize(RASWGL_Context *ctx, int *rxs, int *rys);
void RASWGL_EndPrim_DrawTexture(RASWGL_Context *ctx, int prim);
void RASWGL_EndPrim(RASWGL_Context *ctx, int prim);
void RASWGL_VertexDownProject(RASWGL_Context *ctx);
void RASWGL_VertexCheckExpand(RASWGL_Context *ctx, int pad);
void RASWGL_Vertex3fv(RASWGL_Context *ctx, float *v);
void RASWGL_Vertex4fv(RASWGL_Context *ctx, float *v);
void RASWGL_TexCoord2fv(RASWGL_Context *ctx, float *v);
void RASWGL_Normal3fv(RASWGL_Context *ctx, float *v);
void RASWGL_Normal4fv(RASWGL_Context *ctx, float *v);
void RASWGL_Normal3sbv(RASWGL_Context *ctx, sbyte *v);
void RASWGL_Color3fv(RASWGL_Context *ctx, float *v);
void RASWGL_Color4fv(RASWGL_Context *ctx, float *v);
void RASWGL_Color4ubv(RASWGL_Context *ctx, byte *v);
void RASWGL_Color3f(RASWGL_Context *ctx, float r, float g, float b);
void RASWGL_Color4f(RASWGL_Context *ctx, float r, float g, float b, float a);
void RASWGL_TexCoord2f(RASWGL_Context *ctx, float s, float t);
void RASWGL_Vertex2f(RASWGL_Context *ctx, float x, float y);
void RASWGL_Vertex3f(RASWGL_Context *ctx, float x, float y, float z);
void RASWGL_Normal3f(RASWGL_Context *ctx, float x, float y, float z);
void RASWGL_Normal4f(RASWGL_Context *ctx, float x, float y, float z, float w);
void RASWGL_Vertex4f(RASWGL_Context *ctx, float x, float y, float z, float w);
void RASWGL_TexCoord_Ptrv(RASWGL_Context *ctx, int size, int type, void *ptr);
void RASWGL_Normal_Ptrv(RASWGL_Context *ctx, int size, int type, void *ptr);
void RASWGL_Color_Ptrv(RASWGL_Context *ctx, int size, int type, void *ptr);
void RASWGL_Vertex_Ptrv(RASWGL_Context *ctx, int size, int type, void *ptr);
void RASWGL_DrawArraysSimpleFlat(RASWGL_Context *ctx, int prim, int base, int nxyz, int xyzsize, int xyztype, int xyzstep, void *xyz);
void RASWGL_DrawArraysNormalFlat(int prim, int base, int nxyz, int xyzsize, int xyztype, int xyzstep, void *xyz,  int normsize, int normtype, int normstep, void *norm);
void RASWGL_DrawArraysNormalFlatRGB(int prim, int base, int nxyz, int xyzsize, int xyztype, int xyzstep, void *xyz,  int normsize, int normtype, int normstep, void *norm, int rgbsize, int rgbtype, int rgbstep, void *rgb);
void RASWGL_DrawArraysNormalTex(int prim, int base, int nxyz, int xyzsize, int xyztype, int xyzstep, void *xyz,  int stsize, int sttype, int ststep, void *st,  int normsize, int normtype, int normstep, void *norm);
void RASWGL_DrawArraysNormalTexRGB(int prim, int base, int nxyz, int xyzsize, int xyztype, int xyzstep, void *xyz,  int stsize, int sttype, int ststep, void *st,  int normsize, int normtype, int normstep, void *norm, int rgbsize, int rgbtype, int rgbstep, void *rgb);
void RASWGL_DrawElementsSimpleFlat(int prim, int nelem, int elemtype, void *elems, int xyzsize, int xyztype, int xyzstep, void *xyz);
void RASWGL_DrawElementsNormalTexRGB(int prim, int nelem, int elemtype, void *elems, int xyzsize, int xyztype, int xyzstep, void *xyz,  int stsize, int sttype, int ststep, void *st,  int normsize, int normtype, int normstep, void *norm, int rgbsize, int rgbtype, int rgbstep, void *rgb);
//AHSRC:tkgl_api/ragl_clip.c
int RASWGL_TransformClipTriangles(RASWGL_Context *ctx, int nxyz, int nclip, int clipsz, float *clip, int xyzsz,		int stsz, int nvsz,		int rgbsz, float *ixyz,	float *ist, float *inv,		float *irgb, float *oxyz,	float *ost, float *onv,		float *orgb);
int RASWGL_TransformClipQuads(RASWGL_Context *ctx, int nxyz, int nclip, int clipsz, float *clip, int xyzsz,		int stsz, int nvsz,		int rgbsz, float *ixyz,	float *ist, float *inv,		float *irgb, float *oxyz,	float *ost, float *onv,		float *orgb);
//AHSRC:tkgl_api/ragl_gldrv.c
void RaGlSetErrorNopStub(void);
//AHSRC:tkgl_api/ragl_gpafuncs.c
int TKGL_GpaHash(char *str);
void *TKGL_GetProcAddress(char *name);
//AHSRC:tkgl_api/ragl_light.c
void RASWGL_Lightf(RASWGL_Context *ctx, int target, int pname, float param);
void RASWGL_Lighti(RASWGL_Context *ctx, int target, int pname, int param);
void RASWGL_Lightfv(RASWGL_Context *ctx, int target, int pname, const float *params);
void RASWGL_Lightiv(RASWGL_Context *ctx, int target, int pname, const int *params);
void RASWGL_LightModelf(RASWGL_Context *ctx, int pname, float param);
void RASWGL_LightModeli(RASWGL_Context *ctx, int pname, int param);
void RASWGL_LightModelfv(RASWGL_Context *ctx, int pname, const float *params);
void RASWGL_LightModeliv(RASWGL_Context *ctx, int pname, const int *params);
void RASWGL_Materialf(RASWGL_Context *ctx, int target, int pname, float param);
void RASWGL_Materiali(RASWGL_Context *ctx, int target, int pname, int param);
void RASWGL_Materialfv(RASWGL_Context *ctx, int target, int pname, const float *params);
void RASWGL_Materialiv(RASWGL_Context *ctx, int target, int pname, const int *params);
void RASWGL_CalcLightVertexColor(RASWGL_Context *ctx, float *xyzw, float *srgb, float *drgb);
//AHSRC:tkgl_api/ragl_raswprim.c
void RASWGL_VertexToViewportPixels(RASWGL_Context *ctx, float *sxyz, int *dxy, bgbrasw_zbuf *dz);
void RASWGL_CoordsToViewportTexels(RASWGL_Context *ctx, BGBRASW_Texture *tex, float *suv, int *duv);
void RASWGL_ColorsToViewportColors(RASWGL_Context *ctx, float *srgb, bgbrasw_pixel *drgb);
void RASWGL_ColorsToViewportColors2(RASWGL_Context *ctx, float *xyzw, float *srgb, bgbrasw_pixel *drgb);
int RASWGL_ClasifyPrimitive_FlatColorP(RASWGL_Context *ctx, BGBRASW_Primitive *prim);
int RASWGL_ClasifyPrimitive_OpaqueP(RASWGL_Context *ctx, BGBRASW_Primitive *prim);
int RASWGL_ClasifyPrimitive_BasicOpaqueP(RASWGL_Context *ctx, BGBRASW_Primitive *prim);
int RASWGL_ClasifyPrimitive_TexValidP(RASWGL_Context *ctx, BGBRASW_Primitive *prim);
int RASWGL_ClasifyPrimitive_NeedsTabsP(RASWGL_Context *ctx, BGBRASW_Primitive *prim);
int RASWGL_ClasifyPrimitiveMode(RASWGL_Context *ctx,BGBRASW_Primitive *prim);
void RASWGL_ClasifyPrimitive(RASWGL_Context *ctx, BGBRASW_Primitive *prim);
int raswgl_dist2d2(int *xy0, int *xy1);
void raswgl_avgxy2d(int *xy0, int *xy1, int *st0, int *st1, bgbrasw_pixel clra,	bgbrasw_pixel clrb, bgbrasw_zbuf z0, bgbrasw_zbuf z1, int w0, int w1, int *dxy, int *dst, bgbrasw_pixel *dclr, bgbrasw_zbuf *dz, int *dw);
int raswgl_copyxy2d(int *sxy, int *sst, bgbrasw_pixel  sclr, bgbrasw_zbuf  sz, int sw, int *dxy, int *dst, bgbrasw_pixel *dclr, bgbrasw_zbuf *dz, int *dw);
BGBRASW_Primitive *RASWGL_AllocPrimitiveForPoint(RASWGL_Context *ctx, float *org, float *min, float *max);
void RASWGL_SubmitPrimitive(RASWGL_Context *ctx, BGBRASW_Primitive *prim);
void RASWGL_BuildInsertPrimitiveArrays(RASWGL_Context *ctx, int prim, int base, int nxyz, int xyzsize, float *xyz,  int stsize, float *st,  int normsize, float *norm, int rgbsize, float *rgb);
//AHSRC:tkgl_api/ragl_teximage.c
char *RASWGL_GetString(RASWGL_Context *ctx, int name);
void RASWGL_TexEnvf(RASWGL_Context *ctx, int target, int pname, float param);
void RASWGL_TexEnvi(RASWGL_Context *ctx, int target, int pname, int param);
void RASWGL_TexEnvfv(RASWGL_Context *ctx, int target, int pname, const float *params);
void RASWGL_TexEnviv(RASWGL_Context *ctx, int target, int pname, const int *params);
void RASWGL_GetTexEnvfv(RASWGL_Context *ctx, int target, int pname, float *params);
void RASWGL_GetTexEnviv(RASWGL_Context *ctx, int target, int pname, int *params);
void RASWGL_TexParameterf(RASWGL_Context *ctx, int target, int pname, float param);
void RASWGL_TexParameteri(RASWGL_Context *ctx, int target, int pname, int param);
void RASWGL_TexParameterfv(RASWGL_Context *ctx, int target, int pname, const float *params);
void RASWGL_TexParameteriv(RASWGL_Context *ctx, int target, int pname, const int *params);
void RASWGL_GetTexParameterfv(RASWGL_Context *ctx, int target, int pname, float *params);
void RASWGL_GetTexParameteriv(RASWGL_Context *ctx, int target, int pname, int *params);
void RASWGL_GetTexLevelParameterfv(RASWGL_Context *ctx, int target, int level, int pname, float *params);
void RASWGL_GetTexLevelParameteriv(RASWGL_Context *ctx, int target, int level, int pname, int *params);
void RASWGL_TexImage1D(RASWGL_Context *ctx, int target, int level, int internalFormat, int width, int border, int format, int type, const void *pixels);
int RASWGL_TexImage_ConvPixelsFromSrc(int width, int height, int format, int type, const void *pixels, bgbrasw_pixel *opix);
int RASWGL_TexImage_ConvSubImagePixelsFromSrc(int xoffs, int yoffs, int width, int height, int format, int type, const void *pixels, bgbrasw_pixel *opix, int tgtxs, int tgtys);
void RASWGL_TexImage2D(RASWGL_Context *ctx, int target, int level, int internalFormat, int width, int height, int border, int format, int type, const void *pixels);
void RASWGL_GetTexImage(RASWGL_Context *ctx, int target, int level, int format, int type, void *pixels);
void RASWGL_TexSubImage1D(RASWGL_Context *ctx, int target, int level, int xoffset, int width, int format, int type, const void *pixels);
void RASWGL_TexSubImage2D(RASWGL_Context *ctx, int target, int level, int xoffset, int yoffset, int width, int height, int format, int type, const void *pixels);
void RASWGL_CopyTexImage1D(RASWGL_Context *ctx, int target, int level, int internalformat, int x, int y, int width, int border);
void RASWGL_CopyTexImage2D(RASWGL_Context *ctx, int target, int level, int internalformat, int x, int y, int width, int height, int border);
void RASWGL_CopyTexSubImage1D(RASWGL_Context *ctx, int target, int level, int xoffset, int x, int y, int width);
void RASWGL_CopyTexSubImage2D(RASWGL_Context *ctx, int target, int level, int xoffset, int yoffset, int x, int y, int width, int height);
void RASWGL_CompressedTexImage2D(RASWGL_Context *ctx, int target, int level, int internalFormat, int width, int height, int border, int imgSize, const void *pixels);
void RASWGL_ReadPixels(RASWGL_Context *ctx,  int x, int y, int width, int height, int format, int type, byte *pixels);
//AHSRC:tkgl_api/ragl_transform.c
void RASWGL_CheckExpandTransform0Vertices(RASWGL_Context *ctx, int nxyz);
void RASWGL_CheckExpandTransform1Vertices(RASWGL_Context *ctx, int nxyz);
void RASWGL_CheckExpandTransformNVertices(RASWGL_Context *ctx, int nxyz);
void RASWGL_TransformVerticesModelviewXYZ(RASWGL_Context *ctx, int nxyz, int ixyzsz, float *ixyz, int oxyzsz, float *oxyz);
void RASWGL_TransformVerticesProjectionXYZ(RASWGL_Context *ctx, int nxyz, int ixyzsz, float *ixyz, int oxyzsz, float *oxyz);
void RASWGL_TransformNormalsModelviewXYZ(RASWGL_Context *ctx, int nxyz, int ixyzsz, float *ixyz, int oxyzsz, float *oxyz);
void RASWGL_TransformNormalsProjectionXYZ(RASWGL_Context *ctx, int nxyz, int ixyzsz, float *ixyz, int oxyzsz, float *oxyz);
void RASWGL_TransformVerticesModelviewProjectionXYZ(RASWGL_Context *ctx, int nxyz, int ixyzsz, float *ixyz, int oxyzsz, float *oxyz);
void RASWGL_TransformNormalsModelviewProjectionXYZ(RASWGL_Context *ctx, int nxyz, int ixyzsz, float *ixyz, int oxyzsz, float *oxyz);
void RASWGL_TransformVerticesDivide_XYZ_W(RASWGL_Context *ctx, int nxyz, int ixyzsz, float *ixyz, int oxyzsz, float *oxyz);
void RASWGL_TransformVerticesDivide_XYZ_W(RASWGL_Context *ctx, int nxyz, int ixyzsz, float *ixyz, int oxyzsz, float *oxyz);
float raswgl_perspprojxyzw(float *xyz0, float *dxyz);
float raswgl_perspdist2xyzw(float *xyz0, float *xyz1);
float raswgl_avgdist2xyzw(float *xyz0, float *xyz1, float *oxyz, float *st0, float *st1, float *ost, float *nv0, float *nv1, float *onv, float *rgb0, float *rgb1, float *orgb);
int RASWGL_TransformSubdivideInsertTriangle(RASWGL_Context *ctx, int rc, float *xyz0,	float *st0,		float *nv0,		float *rgb0, float *xyz1,	float *st1,		float *nv1,		float *rgb1, float *xyz2,	float *st2,		float *nv2,		float *rgb2, float *oxyz,	float *ost,		float *onv,		float *orgb, float *exyz,	float *est,		float *env,		float *ergb);
int RASWGL_TransformSubdivideInsertQuad(RASWGL_Context *ctx, int rc, float *xyz0,	float *st0,		float *nv0,		float *rgb0, float *xyz1,	float *st1,		float *nv1,		float *rgb1, float *xyz2,	float *st2,		float *nv2,		float *rgb2, float *xyz3,	float *st3,		float *nv3,		float *rgb3, float *oxyz,	float *ost,		float *onv,		float *orgb, float *exyz,	float *est,		float *env,		float *ergb);
int RASWGL_TransformSubdivideCheckCull(RASWGL_Context *ctx,float *xyz0, float *xyz1, float *xyz2);
int RASWGL_TransformSubdivideTriangles(RASWGL_Context *ctx, int ntris, int mtris, float *ixyz,	float *ist, float *inv,		float *irgb, float *oxyz,	float *ost, float *onv,		float *orgb);
int RASWGL_TransformSubdivideQuads(RASWGL_Context *ctx, int nquad, int mquad, float *ixyz,	float *ist, float *inv,		float *irgb, float *oxyz,	float *ost, float *onv,		float *orgb);
void RASWGL_TransformDrawTriangles(RASWGL_Context *ctx, int base, int nxyz, int xyzsize, float *xyz, int stsize, float *st, int normsize, float *norm, int rgbsize, float *rgb);
void RASWGL_TransformDrawQuads(RASWGL_Context *ctx, int base, int nxyz, int xyzsize, float *xyz, int stsize, float *st, int normsize, float *norm, int rgbsize, float *rgb);
void RASWGL_TransformDrawPolygon(RASWGL_Context *ctx, int base, int nxyz, int xyzsz, float *xyz, int stsz, float *st, int nvsz, float *nv, int rgbsz, float *rgb);
void RASWGL_TransformDrawTriangleStrip(RASWGL_Context *ctx, int base, int nxyz, int xyzsz, float *xyz, int stsz, float *st, int nvsz, float *nv, int rgbsz, float *rgb);
void RASWGL_TransformDrawQuadStrip(RASWGL_Context *ctx, int base, int nxyz, int xyzsz, float *xyz, int stsz, float *st, int nvsz, float *nv, int rgbsz, float *rgb);
void RASWGL_SetupTabs(RASWGL_Context *ctx);
void RASWGL_FinishTabs(RASWGL_Context *ctx);
void RASWGL_TransformDrawArrays(RASWGL_Context *ctx, int prim, int base, int nxyz, int xyzsize, float *xyz, int stsize, float *st, int normsize, float *norm, int rgbsize, float *rgb);
void RASWGL_DrawBaseArrays(RASWGL_Context *ctx, int prim, int base, int nxyz, int xyzsize, int xyztype, int xyzstep, void *xyz,  int stsize, int sttype, int ststep, void *st,  int normsize, int normtype, int normstep, void *norm, int rgbsize, int rgbtype, int rgbstep, void *rgb);
//AHSRC:tkgl_api/ragl_vertexarray.c
int raswgl_barf_arrayStepSize(int vsize, int vtype, int ivstep);
void RASWGL_EnableClientState(RASWGL_Context *ctx, int cap);
void RASWGL_DisableClientState(RASWGL_Context *ctx, int cap);
void RASWGL_VertexPointer(RASWGL_Context *ctx, int size, int type, int stride, const void *ptr);
void RASWGL_TexCoordPointer(RASWGL_Context *ctx, int size, int type, int stride, const void *ptr);
void RASWGL_NormalPointer(RASWGL_Context *ctx, int type, int stride, const void *ptr);
void RASWGL_ColorPointer(RASWGL_Context *ctx, int size, int type, int stride, const void *ptr);
void RASWGL_IndexPointer(RASWGL_Context *ctx, int type, int stride, const void *ptr);
void RASWGL_EdgeFlagPointer(RASWGL_Context *ctx, int stride, const void *ptr);
void RASWGL_GetPointerv(RASWGL_Context *ctx, int pname, void **params);
void RASWGL_ArrayElement(RASWGL_Context *ctx, int i);
void RASWGL_ArrayElements2(RASWGL_Context *ctx, int si, int di, int cnt);
void RASWGL_DrawArrays(RASWGL_Context *ctx, int mode, int first, int count);
void RASWGL_DrawElements(RASWGL_Context *ctx, int mode, int count, int type, const void *indices);
void RASWGL_InterleavedArrays(RASWGL_Context *ctx, int format, int stride, const void *pointer);
void RASWGL_GenCoord_ArrPtrv(RASWGL_Context *ctx, int size, int type, int stri, byte *sptr, int dstri, float *dptr, int cnt, float pad, int normp);
void RASWGL_TexCoord_ArrPtrv(RASWGL_Context *ctx, int size, int type, int stri, void *ptr, int di, int cnt);
void RASWGL_Normal_ArrPtrv(RASWGL_Context *ctx, int size, int type, int stri, void *ptr, int di, int cnt);
void RASWGL_Color_ArrPtrv(RASWGL_Context *ctx, int size, int type, int stri, void *ptr, int di, int cnt);
void RASWGL_Vertex_ArrPtrv(RASWGL_Context *ctx, int size, int type, int stri, void *ptr, int di, int cnt);
//AHSRC:tkgl_api/ragl_glw32.c
//AHSRC:vecmath/math_clip.c
int Hull_LinePlaneIntersect(float *start, float *end,float *norm, float *point);
int Hull_LinePlaneIntersectST(float *sv, float *sst,float *ev, float *est, float *norm, float *ov, float *ost);
int Hull_LinePlaneIntersectSTNVRGBA(float *norm, float *sv, float *sst, float *snv, float *sclr, float *ev, float *est, float *env, float *eclr, float *ov, float *ost, float *onv, float *oclr, int flags);
void Hull_AdjacentNormals(float *norm, float *udir, float *vdir);
void Hull_AdjacentNormals2(float *norm, float *udir, float *vdir);
void Hull_AdjacentNormals21(float *norm, float *udir, float *vdir);
void Hull_AdjacentNormals22(float *norm, float *udir, float *vdir);
void Hull_AdjacentNormals23(float *norm, float *udir, float *vdir);
void Hull_MakePlaneFace(float *norm, float *pts);
int Hull_ClipFace(float *norm,float *ipts, float *opts, int num);
int Hull_ClipFaceST(float *norm,float *ipts, float *ist, float *opts, float *ost, int num);
int Hull_ClipFaceSTNVRGBA(float *norm,int xyzsz, int stsz, int nvsz, int clrsz, float *ipts, float *ist, float *inv, float *iclr, float *opts, float *ost, float *onv, float *oclr, int num, int flags);
void Hull_BoxPlaneExtents(float *mins, float *maxs, float *norm, float *rm, float *rn);
void Hull_SpherePlaneExtents(float *org, float rad, float *norm, float *rm, float *rn);
//AHSRC:vecmath/math_hullf.c
void HullF_MakePlaneFace(float *norm, float *pts);
int HullF_ClipFace(float *norm,float *ipts, float *opts, int num);
int HullF_BoxHull(float *norm, int num,float *mins, float *maxs);
//AHSRC:vecmath/math_m3.c
void Mat3F_Copy(float *a, float *b);
void Mat3F_Transpose(float *a, float *b);
void Mat3F_Identity(float *a);
void Mat3F_Mat3Mult(float *a, float *b, float *c);
void Mat3F_Mat3MultT(float *a, float *b, float *c);
void Mat3F_Mat3TMult(float *a, float *b, float *c);
void Mat3F_TransformVector(float *a, float *xform, float *c);
void Mat3F_Inverse(float *a, float *b);
void Mat3F_AxisTo3Matrix(float *a, float th, float *b);
void Mat3F_Filter3Matrix(float *a, float *b);
void Mat3F_Rotate3Matrix(float *a, float *v, float th, float *b);
int Mat3F_ArcPolate(float *v0, float *v1, float *v2, float t, float *rnv);
void Mat3F_LinePolate(float *v0, float *v1, float *v2, float t,float *n);
void Mat3F_Interpolate(float *m0, float *m1, float *m2, float t);
//AHSRC:vecmath/math_m4.c
void Mat4F_Identity(float *a);
void Mat4F_Copy(float *a, float *b);
int Mat4F_Equal(float *a, float *b);
void Mat4F_MatMult(float *a, float *b, float *c);
void Mat4F_MatMultT(float *a, float *b, float *c);
void Mat4F_Transpose(float *a, float *b);
void Mat4F_Inverse(float *a, float *b);
void Mat4F_Inverse(float *a, float *b);
void Mat4F_InverseTransform(float *a, float *b);
void Mat4F_InterpolateTransform(float *m0, float *m1, float *m2, float t);
void Mat4F_TransformVector4(float *a, float *b, float *c);
void Mat4F_TransformVector4T(float *a, float *b, float *c);
void Mat4F_TransformPoint34G(float *point, float *xform, float *org);
void Mat4F_TransformVector(float *dir, float *xform, float *v);
void Mat4F_TransformVectorT(float *dir, float *xform, float *v);
void Mat4F_TransformNormal(float *dir, float *xform, float *norm);
void Mat4F_TransformNormalT(float *dir, float *xform, float *norm);
void Mat4F_TransformNormalN(float *dir, float *xform, float *norm);
void Mat4F_TransformNormalNT(float *dir, float *xform, float *norm);
void Mat4F_TransformPoint(float *point, float *xform, float *org);
void Mat4F_TransformPointT(float *point, float *xform, float *org);
void Mat4F_TransformPointN(float *point, float *xform, float *org);
void Mat4F_TransformPointNT(float *point, float *xform, float *org);
void Mat4F_TransformPointLocal(float *point, float *xform, float *org);
void Mat4F_TransformPointLocalT(float *point, float *xform, float *org);
void Mat4F_AxisTo4Matrix(float *a, float th, float *b);
void Mat4F_AxisTo4MatrixT(float *a, float th, float *b);
void Mat4F_Filter4Matrix(float *a, float *b);
void Mat4F_Rotate4Matrix(float *a, float *v, float th, float *b);
void Mat4F_Set4MatrixRotXY(float *a, float th);
void Mat4F_Set4MatrixRotXZ(float *a, float th);
void Mat4F_Set4MatrixRotYZ(float *a, float th);
void Mat4F_Set4MatrixRotXW(float *a, float th);
void Mat4F_Set4MatrixRotYW(float *a, float th);
void Mat4F_Set4MatrixRotZW(float *a, float th);
void Mat4F_Rotate4MatrixXY(float *a, float th, float *b);
void Mat4F_Rotate4MatrixXZ(float *a, float th, float *b);
void Mat4F_Rotate4MatrixYZ(float *a, float th, float *b);
void Mat4F_Rotate4MatrixXW(float *a, float th, float *b);
void Mat4F_Rotate4MatrixYW(float *a, float th, float *b);
void Mat4F_Rotate4MatrixZW(float *a, float th, float *b);
void Mat4F_Rotate4MatrixAngles(float *a, float *ang, float *b);
void Mat4F_SetupFrustum(float *mat,float left, float right, float bottom, float top, float nearval, float farval);
void Mat4F_SetupOrtho(float *mat,float left, float right, float bottom, float top, float nearval, float farval);
//AHSRC:vecmath/math_mf.c
void Mat34F_MatMult(float *a, float *b, float *c);
void Mat34F_Transpose(float *a, float *b);
void Mat3to4F_Copy(float *a, float *b);
void Mat3to4F_Transpose(float *a, float *b);
//AHSRC:vecmath/math_n.c
float Vec3F_DistLine(float *pt, float *v0, float *v1);
float Vec3F_DistLineSeg(float *pt, float *v0, float *v1);
//AHSRC:vecmath/math_plane.c
int PlaneF_LinePlaneIntersect(float *start, float *end, float *norm, float *point);
int PlaneF_CheckLinePlane(float *start, float *end, float *norm);
int PlaneF_ClipLinePlane(float *start, float *end, float *norm);
void PlaneF_NearestPointLinePlane(float *start, float *end,float *norm, float *pt);
int PlaneF_CheckPlaneBox(float *norm, float *mins, float *maxs);
void PlaneF_BoxAxisExtents(float *mins, float *maxs,float *norm, float *min, float *max);
void PlaneF_BoxPlaneExtents(float *mins, float *maxs,float *norm, float *min, float *max);
void PlaneF_TransformVector(float *dir, float *xform, float *v);
void PlaneF_TransformVectorT(float *dir, float *xform, float *v);
void PlaneF_TransformNormal(float *dir, float *xform, float *norm);
void PlaneF_TransformNormalT(float *dir, float *xform, float *norm);
void PlaneF_TransformNormalN(float *dir, float *xform, float *norm);
void PlaneF_TransformNormalNT(float *dir, float *xform, float *norm);
void PlaneF_TransformPoint(float *point, float *xform, float *org);
void PlaneF_TransformPointT(float *point, float *xform, float *org);
void PlaneF_TransformPointN(float *point, float *xform, float *org);
void PlaneF_TransformPointNT(float *point, float *xform, float *org);
void PlaneF_TransformPointLocal(float *point, float *xform, float *org);
void PlaneF_AdjacentNormals(float *n, float *x, float *y);
void PlaneF_AdjacentNormals2(float *norm, float *udir, float *vdir);
//AHSRC:vecmath/math_quat.c
void QuatF_Identity(float *a);
void QuatF_Negate(float *a, float *b);
void QuatF_Conjugate(float *a, float *b);
void QuatF_Recip(float *a, float *b);
float QuatF_Magnitude(float *a);
float QuatF_Normalize(float *a, float *b);
void QuatF_Multiply(float *a, float *b, float *c);
void QuatF_ToMatrix(float *a, float *b);
void QuatF_To3Matrix(float *a, float *b);
void QuatF_FromMatrix(float *a, float *b);
void QuatF_From3Matrix(float *a, float *b);
void QuatF_FromAxis(float *a, float b, float *c);
void QuatF_ToAxis(float *a, float *b, float *c);
void QuatF_FromAngles(float *a, float *b);
void QuatF_ToAngles(float *a, float *b);
void QuatF_Lerp(float *a, float *b, float t, float *c);
void QuatF_SLerp(float *a, float *ib, float t, float *c);
//AHSRC:vecmath/math_solid.c
void SolidAABB_BoxMove(float *bmins, float *bmaxs,float *start, float *end, float *mins, float *maxs);
int SolidAABB_BoxCollideP(float *ma, float *na, float *mb, float *nb);
int SolidAABB_BoxCollideAxis(float *ma, float *na, float *mb, float *nb);
int SolidAABB_PointInBoxP(float *p, float *min, float *max);
void SolidAABB_BoxIntersection(float *ma, float *na,float *mb, float *nb, float *mc, float *nc);
int SolidAABB_BoxLineCollideP(float *min, float *max, float *sp, float *ep);
int SolidOBB_CheckObbPlane(float *mins, float *maxs,float *xform, float *norm, float *io);
void SolidOBB_GenPoints(float *mins, float *maxs, float *pos, float *pts);
int SolidOBB_ObbPlaneIntersect(float *mins, float *maxs,float *xform, float *norm, float *io);
int SolidOBB_ObbPlaneExtents(float *mins, float *maxs,float *xform, float *norm, float *ext);
void SolidOBB_PlaneExtents(float *mins, float *maxs,float *xform, float *norm, float *min, float *max);
int SolidOBB_ObbPlaneMoveExtents(float *mins, float *maxs,float *sxform, float *exform, float *norm, float *ext);
int SolidOBB_CheckObbMovePlane(float *mins, float *maxs,float *sxform, float *exform, float *norm, float *io);
int SolidOBB_CheckCollide(float *amins, float *amaxs, float *apos, float *bmins, float *bmaxs, float *bpos);
int SolidOBB_CheckObbMove(float *amins, float *amaxs, float *aspos, float *aepos, float *bmins, float *bmaxs, float *bspos, float *bepos, float *org);
int SolidOBB_ObbImpactNormal(float *amins, float *amaxs, float *aspos, float *aepos, float *bmins, float *bmaxs, float *bspos, float *bepos, float *vel, float *norm);
void SolidOBB_Box(float *mins, float *maxs, float *pos,float *bmins, float *bmaxs);
void SolidOBB_BoxMove(float *mins, float *maxs, float *spos, float *epos, float *bmins, float *bmaxs);
int SolidOBB_ObbPointCollide(float *mins, float *maxs, float *pos, float *org);
int SolidOBB_BoxLineCollideP(float *min, float *max, float *pos,float *sp, float *ep);
//AHSRC:vecmath/math_v3f.c
void Vec3F_Set(float *a, float x, float y, float z);
void Vec3F_Zero(float *a);
void Vec3F_Copy(float *a, float *b);
void Vec3F_Add(float *a, float *b, float *c);
void Vec3F_Subtract(float *a, float *b, float *c);
void Vec3F_Scale(float *a, float b, float *c);
float Vec3F_DotProduct(float *a, float *b);
float Vec3F_Length(float *a);
void Vec3F_ScaleAdd(float *a, float b, float *c, float *d);
void Vec3F_AddScale(float *a, float *b, float c, float *d);
void Vec3F_ScaleAddScale(float *a, float b, float *c, float d, float *e);
float Vec3F_Normalize(float *a, float *b);
float Vec3F_Distance(float *a, float *b);
void Vec3F_CrossProduct(float *a, float *b, float *c);
float Vec3F_NearestRayDistance(float *a, float *adir, float *b, float *bdir);
float Vec3F_NearestRayPoints(float *a, float *adir, float *b, float *bdir,float *pA, float *pB);
float Vec3F_NearestLinePoints(float *As, float *Ae, float *Bs, float *Be,float *pA, float *pB);
float Vec3F_NearestLineDistance(float *As, float *Ae, float *Bs, float *Be);
int Vec3F_BoxTouchP(float *ma, float *na, float *mb, float *nb);
int Vec3F_BoxCollideP(float *ma, float *na, float *mb, float *nb);
void Vec3F_LinePlaneIntersect(float *start, float *end, float *norm,float *point);
int Vec3F_LineBoxCollideP(float *m, float *n, float *s, float *e);
void Vec3F_QuatToEulerYXZ(float *quat, float *ang);
void Vec3F_QuatToEulerZXY(float *quat, float *ang);
void Vec3F_QuatToEulerXYZ(float *quat, float *ang);
void Vec3F_QuatFromEulerZXY(float *quat, float *ang);
void Vec3F_Mat3ToEuler(float *mat, float *ang);
void Vec3F_QuatToEulerZXZ(float *quat, float *ang);
void Vec3F_AxisToRot3(float *axis, float angle, float *rot);
void Vec3F_RotatePointAxis(float *src, float *axis, float angle, float *dst);
//AHSRC:vecmath/math_vecnf.c
void *VecNF_Ralloc(int sz);
//AHSRC:vecmath/math_vnf.c
void VecNF_Copy(float *a, float *b, int n);
void VecNF2D_Copy(float *a, double *b, int n);
void VecNF_ResizeVector(float *a, int an, float *b, int bn);
float VecNF_DotProduct(float *a, float *b, int n);
float VecNF_Length(float *a, int n);
float VecNF_Normalize(float *a, float *b, int n);
float VecNF_Distance(float *a, float *b, int n);
void VecNF_Add(float *a, float *b, float *c, int n);
void VecNF_Subtract(float *a, float *b, float *c, int n);
void VecNF_Scale(float *a, float b, float *c, int n);
void VecNF_ScaleAdd(float *a, float b, float *c, float *d, int n);
void VecNF_AddScale(float *a, float *b, float c, float *d, int n);
void VecNF_ScaleAddScale(float *a, float b, float *c, float d, float *e, int n);
void VecNF_Zero(float *a, int n);
void VecNF_Const(float *a, float b, int n);
void VecNF_ProjectPointOnPlane(float *d, float *v, float *z, int n);
void VecNF_ProjectPointOnPlane2(float *d, float *v, float *z, int n);
void VecNF_ProjectPointBelowPlane(float *d, float *v, float *z, int n);
void VecNF_ProjectPointAbovePlane(float *d, float *v, float *z, int n);
void VecNF_LinePlaneIntersect(float *start, float *end, float *norm, float *point, int n);
int VecNF_CheckPlaneBox(float *norm, float *mins, float *maxs, int n);
//AHSRC:vecmath/mathlib_d.c
void MatND_MatMult(double *a, int ah, int aw, double *b, int bh, int bw, double *c);
void MatND_MatMultVector(double *a, double *b, double *c, int n);
void MatND_MatMultScaler(double *a, double b, double *c, int n);
void MatND_ResizeMatrix(double *a, int ah, int aw, double *b, int bh, int bw);
void MatND_FillIdentity(double *a, int n);
void MatND_Copy(double *a, double *b, int h, int w);
void Vec16D_RotateMatrix(double *amat, double *angles, double *bmat);
void MatND_GetLowerMatrix(double *a, double *b, int n);
void MatND_GetUpperMatrix(double *a, double *b, int n);
void Vec16D_TranslateMatrix(double *amat, double *pos, double *bmat);
void MatND_SwapOrder(double *a, double *b, int n);
void MatND_Inverse(double *a, double *b, int n);
void VecND_Copy(double *a, double *b, int n);
void VecND2F_Copy(double *a, float *b, int n);
void VecND_ResizeVector(double *a, int an, double *b, int bn);
double VecND_DotProduct(double *a, double *b, int n);
double VecND_Length(double *a, int n);
double VecND_Normalize(double *a, double *b, int n);
double VecND_Distance(double *a, double *b, int n);
void VecND_Add(double *a, double *b, double *c, int n);
void VecND_Subtract(double *a, double *b, double *c, int n);
void VecND_Scale(double *a, double b, double *c, int n);
void VecND_ScaleAdd(double *a, double b, double *c, double *d, int n);
void VecND_AddScale(double *a, double *b, double c, double *d, int n);
void VecND_ScaleAddScale(double *a, double b, double *c, double d, double *e, int n);
void VecND_Zero(double *a, int n);
void VecND_Const(double *a, double b, int n);
void VecND_ProjectPointOnPlane(double *d, double *v, double *z, int n);
void Vec3D_CrossProduct (double *v1, double *v2, double *cross);
void Vec3D_ToSphericalCoords(double *a, double *b);
void Vec3D_FromSphericalCoords(double *a, double *b);
void Vec16D_InvertAngles(double *amat, double *bmat);
void Vec3D_RotatePoint(double *p, double *angles);
void Vec3D_CalcAngleVectors(double *angles, double *forward, double *right, double *up);
void Vec3D_PointToParentSpace(double *a, double *sp, double *b);
//AHSRC:vecmath/mathlib_f.c
float *VecNF_AllocVec(int sz);
double *VecND_AllocVec(int sz);
void MatNF_MatMult(float *a, int ah, int aw, float *b, int bh, int bw, float *c);
void MatNF_MatMultT(float *a, int ah, int aw, float *b, int bh, int bw, float *c);
void MatNF_MatMultVector(float *a, float *b, float *c, int n);
void MatNF_MatMultScaler(float *a, float b, float *c, int n);
void MatNF_ResizeMatrix(float *a, int ah, int aw, float *b, int bh, int bw);
void MatNF_FillIdentity(float *a, int n);
void MatNF_Copy(float *a, float *b, int h, int w);
void Vec16F_RotateMatrix(float *amat, float *angles, float *bmat);
void MatNF_GetLowerMatrix(float *a, float *b, int n);
void MatNF_GetUpperMatrix(float *a, float *b, int n);
void Vec16F_TranslateMatrix(float *amat, float *pos, float *bmat);
void Vec16F_ScaleMatrix(float *amat, float *pos, float *bmat);
void MatNF_SwapOrder(float *a, float *b, int n);
void MatNF_Inverse(float *a, float *b, int n);
void Vec3F_ToSphericalCoords(float *a, float *b);
void Vec3F_FromSphericalCoords(float *a, float *b);
void Vec16F_InvertAngles(float *amat, float *bmat);
void Vec3F_RotatePoint(float *p, float *angles);
void Vec3F_CalcAngleVectors(float *angles, float *forward, float *right, float *up);
void Vec3F_NormalToParentSpace(float *a, float *sp, float *b);
void Vec3F_NormalFromParentSpace(float *a, float *sp, float *b);
void Vec3F_NormalToChildSpace(float *a, float *sp, float *b);
void Vec3F_NormalFromChildSpace(float *a, float *sp, float *b);
void Vec3F_PointToParentSpace(float *a, float *sp, float *b);
void Vec3F_PointFromParentSpace(float *a, float *sp, float *b);
void Vec3F_PointToChildSpace(float *a, float *sp, float *b);
void Vec3F_PointFromChildSpace(float *a, float *sp, float *b);
float Scaler_Random();
float Scaler_SignRandom();
