#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef signed char			sbyte;
typedef unsigned char			byte;
typedef signed short			s16;
typedef unsigned short		u16;
typedef signed int			s32;
typedef unsigned int			u32;
typedef signed long long		s64;
typedef unsigned long long	u64;

byte *LoadFile(char *name, int *rsz)
{
	FILE *fd;
	byte *buf;
	int sz;
	
	fd=fopen(name, "rb");
	if(!fd)
		return(NULL);
		
	fseek(fd, 0, 2);
	sz=ftell(fd);
	fseek(fd, 0, 0);
	buf=malloc(sz+64);
	memset(buf, 0, sz+64);

	fread(buf, 1, sz, fd);
	fclose(fd);
	
	if(rsz)
		*rsz=sz;
	return(buf);
}

int main()
{
	char tb1[256];
	FILE *ofd;
	byte *ibuf;
	byte *ics;
	char *ict;
	int isz, nl;
	int i, j, k;
	
//	ibuf=LoadFile("StreetHolland.jpg", &isz);
	ibuf=LoadFile("StreetHolland_320.jpg", &isz);
	if(!ibuf)
		return(-1);
	
	ofd=fopen("gen_jpg2c.c", "wt");
	
	if(!ofd)
	{
		return(-1);
	}
	
	fprintf(ofd, "/* Autogenerated */\n");
	fprintf(ofd, "#define JPG2STR_SIZE %d\n", isz);
	
	ics=ibuf;
	nl=(isz+15)/16;
	for(i=0; i<nl; i++)
	{
		ict=tb1;
//		*ict++='\"';
		
		for(j=0; j<4; j++)
		{
//			k=*ics++;
			k=ics[0]+(ics[1]<<8)+(ics[2]<<16)+(ics[3]<<24);
			ics+=4;

//			sprintf(ict, "\\x%02X", k);
			sprintf(ict, "0x%08X,", k);
			ict+=strlen(ict);
			continue;

#if 0
			if(!k)
			{
				*ict++='\\';
				*ict++='0';
				continue;
			}
			
			if((k=='\'') || (k=='\"'))
			{
				*ict++='\\';
				*ict++=k;
				continue;
			}
			
			if((k<' ') || (k>'~'))
			{
				sprintf(ict, "\\x%02X", k);
				ict+=strlen(ict);
				continue;
			}
			
			*ict++=k;
#endif
		}
		
//		*ict++='\"';
		*ict++='\n';
		*ict=0;
		
		fputs(tb1, ofd);
	}
	
	fclose(ofd);
	return(0);
}
