set_property PACKAGE_PIN R7 [get_ports {ddrData[0]}]
set_property PACKAGE_PIN V5 [get_ports {ddrData[10]}]
set_property PACKAGE_PIN U4 [get_ports {ddrData[11]}]
set_property PACKAGE_PIN V4 [get_ports {ddrData[12]}]
set_property PACKAGE_PIN T4 [get_ports {ddrData[13]}]
set_property PACKAGE_PIN V1 [get_ports {ddrData[14]}]
set_property PACKAGE_PIN T3 [get_ports {ddrData[15]}]
set_property PACKAGE_PIN V6 [get_ports {ddrData[1]}]
set_property PACKAGE_PIN R8 [get_ports {ddrData[2]}]
set_property PACKAGE_PIN U7 [get_ports {ddrData[3]}]
set_property PACKAGE_PIN V7 [get_ports {ddrData[4]}]
set_property PACKAGE_PIN R6 [get_ports {ddrData[5]}]
set_property PACKAGE_PIN U6 [get_ports {ddrData[6]}]
set_property PACKAGE_PIN R5 [get_ports {ddrData[7]}]
set_property PACKAGE_PIN T5 [get_ports {ddrData[8]}]
set_property PACKAGE_PIN U3 [get_ports {ddrData[9]}]
set_property PACKAGE_PIN U9 [get_ports {ddrDqsP[0]}]
set_property PACKAGE_PIN V9 [get_ports {ddrDqsN[0]}]
create_clock -period 10.000 -name clock0 -waveform {0.000 5.000} [get_ports clock]

set_property PACKAGE_PIN D8 [get_ports {vgaBlu[3]}]
set_property PACKAGE_PIN D7 [get_ports {vgaBlu[2]}]
set_property PACKAGE_PIN C7 [get_ports {vgaBlu[1]}]
set_property PACKAGE_PIN B7 [get_ports {vgaBlu[0]}]
set_property PACKAGE_PIN A6 [get_ports {vgaGrn[3]}]
set_property PACKAGE_PIN B6 [get_ports {vgaGrn[2]}]
set_property PACKAGE_PIN A5 [get_ports {vgaGrn[1]}]
set_property PACKAGE_PIN C6 [get_ports {vgaGrn[0]}]
set_property PACKAGE_PIN A4 [get_ports {vgaRed[3]}]
set_property PACKAGE_PIN C5 [get_ports {vgaRed[2]}]
set_property PACKAGE_PIN B4 [get_ports {vgaRed[1]}]
set_property PACKAGE_PIN A3 [get_ports {vgaRed[0]}]
set_property PACKAGE_PIN B11 [get_ports vgaHsync]
set_property PACKAGE_PIN B12 [get_ports vgaVsync]
set_property PACKAGE_PIN E3 [get_ports clock]
set_property PACKAGE_PIN C12 [get_ports reset]
set_property PACKAGE_PIN M4 [get_ports {ddrAddr[0]}]
set_property PACKAGE_PIN R2 [get_ports {ddrAddr[10]}]
set_property PACKAGE_PIN K5 [get_ports {ddrAddr[11]}]
set_property PACKAGE_PIN N6 [get_ports {ddrAddr[12]}]
set_property PACKAGE_PIN P4 [get_ports {ddrAddr[1]}]
set_property PACKAGE_PIN M6 [get_ports {ddrAddr[2]}]
set_property PACKAGE_PIN T1 [get_ports {ddrAddr[3]}]
set_property PACKAGE_PIN L3 [get_ports {ddrAddr[4]}]
set_property PACKAGE_PIN P5 [get_ports {ddrAddr[5]}]
set_property PACKAGE_PIN M2 [get_ports {ddrAddr[6]}]
set_property PACKAGE_PIN N1 [get_ports {ddrAddr[7]}]
set_property PACKAGE_PIN L4 [get_ports {ddrAddr[8]}]
set_property PACKAGE_PIN N5 [get_ports {ddrAddr[9]}]
set_property PACKAGE_PIN P2 [get_ports {ddrBa[0]}]
set_property PACKAGE_PIN P3 [get_ports {ddrBa[1]}]
set_property PACKAGE_PIN R1 [get_ports {ddrBa[2]}]
set_property PACKAGE_PIN L1 [get_ports ddrCas]
set_property PACKAGE_PIN M1 [get_ports ddrCke]
set_property PACKAGE_PIN K6 [get_ports ddrCs]
set_property PACKAGE_PIN N2 [get_ports ddrWe]
set_property PACKAGE_PIN N4 [get_ports ddrRas]
set_property PACKAGE_PIN L6 [get_ports {ddrClk[0]}]
set_property PACKAGE_PIN L5 [get_ports {ddrClk[1]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrAddr[12]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrAddr[11]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrAddr[10]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrAddr[9]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrAddr[8]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrAddr[7]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrAddr[6]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrAddr[5]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrAddr[4]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrAddr[3]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrAddr[2]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrAddr[1]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrAddr[0]}]
set_property SLEW FAST [get_ports {ddrAddr[12]}]
set_property SLEW FAST [get_ports {ddrAddr[11]}]
set_property SLEW FAST [get_ports {ddrAddr[10]}]
set_property SLEW FAST [get_ports {ddrAddr[9]}]
set_property SLEW FAST [get_ports {ddrAddr[8]}]
set_property SLEW FAST [get_ports {ddrAddr[7]}]
set_property SLEW FAST [get_ports {ddrAddr[6]}]
set_property SLEW FAST [get_ports {ddrAddr[5]}]
set_property SLEW FAST [get_ports {ddrAddr[4]}]
set_property SLEW FAST [get_ports {ddrAddr[3]}]
set_property SLEW FAST [get_ports {ddrAddr[2]}]
set_property SLEW FAST [get_ports {ddrAddr[1]}]
set_property SLEW FAST [get_ports {ddrAddr[0]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrBa[2]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrBa[1]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrBa[0]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrClk[1]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrClk[0]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrData[15]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrData[14]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrData[13]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrData[12]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrData[11]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrData[10]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrData[9]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrData[8]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrData[7]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrData[6]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrData[5]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrData[4]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrData[3]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrData[2]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrData[1]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrData[0]}]
set_property IOSTANDARD SSTL18_II [get_ports ddrCas]
set_property IOSTANDARD SSTL18_II [get_ports ddrCke]
set_property IOSTANDARD SSTL18_II [get_ports ddrCs]
set_property IOSTANDARD SSTL18_II [get_ports ddrRas]
set_property IOSTANDARD SSTL18_II [get_ports ddrWe]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlu[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlu[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlu[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlu[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGrn[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGrn[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGrn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGrn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[0]}]
set_property INTERNAL_VREF 0.9 [get_iobanks 34]

set_property PACKAGE_PIN C2 [get_ports {sdc_dat[0]}]
set_property PACKAGE_PIN D2 [get_ports {sdc_dat[3]}]
set_property PACKAGE_PIN E1 [get_ports {sdc_dat[1]}]
set_property PACKAGE_PIN F1 [get_ports {sdc_dat[2]}]
set_property PACKAGE_PIN F4 [get_ports ps2_clk]
set_property PACKAGE_PIN B2 [get_ports ps2_data]
set_property PACKAGE_PIN A11 [get_ports aud_mono_out]
set_property PACKAGE_PIN D4 [get_ports uartTxD]
set_property PACKAGE_PIN C4 [get_ports uartRxD]
set_property PACKAGE_PIN E5 [get_ports uartCtS]
set_property PACKAGE_PIN D3 [get_ports uartRtS]
set_property PACKAGE_PIN E2 [get_ports sdc_ena]
set_property PACKAGE_PIN C1 [get_ports sdc_cmd]
set_property PACKAGE_PIN B1 [get_ports sdc_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {sdc_dat[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sdc_dat[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sdc_dat[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sdc_dat[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data]
set_property IOSTANDARD LVCMOS33 [get_ports sdc_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sdc_cmd]
set_property IOSTANDARD LVCMOS33 [get_ports sdc_ena]
set_property IOSTANDARD LVCMOS33 [get_ports uartCtS]
set_property IOSTANDARD LVCMOS33 [get_ports uartRtS]
set_property IOSTANDARD LVCMOS33 [get_ports uartRxD]
set_property IOSTANDARD LVCMOS33 [get_ports uartTxD]
set_property IOSTANDARD LVCMOS33 [get_ports vgaHsync]
set_property IOSTANDARD LVCMOS33 [get_ports vgaVsync]
set_property IOSTANDARD LVCMOS33 [get_ports aud_mono_out]
set_property IOSTANDARD LVCMOS33 [get_ports reset]


set_property SLEW FAST [get_ports {ddrData[15]}]
set_property SLEW FAST [get_ports {ddrData[14]}]
set_property SLEW FAST [get_ports {ddrData[13]}]
set_property SLEW FAST [get_ports {ddrData[12]}]
set_property SLEW FAST [get_ports {ddrData[11]}]
set_property SLEW FAST [get_ports {ddrData[10]}]
set_property SLEW FAST [get_ports {ddrData[9]}]
set_property SLEW FAST [get_ports {ddrData[8]}]
set_property SLEW FAST [get_ports {ddrData[7]}]
set_property SLEW FAST [get_ports {ddrData[6]}]
set_property SLEW FAST [get_ports {ddrData[5]}]
set_property SLEW FAST [get_ports {ddrData[4]}]
set_property SLEW FAST [get_ports {ddrData[3]}]
set_property SLEW FAST [get_ports {ddrData[2]}]
set_property SLEW FAST [get_ports {ddrData[1]}]
set_property SLEW FAST [get_ports {ddrData[0]}]




set_property PACKAGE_PIN H17 [get_ports dbg_exHold1]
set_property PACKAGE_PIN K15 [get_ports dbg_exHold2]
set_property IOSTANDARD LVCMOS33 [get_ports dbg_exHold1]
set_property IOSTANDARD LVCMOS33 [get_ports dbg_exHold2]

set_property PACKAGE_PIN J13 [get_ports dbg_outStatus1]
set_property PACKAGE_PIN N14 [get_ports dbg_outStatus2]
set_property PACKAGE_PIN R18 [get_ports dbg_outStatus3]
set_property PACKAGE_PIN V17 [get_ports dbg_outStatus4]
set_property IOSTANDARD LVCMOS33 [get_ports dbg_outStatus4]
set_property IOSTANDARD LVCMOS33 [get_ports dbg_outStatus3]
set_property IOSTANDARD LVCMOS33 [get_ports dbg_outStatus2]
set_property IOSTANDARD LVCMOS33 [get_ports dbg_outStatus1]
set_property PACKAGE_PIN T10 [get_ports {seg_outSegBit[0]}]
set_property PACKAGE_PIN R10 [get_ports {seg_outSegBit[1]}]
set_property PACKAGE_PIN K16 [get_ports {seg_outSegBit[2]}]
set_property PACKAGE_PIN K13 [get_ports {seg_outSegBit[3]}]
set_property PACKAGE_PIN P15 [get_ports {seg_outSegBit[4]}]
set_property PACKAGE_PIN T11 [get_ports {seg_outSegBit[5]}]
set_property PACKAGE_PIN L18 [get_ports {seg_outSegBit[6]}]
set_property PACKAGE_PIN H15 [get_ports {seg_outSegBit[7]}]
set_property PACKAGE_PIN U13 [get_ports {seg_outCharBit[0]}]
set_property PACKAGE_PIN K2 [get_ports {seg_outCharBit[1]}]
set_property PACKAGE_PIN T14 [get_ports {seg_outCharBit[2]}]
set_property PACKAGE_PIN P14 [get_ports {seg_outCharBit[3]}]
set_property PACKAGE_PIN J14 [get_ports {seg_outCharBit[4]}]
set_property PACKAGE_PIN T9 [get_ports {seg_outCharBit[5]}]
set_property PACKAGE_PIN J18 [get_ports {seg_outCharBit[6]}]
set_property PACKAGE_PIN J17 [get_ports {seg_outCharBit[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_outCharBit[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_outCharBit[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_outCharBit[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_outCharBit[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_outCharBit[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_outCharBit[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_outCharBit[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_outCharBit[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_outSegBit[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_outSegBit[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_outSegBit[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_outSegBit[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_outSegBit[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_outSegBit[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_outSegBit[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_outSegBit[0]}]

set_property PACKAGE_PIN U2 [get_ports {ddrDqsP[1]}]
set_property PACKAGE_PIN V2 [get_ports {ddrDqsN[1]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrDqsN[1]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrDqsN[0]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrDqsP[1]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrDqsP[0]}]

set_property SLEW FAST [get_ports {ddrBa[2]}]
set_property SLEW FAST [get_ports {ddrBa[1]}]
set_property SLEW FAST [get_ports {ddrBa[0]}]
set_property SLEW FAST [get_ports {ddrClk[1]}]
set_property SLEW FAST [get_ports {ddrClk[0]}]
set_property SLEW FAST [get_ports {ddrDqsN[1]}]
set_property SLEW FAST [get_ports {ddrDqsN[0]}]
set_property SLEW FAST [get_ports {ddrDqsP[1]}]
set_property SLEW FAST [get_ports {ddrDqsP[0]}]
set_property SLEW FAST [get_ports ddrCas]
set_property SLEW FAST [get_ports ddrCke]
set_property SLEW FAST [get_ports ddrCs]
set_property SLEW FAST [get_ports ddrRas]
set_property SLEW FAST [get_ports ddrWe]

set_property PACKAGE_PIN U17 [get_ports dbg_outStatus5]
set_property PACKAGE_PIN U16 [get_ports dbg_outStatus6]
set_property PACKAGE_PIN V16 [get_ports dbg_outStatus7]
set_property PACKAGE_PIN T15 [get_ports dbg_outStatus8]
set_property IOSTANDARD LVCMOS33 [get_ports dbg_outStatus5]
set_property IOSTANDARD LVCMOS33 [get_ports dbg_outStatus6]
set_property IOSTANDARD LVCMOS33 [get_ports dbg_outStatus7]
set_property IOSTANDARD LVCMOS33 [get_ports dbg_outStatus8]

set_property PACKAGE_PIN K3 [get_ports {ddrAddr[13]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddrAddr[13]}]
set_property SLEW FAST [get_ports {ddrAddr[13]}]

set_property PACKAGE_PIN D12 [get_ports aud_mono_en]
set_property IOSTANDARD LVCMOS33 [get_ports aud_mono_en]

set_property SLEW FAST [get_ports {sdc_dat[3]}]
set_property SLEW FAST [get_ports {sdc_dat[2]}]
set_property SLEW FAST [get_ports {sdc_dat[1]}]
set_property SLEW FAST [get_ports {sdc_dat[0]}]
set_property SLEW FAST [get_ports sdc_clk]
set_property SLEW FAST [get_ports sdc_cmd]
set_property SLEW FAST [get_ports sdc_ena]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

set_input_delay -add_delay 0.250 [get_ports {{ddrData[0]} {ddrData[1]} {ddrData[2]} {ddrData[3]} {ddrData[4]} {ddrData[5]} {ddrData[6]} {ddrData[7]} {ddrData[8]} {ddrData[9]} {ddrData[10]} {ddrData[11]} {ddrData[12]} {ddrData[13]} {ddrData[14]} {ddrData[15]} {ddrDqsN[0]} {ddrDqsN[1]} {ddrDqsP[0]} {ddrDqsP[1]}}]
set_output_delay -clock [get_clocks [get_clocks -of_objects [get_pins genclock/CLKOUT2]]] -max 0.100 [get_ports {{ddrData[0]} {ddrData[1]} {ddrData[2]} {ddrData[3]} {ddrData[4]} {ddrData[5]} {ddrData[6]} {ddrData[7]} {ddrData[8]} {ddrData[9]} {ddrData[10]} {ddrData[11]} {ddrData[12]} {ddrData[13]} {ddrData[14]} {ddrData[15]}}]
set_output_delay -clock [get_clocks [get_clocks -of_objects [get_pins genclock/CLKOUT2]]] -max 0.100 [get_ports {{ddrAddr[0]} {ddrAddr[1]} {ddrAddr[2]} {ddrAddr[3]} {ddrAddr[4]} {ddrAddr[5]} {ddrAddr[6]} {ddrAddr[7]} {ddrAddr[8]} {ddrAddr[9]} {ddrAddr[10]} {ddrAddr[11]} {ddrAddr[12]} {ddrAddr[13]} {ddrBa[0]} {ddrBa[1]} {ddrBa[2]} ddrCas ddrCke ddrCs ddrRas ddrWe}]
set_input_delay -clock [get_clocks [get_clocks -of_objects [get_pins genclock/CLKOUT4]]] -add_delay 3.000 [get_ports {ps2_clk ps2_data {sdc_dat[0]} {sdc_dat[1]} {sdc_dat[2]} {sdc_dat[3]}}]
set_output_delay -clock [get_clocks [get_clocks -of_objects [get_pins genclock/CLKOUT4]]] -max 2.000 [get_ports {ps2_clk ps2_data {sdc_dat[0]} {sdc_dat[1]} {sdc_dat[2]} {sdc_dat[3]}}]

set_input_delay -clock [get_clocks [get_clocks -of_objects [get_pins genclock/CLKOUT4]]] -add_delay 3.000 [get_ports {reset uartCtS uartRxD}]


set_output_delay -clock [get_clocks [get_clocks -of_objects [get_pins genclock/CLKOUT4]]] -max 2.000 [get_ports {aud_mono_en aud_mono_out aud_mic_clk aud_mic_lr dbg_exHold1 dbg_exHold2 dbg_outStatus1 dbg_outStatus2 dbg_outStatus3 dbg_outStatus4 dbg_outStatus5 dbg_outStatus6 dbg_outStatus7 dbg_outStatus8 sdc_clk sdc_cmd sdc_ena {seg_outCharBit[0]} {seg_outCharBit[1]} {seg_outCharBit[2]} {seg_outCharBit[3]} {seg_outCharBit[4]} {seg_outCharBit[5]} {seg_outCharBit[6]} {seg_outCharBit[7]} {seg_outSegBit[0]} {seg_outSegBit[1]} {seg_outSegBit[2]} {seg_outSegBit[3]} {seg_outSegBit[4]} {seg_outSegBit[5]} {seg_outSegBit[6]} {seg_outSegBit[7]} uartRtS uartTxD {vgaBlu[0]} {vgaBlu[1]} {vgaBlu[2]} {vgaBlu[3]} {vgaGrn[0]} {vgaGrn[1]} {vgaGrn[2]} {vgaGrn[3]} vgaHsync {vgaRed[0]} {vgaRed[1]} {vgaRed[2]} {vgaRed[3]} vgaVsync}]


set_output_delay -clock [get_clocks [get_clocks -of_objects [get_pins genclock/CLKOUT4]]] -min 1.000 [get_ports {aud_mono_en aud_mono_out aud_mic_clk aud_mic_lr dbg_exHold1 dbg_exHold2 dbg_outStatus1 dbg_outStatus2 dbg_outStatus3 dbg_outStatus4 dbg_outStatus5 dbg_outStatus6 dbg_outStatus7 dbg_outStatus8 sdc_clk sdc_cmd sdc_ena {seg_outCharBit[0]} {seg_outCharBit[1]} {seg_outCharBit[2]} {seg_outCharBit[3]} {seg_outCharBit[4]} {seg_outCharBit[5]} {seg_outCharBit[6]} {seg_outCharBit[7]} {seg_outSegBit[0]} {seg_outSegBit[1]} {seg_outSegBit[2]} {seg_outSegBit[3]} {seg_outSegBit[4]} {seg_outSegBit[5]} {seg_outSegBit[6]} {seg_outSegBit[7]} uartRtS uartTxD {vgaBlu[0]} {vgaBlu[1]} {vgaBlu[2]} {vgaBlu[3]} {vgaGrn[0]} {vgaGrn[1]} {vgaGrn[2]} {vgaGrn[3]} vgaHsync {vgaRed[0]} {vgaRed[1]} {vgaRed[2]} {vgaRed[3]} vgaVsync}]
set_output_delay -clock [get_clocks [get_clocks -of_objects [get_pins genclock/CLKOUT4]]] -min 1.000 [get_ports {ps2_clk ps2_data {sdc_dat[0]} {sdc_dat[1]} {sdc_dat[2]} {sdc_dat[3]}}]



set_output_delay -clock [get_clocks [get_clocks -of_objects [get_pins genclock/CLKOUT2]]] -clock_fall -max 0.100 [get_ports {{ddrDqsN[0]} {ddrDqsN[1]} {ddrDqsP[0]} {ddrDqsP[1]}}]
set_output_delay -clock [get_clocks [get_clocks -of_objects [get_pins genclock/CLKOUT2]]] -clock_fall -max 0.100 [get_ports {{ddrClk[0]} {ddrClk[1]}}]

set_output_delay -clock [get_clocks [get_clocks -of_objects [get_pins genclock/CLKOUT2]]] -min 0.025 [get_ports {{ddrData[0]} {ddrData[1]} {ddrData[2]} {ddrData[3]} {ddrData[4]} {ddrData[5]} {ddrData[6]} {ddrData[7]} {ddrData[8]} {ddrData[9]} {ddrData[10]} {ddrData[11]} {ddrData[12]} {ddrData[13]} {ddrData[14]} {ddrData[15]}}]
set_output_delay -clock [get_clocks [get_clocks -of_objects [get_pins genclock/CLKOUT2]]] -min 0.025 [get_ports {{ddrAddr[0]} {ddrAddr[1]} {ddrAddr[2]} {ddrAddr[3]} {ddrAddr[4]} {ddrAddr[5]} {ddrAddr[6]} {ddrAddr[7]} {ddrAddr[8]} {ddrAddr[9]} {ddrAddr[10]} {ddrAddr[11]} {ddrAddr[12]} {ddrAddr[13]} {ddrBa[0]} {ddrBa[1]} {ddrBa[2]} ddrCas ddrCke ddrCs ddrRas ddrWe}]
set_output_delay -clock [get_clocks [get_clocks -of_objects [get_pins genclock/CLKOUT2]]] -clock_fall -min 0.025 [get_ports {{ddrDqsN[0]} {ddrDqsN[1]} {ddrDqsP[0]} {ddrDqsP[1]}}]
set_output_delay -clock [get_clocks [get_clocks -of_objects [get_pins genclock/CLKOUT2]]] -clock_fall -min 0.025 [get_ports {{ddrClk[0]} {ddrClk[1]}}]





set_property IOSTANDARD LVCMOS33 [get_ports aud_mic_lr]
set_property IOSTANDARD LVCMOS33 [get_ports aud_mic_data]
set_property IOSTANDARD LVCMOS33 [get_ports aud_mic_clk]
set_property PACKAGE_PIN J5 [get_ports aud_mic_clk]
set_property PACKAGE_PIN H5 [get_ports aud_mic_data]
set_property PACKAGE_PIN F5 [get_ports aud_mic_lr]
set_input_delay -clock [get_clocks [get_clocks -of_objects [get_pins genclock/CLKOUT4]]] 3.000 [get_ports aud_mic_data]
