/* Autogenerated.  */
module ExModKrrFixSh(
	val0I, val1I, val2I, val3I,
	val0O, val1O, val2O, val3O);
input[63:0] val0I;
input[63:0] val1I;
input[63:0] val2I;
input[63:0] val3I;
output[63:0] val0O;
output[63:0] val1O;
output[63:0] val2O;
output[63:0] val3O;
assign val0O = {
	val0I[61], val0I[60], val0I[19], val0I[58], 
	val0I[57], val0I[21], val0I[26], val0I[63], 
	val0I[53], val0I[52], val0I[51], val0I[11], 
	val0I[48], val0I[62], val0I[47], val0I[ 4], 
	val0I[45], val0I[44], val0I[15], val0I[42], 
	val0I[24], val0I[40], val0I[39], val0I[38], 
	val0I[12], val0I[36], val0I[35], val0I[34], 
	val0I[13], val0I[18], val0I[ 9], val0I[17], 
	val0I[20], val0I[28], val0I[27], val0I[49], 
	val0I[ 2], val0I[33], val0I[41], val0I[46], 
	val0I[ 6], val0I[ 8], val0I[29], val0I[10], 
	val0I[14], val0I[16], val0I[30], val0I[54], 
	val0I[31], val0I[23], val0I[32], val0I[25], 
	val0I[ 3], val0I[55], val0I[43], val0I[50], 
	val0I[ 5], val0I[37], val0I[ 1], val0I[59], 
	val0I[56], val0I[ 0], val0I[ 7], val0I[22]
};
assign val1O = {
	val1I[20], val1I[62], val1I[59], val1I[ 1], 
	val1I[23], val1I[56], val1I[55], val1I[54], 
	val1I[53], val1I[ 2], val1I[51], val1I[ 9], 
	val1I[ 7], val1I[29], val1I[58], val1I[17], 
	val1I[45], val1I[44], val1I[43], val1I[26], 
	val1I[14], val1I[21], val1I[19], val1I[38], 
	val1I[37], val1I[36], val1I[35], val1I[27], 
	val1I[ 6], val1I[13], val1I[18], val1I[32], 
	val1I[ 3], val1I[50], val1I[31], val1I[48], 
	val1I[42], val1I[41], val1I[ 8], val1I[15], 
	val1I[30], val1I[28], val1I[16], val1I[39], 
	val1I[ 4], val1I[46], val1I[49], val1I[33], 
	val1I[25], val1I[61], val1I[40], val1I[47], 
	val1I[10], val1I[60], val1I[ 0], val1I[22], 
	val1I[11], val1I[57], val1I[12], val1I[52], 
	val1I[63], val1I[24], val1I[ 5], val1I[34]
};
assign val2O = {
	val2I[56], val2I[50], val2I[63], val2I[62], 
	val2I[ 4], val2I[60], val2I[59], val2I[ 3], 
	val2I[10], val2I[16], val2I[55], val2I[54], 
	val2I[53], val2I[ 8], val2I[28], val2I[51], 
	val2I[49], val2I[24], val2I[47], val2I[46], 
	val2I[ 9], val2I[44], val2I[25], val2I[42], 
	val2I[41], val2I[40], val2I[ 6], val2I[38], 
	val2I[37], val2I[36], val2I[26], val2I[13], 
	val2I[15], val2I[17], val2I[21], val2I[30], 
	val2I[29], val2I[57], val2I[12], val2I[43], 
	val2I[14], val2I[ 0], val2I[58], val2I[31], 
	val2I[61], val2I[34], val2I[32], val2I[18], 
	val2I[45], val2I[19], val2I[35], val2I[39], 
	val2I[52], val2I[20], val2I[33], val2I[22], 
	val2I[ 1], val2I[23], val2I[ 7], val2I[48], 
	val2I[11], val2I[27], val2I[ 5], val2I[ 2]
};
assign val3O = {
	val3I[ 3], val3I[62], val3I[14], val3I[10], 
	val3I[61], val3I[49], val3I[ 6], val3I[58], 
	val3I[57], val3I[56], val3I[55], val3I[ 4], 
	val3I[53], val3I[30], val3I[17], val3I[28], 
	val3I[12], val3I[18], val3I[47], val3I[46], 
	val3I[45], val3I[27], val3I[26], val3I[13], 
	val3I[20], val3I[40], val3I[39], val3I[38], 
	val3I[37], val3I[ 0], val3I[16], val3I[32], 
	val3I[29], val3I[23], val3I[50], val3I[22], 
	val3I[36], val3I[44], val3I[15], val3I[ 2], 
	val3I[59], val3I[ 8], val3I[42], val3I[63], 
	val3I[41], val3I[33], val3I[48], val3I[21], 
	val3I[24], val3I[43], val3I[34], val3I[ 5], 
	val3I[ 7], val3I[11], val3I[52], val3I[25], 
	val3I[51], val3I[35], val3I[ 1], val3I[19], 
	val3I[31], val3I[54], val3I[60], val3I[ 9]
};
endmodule
