/* Autogenerated source */
#include <stdio.h>

int bgbcc_tokord_nops=123;

char *bgbcc_tokord_strs[]={
"", "auto", "abstract", "as", "base", "bool", "boolean", "break", 
"byte", "case", "catch", "char", "checked", "class", "const", "continue", 
"decimal", "default", "delegate", "do", "double", "else", "enum", 
"event", "explicit", "extends", "extern", "false", "final", "finally", 
"fixed", "float", "for", "foreach", "goto", "if", "implements", "implicit", 
"import", "in", "inline", "instanceof", "int", "interface", "internal", 
"is", "lock", "long", "namespace", "native", "new", "null", "object", 
"operator", "out", "override", "package", "params", "private", "protected", 
"public", "readonly", "ref", "register", "restrict", "return", "sbyte", 
"sealed", "short", "signed", "sizeof", "stackalloc", "static", "string", 
"struct", "super", "synchronized", "switch", "this", "throw", "throws", 
"transient", "true", "try", "typedef", "typeof", "uint", "ulong", 
"unchecked", "union", "unsafe", "unsigned", "ushort", "using", "virtual", 
"void", "volatile", "while", "_Bool", "_Complex", "_Imaginary", "__inline", 
"__forceinline", "__stdcall", "__cdecl", "__proxy", "__w64", "__ptr64", 
"__ptr32", "__win64", "__amd64", "__xcall", "__packed", "__gc", "__nogc", 
"__wide", "__public", "__private", "__protected", "__final", "__virtual", 
"__native", "__abstract", NULL};

char *bgbcc_tokord_args[]={
"", "CPm", "PJSm", "S", "Sv", "PSt", "JEt", "CPJSEs", "St", "CPJSEs", 
"PJSEs", "CPJSEt", "S", "PJSEs", "CPJSEm", "CPJSEs", "St", "CPJSEs", 
"Ss", "CPJSEs", "CPJSEt", "CPJSEk", "CPJSEs", "Sm", "Sm", "JEk", 
"CPJSEm", "Sv", "JEm", "PJSEk", "Sm", "CPJSEt", "CPJSEs", "Ss", "CPJSEs", 
"CPJSEs", "JEk", "Sm", "JEs", "JEk", "CPm", "JEb", "CPJSEt", "JSEs", 
"Sm", "Sb", "Sm", "CPJSEt", "PSs", "JEm", "PJSEme", "JSEv", "St", 
"PSk", "Sm", "Sm", "JEs", "S", "PJSEm", "PJSEm", "PJSEm", "Sm", "Sm", 
"CPm", "CPm", "CPJSEs", "St", "Sm", "CPJSEt", "CPm", "CPSe", "Se", 
"CPJSEm", "St", "CPSk", "Jv", "Jm", "CPJSEs", "PJSEv", "PJSEs", "JEk", 
"JEm", "Sv", "PJSEs", "CPs", "PJSEe", "St", "St", "S", "CPk", "S", 
"CPm", "St", "Ss", "PSm", "CPJSEt", "CPJSEm", "CPJSEs", "Ct", "Cm", 
"Cm", "CPm", "CPm", "CPm", "CPm", "CPm", "CPm", "CPm", "CPm", "CPm", 
"CPm", "CPm", "CPm", "CPm", "CPm", "CPm", "Cm", "Cm", "Cm", "Cm", 
"Cm", "Cm", "Cm", NULL};

char *bgbcc_tokord_sfis[]={
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
"", "", "", "", NULL};

